/* Offline creation and campaign editing. Every mutation joins the existing draft. */
(()=>{
const state=()=>window.MPB_WORKSHOP_STATE;
const option=(id,label,active)=>'<option value="'+esc(id)+'" '+(id===active?'selected':'')+'>'+esc(label)+'</option>';
const figureOptions=()=>records.map(r=>option(r.id,r.name+' / '+r.soulClass+' / '+r.id,'')).join('');
const update=fn=>{checkpoint();fn();persist();if($('worldUndo'))$('worldUndo').disabled=false;};
const dialog=document.createElement('dialog');dialog.id='world';document.body.append(dialog);
const create=document.createElement('dialog');create.id='createFigure';document.body.append(create);
document.querySelector('nav').insertAdjacentHTML('beforeend','<button id="newFigure">＋ 画像から追加</button><button id="editWorld">タワー・ガチャ</button>');
let towerId=Object.keys(state().towers)[0],floorIndex=0,enemyIndex=0,bannerId=Object.keys(state().banners)[0],mode='tower';
const originalRender=render;
render=function(){originalRender();document.querySelector('h1 span').textContent=records.length;$('figureIDs').innerHTML=records.map(r=>'<option value="'+esc(r.id)+'">'+esc(r.name)+'</option>').join('');};
const oldChanges=renderChanges;
renderChanges=function(list){oldChanges(list);const w=state(),t=Object.values(w.towers).filter(t=>!C.equal(t,D.workshop.towers[t.id])),b=Object.values(w.banners).filter(b=>!C.equal(b,D.workshop.banners[b.id]));$('changes').insertAdjacentHTML('afterbegin','<div class="notice">追加・差替画像 '+Object.keys(w.images).length+'件 / タワー変更 '+t.length+'件 / ガチャ変更 '+b.length+'件。これらも保存ファイルに含まれます。<br>'+esc([...t,...b].map(x=>x.name).join(' / '))+'</div>');};
const originalEditor=renderEditor;
renderEditor=function(){originalEditor();if(!current())return;const label=document.createElement('label');label.className='uploadImage';label.innerHTML='画像を差し替える（PNG / JPEG / WebP）<input id="replaceImage" type="file" accept="image/png,image/jpeg,image/webp"><span class="imageStatus"></span>';$('editorBody').querySelector('.hero').after(label);label.querySelector('input').onchange=async e=>{const id=current().id;try{const image=await readImage(e.target.files[0]);update(()=>{state().images[id]=image;});if(current()?.id===id)renderEditor();}catch(error){label.querySelector('span').textContent=error.message;}};};
async function readImage(file){
 if(!file)throw Error('画像を選択してください');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('20MB以下のPNG・JPEG・WebPを選択してください');
 const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(!img.width||!img.height)throw Error('画像を読み込めません');const scale=Math.min(1,1200/img.width,1200/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/webp',.88);if(result.length>3*1024*1024)throw Error('画像が大きすぎます。小さい画像を選んでください');return result;}finally{URL.revokeObjectURL(url);}
}
$('newFigure').onclick=()=>{
 let uploaded='';create.innerHTML='<div class="dialogbar"><b>画像からフィギュアを追加</b><button id="cancelCreate">閉じる ×</button></div><form id="newForm" class="worldBody"><p>画像と名前を入れて追加。スキル・タグ・融合素材は、追加後の画面で編集できます。</p><label class="dropZone">画像を選択 / ここへドロップ<input id="newImage" type="file" accept="image/png,image/jpeg,image/webp" required><img id="newPreview" alt="追加する画像" hidden></label><div class="formgrid"><label>名前<input id="newName" required maxlength="100"></label><label>段階<select id="newClass"><option value="seed">Seed</option><option value="middle">Middle</option><option value="mob">MOB</option></select></label><label>レア度<select id="newRarity">'+['R','SR','SSR','UR','MOB'].map(r=>option(r,r,'R')).join('')+'</select></label><label>属性<input id="newAttribute" value="無" required></label><label>ATK<input id="newAtk" type="number" min="0" step="1" value="10" required></label><label>DEF<input id="newDef" type="number" min="0" step="1" value="10" required></label></div><p id="createStatus" role="status"></p><button id="submitFigure" class="primary" type="submit">追加して詳細を編集</button></form>';
 let template=null;
 create.querySelector('.dropZone').insertAdjacentHTML('afterend','<section class="copyPerformance"><h3>既存フィギュアから性能とタグをコピー</h3><label>名前・IDで検索<input id="templateSearch" type="search" placeholder="コピー元の名前を入力"></label><label>コピー元<select id="templateSelect">'+figureOptions()+'</select></label><p class="small">段階・レア度・属性・ATK・DEF・攻撃種別・役割・スキル・タグをコピーします。名前と画像はそのままです。</p><label><input id="templateSummon" type="checkbox">融合条件・パッシブもコピーする</label><button id="applyTemplate" type="button">選んだフィギュアの性能とタグをコピー</button><p id="templateStatus" role="status"></p></section>');
 $('templateSearch').oninput=()=>{const q=$('templateSearch').value.trim().toLocaleLowerCase();$('templateSelect').innerHTML=records.filter(r=>(r.name+' '+r.id).toLocaleLowerCase().includes(q)).map(r=>option(r.id,r.name+' / '+r.soulClass+' / '+r.id,'')).join('');$('applyTemplate').disabled=!$('templateSelect').value;};
 $('applyTemplate').onclick=()=>{const source=records.find(r=>r.id===$('templateSelect').value);if(!source)return;template=clone(source);for(const [id,key]of [['newClass','soulClass'],['newRarity','rarity'],['newAttribute','attribute'],['newAtk','atk'],['newDef','def']])$(id).value=source[key];$('templateStatus').textContent=source.name+' からコピー済み。スキル：'+source.skill.name+' / タグ：'+(source.tags.map(id=>tagNames.get(id)||id).join('・')||'なし')+'。数値はこの下で調整できます。';};
 $('cancelCreate').onclick=()=>create.close();const accept=async file=>{uploaded='';$('submitFigure').disabled=true;try{uploaded=await readImage(file);$('newPreview').src=uploaded;$('newPreview').hidden=false;$('newImage').required=false;$('createStatus').textContent='画像を準備しました';}catch(e){$('createStatus').textContent=e.message;}finally{$('submitFigure').disabled=false;}};
 $('newImage').onchange=e=>accept(e.target.files[0]);const drop=create.querySelector('.dropZone');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();accept(e.dataTransfer.files[0]);};
 $('newForm').onsubmit=e=>{e.preventDefault();if(!uploaded||!$('newName').value.trim()){$('createStatus').textContent='名前と画像を入力してください';return;}const id='custom-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));const soulClass=$('newClass').value;
 const r={id,uid:id,editorAdded:true,name:$('newName').value.trim(),series:'追加フィギュア',soulClass,rarity:$('newRarity').value,attribute:$('newAttribute').value,attackType:'',role:'',atk:Number($('newAtk').value),def:Number($('newDef').value),tags:[],gameImage:'custom-figures/'+id+'.webp',skill:{mode:'custom',name:'新しいスキル',description:'',timing:'',program:'',plan:{},custom:{target:'',timing:'',condition:'',cost:'',uses:'',example:''}},summon:{normal:soulClass==='seed',recipes:[],passive:{},notes:''}};
 if(template){for(const key of ['attackType','role','tags','skill'])r[key]=clone(template[key]);if($('templateSummon').checked){r.summon=clone(template.summon);r.summon.recipes=r.summon.recipes.map((recipe,i)=>({...recipe,id:id+'-recipe-'+(i+1),target:id}));}r.summon.normal=soulClass==='seed';}
 update(()=>{records.push(r);state().images[id]=uploaded;});create.close();render();openEditor(id);};create.showModal();
};
function picker(id){return '<div class="figurePicker"><label>名前・IDで検索<input id="'+id+'Search" type="search" placeholder="名前を入力"></label><label>フィギュア<select id="'+id+'Select">'+figureOptions()+'</select></label><button id="'+id+'Add">追加</button></div>';}
function bindPicker(id,add){$(id+'Search').oninput=()=>{const q=$(id+'Search').value.toLocaleLowerCase();$(id+'Select').innerHTML=records.filter(r=>(r.name+' '+r.id).toLocaleLowerCase().includes(q)).map(r=>option(r.id,r.name+' / '+r.soulClass+' / '+r.id,'')).join('');};$(id+'Add').onclick=()=>{const r=records.find(r=>r.id===$(id+'Select').value);if(r)add(r);};}
const figureName=id=>records.find(r=>r.id===id)?.name||id;
function rowImage(id){return '<img loading="lazy" src="'+esc(C.imageFor(id,D))+'" alt="">';}
function world(){
 if(!state().towers[towerId])towerId=Object.keys(state().towers)[0];if(!state().banners[bannerId])bannerId=Object.keys(state().banners)[0];
 dialog.innerHTML='<div class="dialogbar"><b>タワー・ガチャ工房</b><button id="worldUndo" '+(!history.length?'disabled':'')+'>1操作戻す</button><button id="closeWorld">閉じる ×</button></div><div class="worldBody"><div class="worldTabs"><button id="towerTab" class="'+(mode==='tower'?'primary':'')+'">タワー / 敵 / 報酬</button><button id="bannerTab" class="'+(mode==='banner'?'primary':'')+'">ガチャ / 解放条件</button><button id="worldExport">全編集データを保存</button></div><p class="notice">編集は自動下書き保存。画像を含めて「全編集データを保存」で持ち出せます。本体への適用は別途必要です。</p><div id="worldContent"></div><details><summary>全体チェック <span id="worldCheckCount"></span></summary><div id="worldChecks"></div></details></div>';
 $('closeWorld').onclick=()=>{dialog.close();render();};$('towerTab').onclick=()=>{mode='tower';world();};$('bannerTab').onclick=()=>{mode='banner';world();};$('worldExport').onclick=()=>download('MOB-PIECE-workshop-'+stamp()+'.json',snapshot(),'application/json');
 $('worldUndo').onclick=()=>{const old=history.pop();if(!old)return;if(old.source!==D)refreshSource(old.source);records=old.records;orphans=old.orphans;C.installWorkspace(old.workshop);persist();world();};
 if(mode==='tower')towerView();else bannerView();checks();
}
function checks(){const warnings=C.workshopWarnings(records,D);$('worldCheckCount').textContent=warnings.length?'（'+warnings.length+'件）':'（問題なし）';$('worldChecks').innerHTML=warnings.map(w=>'<p class="warning">'+esc(w)+'</p>').join('')||'<p>枚数・同名上限・参照IDに問題はありません。</p>';}
function towerView(){
 const t=state().towers[towerId],f=t.floors[floorIndex];enemyIndex=Math.min(enemyIndex,f.opponents.length-1);const enemy=f.opponents[enemyIndex];const counts={};enemy.deck.forEach(id=>counts[id]=(counts[id]||0)+1);
 $('worldContent').innerHTML='<div class="formgrid"><label>タワー<select id="towerSelect">'+Object.values(state().towers).map(t=>option(t.id,t.name,towerId)).join('')+'</select></label><label>階層<select id="floorSelect">'+t.floors.map((f,i)=>option(String(i),f.number+'階',String(floorIndex))).join('')+'</select></label><label>タワー名<input id="towerName" value="'+esc(t.name)+'"></label></div><h2>クリア報酬</h2><p class="small">初回クリア時の報酬。1〜4階は各対戦相手、5階はタワーマスター戦のシリーズ達成時です。ダイヤは追加分ではなく合計です。</p><div class="formgrid">'+[['coins','コイン'],['diamonds','ダイヤ'],['rubies','ルビー']].map(([k,label])=>'<label>'+label+'<input data-reward="'+k+'" type="number" min="0" step="1" value="'+f.reward[k]+'"></label>').join('')+'</div><h3>報酬フィギュア</h3><div class="figureRows">'+Object.entries(f.reward.figures).map(([id,n])=>'<div class="figureRow">'+rowImage(id)+'<b>'+esc(figureName(id))+'</b><input aria-label="報酬枚数" data-reward-figure="'+esc(id)+'" type="number" min="1" max="999" step="1" value="'+n+'"><button data-reward-remove="'+esc(id)+'">削除</button></div>').join('')+'</div>'+picker('reward')+'<h2>敵のデッキ</h2><div class="formgrid"><label>対戦相手<select id="enemySelect">'+f.opponents.map((e,i)=>option(String(i),e.name,String(enemyIndex))).join('')+'</select></label><label>敵の名前<input id="enemyName" value="'+esc(enemy.name)+'"></label><label>ランク<input id="enemyRank" value="'+esc(enemy.rank)+'"></label></div><p id="deckStatus" role="status"></p><p class="small">45枚 / Seed・Middleは同名3枚まで、MOBは同名1枚まで。段階ごとの枚数は自由です。</p><div class="figureRows">'+Object.entries(counts).map(([id,n])=>'<div class="figureRow">'+rowImage(id)+'<b>'+esc(figureName(id))+'<small>'+esc(records.find(r=>r.id===id)?.soulClass||id)+'</small></b><input aria-label="デッキ枚数" data-deck-count="'+esc(id)+'" type="number" min="0" max="45" step="1" value="'+n+'"><button data-deck-remove="'+esc(id)+'">削除</button></div>').join('')+'</div>'+picker('deck');
 $('towerSelect').onchange=e=>{towerId=e.target.value;floorIndex=0;enemyIndex=0;world();};$('floorSelect').onchange=e=>{floorIndex=Number(e.target.value);enemyIndex=0;world();};$('enemySelect').onchange=e=>{enemyIndex=Number(e.target.value);world();};
 for(const [id,obj,key]of [['towerName',t,'name'],['enemyName',enemy,'name'],['enemyRank',enemy,'rank']])$(id).onchange=e=>{update(()=>obj[key]=e.target.value);};
 dialog.querySelectorAll('[data-reward]').forEach(el=>el.onchange=()=>{if(!el.checkValidity()){el.reportValidity();el.value=f.reward[el.dataset.reward];return;}update(()=>f.reward[el.dataset.reward]=Number(el.value));checks();});
 dialog.querySelectorAll('[data-reward-figure]').forEach(el=>el.onchange=()=>{if(!el.checkValidity()){el.reportValidity();return;}update(()=>f.reward.figures[el.dataset.rewardFigure]=Number(el.value));});
 dialog.querySelectorAll('[data-reward-remove]').forEach(el=>el.onclick=()=>{update(()=>delete f.reward.figures[el.dataset.rewardRemove]);world();});
 bindPicker('reward',r=>{update(()=>f.reward.figures[r.id]=(f.reward.figures[r.id]||0)+1);world();});
 const deckStatus=()=>{const warnings=C.deckWarnings(enemy.deck,records,D);$('deckStatus').className=warnings.length?'warning':'notice';$('deckStatus').textContent=warnings.join(' / ')||'45枚・同名上限 OK';checks();};
 dialog.querySelectorAll('[data-deck-count]').forEach(el=>el.onchange=()=>{if(!el.checkValidity()){el.reportValidity();return;}update(()=>enemy.deck=[...enemy.deck.filter(id=>id!==el.dataset.deckCount),...Array(Number(el.value)).fill(el.dataset.deckCount)]);deckStatus();});
 dialog.querySelectorAll('[data-deck-remove]').forEach(el=>el.onclick=()=>{update(()=>enemy.deck=enemy.deck.filter(id=>id!==el.dataset.deckRemove));world();});
 bindPicker('deck',r=>{const cap=D.rules.copyLimits[r.soulClass];if(enemy.deck.length>=45||enemy.deck.filter(id=>id===r.id).length>=cap){$('deckStatus').textContent='追加できません。45枚・同名上限を超えます。先に枚数を減らしてください';return;}update(()=>enemy.deck.push(r.id));world();});deckStatus();
}
function bannerView(){
 const b=state().banners[bannerId];
 $('worldContent').innerHTML='<div class="worldTabs"><label>ガチャ<select id="bannerSelect">'+Object.values(state().banners).map(b=>option(b.id,b.name,bannerId)).join('')+'</select></label><button id="addBanner">＋ ガチャを作成</button></div><div class="formgrid"><label>ガチャ名<input id="bannerName" value="'+esc(b.name)+'"></label><label>サブタイトル<input id="bannerSubtitle" value="'+esc(b.subtitle)+'"></label><label>登場するタイミング<select id="bannerUnlock">'+option('','最初から登場',b.requiresClear||'')+Object.values(state().towers).map(t=>option(t.id,t.name+' クリア後',b.requiresClear)).join('')+'</select></label></div><p class="notice">選択したタワーの5階をクリアすると登場します。ピックアップ・メイン表示はラインナップ内から選びます。</p><h2>ラインナップ '+b.figureIds.length+'体</h2>'+picker('pool')+'<div class="figureRows">'+b.figureIds.map(id=>'<div class="figureRow poolRow">'+rowImage(id)+'<b>'+esc(figureName(id))+'</b><label><input type="checkbox" data-pickup="'+esc(id)+'" '+(b.pickupIds.includes(id)?'checked':'')+'>ピックアップ</label><label><input type="checkbox" data-featured="'+esc(id)+'" '+(b.featuredIds.includes(id)?'checked':'')+'>メイン表示</label><button data-pool-remove="'+esc(id)+'">削除</button></div>').join('')+'</div>';
 $('bannerSelect').onchange=e=>{bannerId=e.target.value;world();};
 $('addBanner').onclick=()=>{const id='custom-banner-'+Date.now().toString(36);update(()=>state().banners[id]={id,name:'新しいガチャ',subtitle:'',color:'#9754d9',figureIds:[],pickupIds:[],featuredIds:[]});bannerId=id;world();};
 for(const [id,key]of [['bannerName','name'],['bannerSubtitle','subtitle']])$(id).onchange=e=>update(()=>b[key]=e.target.value);
 $('bannerUnlock').onchange=e=>update(()=>{if(e.target.value)b.requiresClear=e.target.value;else delete b.requiresClear;});
 bindPicker('pool',r=>{if(!b.figureIds.includes(r.id)){update(()=>b.figureIds.push(r.id));world();}});
 for(const [attr,key]of [['pickup','pickupIds'],['featured','featuredIds']])dialog.querySelectorAll('[data-'+attr+']').forEach(el=>el.onchange=()=>update(()=>{b[key]=b[key].filter(id=>id!==el.dataset[attr]);if(el.checked)b[key].push(el.dataset[attr]);}));
 dialog.querySelectorAll('[data-pool-remove]').forEach(el=>el.onclick=()=>{update(()=>{for(const key of ['figureIds','pickupIds','featuredIds'])b[key]=b[key].filter(id=>id!==el.dataset.poolRemove);});world();});
}
$('editWorld').onclick=()=>{world();dialog.showModal();};
const report=textReport;textReport=()=>report()+'\n\nタワー・ガチャ変更\n'+(C.equal(state().towers,D.workshop.towers)?'タワー変更なし':JSON.stringify(state().towers,null,2))+'\n'+(C.equal(state().banners,D.workshop.banners)?'ガチャ変更なし':JSON.stringify(state().banners,null,2))+'\n追加・差替画像: '+Object.keys(state().images).join(', ')+'\n全体チェック:\n'+C.workshopWarnings(records,D).join('\n');
window.Workshop.getWorkspace=()=>clone(state());window.Workshop.readImage=readImage;
})();
