'use strict';
let D=window.MPB_DATA;const C=window.MPB_CORE,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=C.clone;let base=new Map(D.records.map(r=>[r.id,r])),tagNames=new Map(D.tags.map(t=>[t.id,t.name])),STORAGE='mpb-figure-workshop:v1',classLabels={seed:'Seed',middle:'Middle',mob:'MOB'},timings={'own-main':'自分メイン','attack-response':'相手攻撃宣言時','skill-response':'相手スキル発動時','defeat-response':'撃破時'};
let records=clone(D.records),orphans=[],view='cards',limit=48,selected=null,history=[],pendingImport=null,unsaved=false,db=null,saveRevision=0,storageError=false,lastFocus=null,refreshTimer=null;
const options=(xs,selected)=>xs.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return '<option value="'+esc(v)+'"'+(String(v)===String(selected)?' selected':'')+'>'+esc(l)+'</option>';}).join('');
const input=(label,path,value,type='text')=>'<label>'+esc(label)+'<input data-path="'+path+'" type="'+type+'" value="'+esc(value)+'"'+(type==='number'?' step="1"':path.endsWith('evolve.target')||(path.includes('.materials.')&&path.endsWith('.id'))?' list="figureIDs"':path.endsWith('.tag')?' list="tagIDs"':'')+'></label>';
const area=(label,path,value)=>'<label class="span2">'+esc(label)+'<textarea data-path="'+path+'" rows="3">'+esc(value)+'</textarea></label>';
const select=(label,path,value,choices)=>'<label>'+esc(label)+'<select data-path="'+path+'">'+options(choices,value)+'</select></label>';
function current(){return records.find(r=>r.id===selected);}
function setpath(o,path,value){const keys=path.split('.');for(const k of keys.slice(0,-1)){if(o[k]===undefined)o[k]={};o=o[k];}o[keys.at(-1)]=value;}
function snapshot(){return JSON.stringify(C.envelope(records,D,orphans));}
function checkpoint(){history.push({records:clone(records),orphans:clone(orphans),source:D,workshop:clone(window.MPB_WORKSHOP_STATE)});if(history.length>60)history.shift();}
function saveMessage(text,error=false){$('saveState').textContent=text;$('saveState').classList.toggle('error',error);}
function openDB(){return new Promise(resolve=>{try{const req=indexedDB.open(STORAGE,1);req.onupgradeneeded=()=>req.result.createObjectStore('draft');req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);req.onblocked=()=>resolve(null);}catch{resolve(null);}});}
function dbGet(key){return new Promise(resolve=>{try{const q=db.transaction('draft').objectStore('draft').get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null);}catch{resolve(null);}});}
function dbPut(value){return new Promise(resolve=>{if(!db)return resolve(false);try{const tx=db.transaction('draft','readwrite'),s=tx.objectStore('draft'),q=s.get('current');q.onsuccess=()=>{if(q.result)s.put(q.result,'previous');s.put(value,'current');};tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false);}catch{resolve(false);}});}
function persist(){
 unsaved=true;const rev=++saveRevision,text=snapshot();let local=false;
 try{const prev=localStorage.getItem(STORAGE);if(prev)localStorage.setItem(STORAGE+':previous',prev);localStorage.setItem(STORAGE,text);local=true;}catch{}
 storageError=!local;saveMessage(local?'自動下書き保存済み · ファイル出力も忘れずに':'保存を確認中…',!local);
 dbPut(text).then(ok=>{if(rev!==saveRevision)return;storageError=!(local||ok);saveMessage(local||ok?'自動下書き保存済み · ファイル出力も忘れずに':'自動保存失敗 · この画面を閉じず「保存・出力」でJSONを救出',storageError);});
 $('changeCount').textContent=C.changes(records,D).length;
 clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(selected)renderWarnings();},180);
}
function mutate(fn,rebuild=false){checkpoint();fn();persist();if(rebuild)renderEditor();}
function filters(){return {q:$('search').value,...Object.fromEntries(['series','soulClass','rarity','attribute','tag'].map(k=>[k,$(k).value]))};}
function visible(){return C.filter(records,filters(),D.groups);}
function card(r){const changed=!C.equal(r,base.get(r.id));return '<article class="card '+(changed?'changed':'')+'"><div class="art"><img loading="lazy" decoding="async" src="'+C.imageFor(r.id,D)+'" alt="'+esc(r.name)+'"><span class="badge">'+esc(r.rarity)+' · '+classLabels[r.soulClass]+(changed?' · 編集済':'')+'</span></div><div class="cardbody"><span class="eyebrow">'+esc(r.series)+' / '+esc(r.id)+'</span><h2>'+esc(r.name)+'</h2><div class="stats"><span>ATK <b>'+esc(r.atk)+'</b></span><span>DEF <b>'+esc(r.def)+'</b></span><span>'+esc(r.attribute)+'</span></div><div class="skillbox"><strong>'+esc(r.skill.name)+'</strong><p>'+esc(r.skill.description)+'</p></div><button data-edit="'+esc(r.id)+'">画像を見て編集</button></div></article>';}
function render(){
 for(const key of ['series','attribute']){const value=$(key).value,values=[...new Set([...D.records.map(r=>r[key]),...records.map(r=>r[key])])];$(key).innerHTML=options([['','すべて'],...values],value);}const list=visible();$('count').textContent=list.length+' / '+records.length+' 体';$('changeCount').textContent=C.changes(records,D).length;
 for(const [id,v] of [['cards','cards'],['groupPanel','groups'],['changes','changes']])$(id).hidden=view!==v;
 for(const [id,v] of [['viewCards','cards'],['viewGroups','groups'],['viewChanges','changes']])$(id).classList.toggle('active',view===v);
 if(view==='cards')$('cards').innerHTML=list.slice(0,limit).map(card).join('')||'<div class="empty">一致するフィギュアはありません</div>';
 if(view==='groups')renderGroups(list);
 if(view==='changes')renderChanges(list);
 $('more').hidden=view!=='cards'||limit>=list.length;$('shown').textContent=view==='cards'?Math.min(limit,list.length)+'体表示中':'';
}
function renderGroups(list){const groups=C.groups(list,$('groupMode').value),dups=groups.filter(g=>g.length>1);$('groupSummary').textContent=groups.length+'種類 / 重複 '+dups.length+'組 / '+dups.reduce((s,g)=>s+g.length,0)+'体';$('groups').innerHTML=groups.map(g=>'<article class="group"><h3>'+g.length+'体 · '+esc(g[0].skill.name)+'</h3><p>'+esc(g[0].skill.description)+'</p><span class="small">'+esc(timings[g[0].skill.timing]||g[0].skill.timing)+' / program '+esc(g[0].skill.program)+'（自由記述は案の内容で集計）</span><details><summary>このグループのフィギュアを見る</summary><div class="memberlist">'+g.map(r=>'<button data-edit="'+esc(r.id)+'">'+esc(r.name)+' · '+esc(r.id)+'</button>').join('')+'</div></details></article>').join('');}
function renderChanges(list){const ids=new Set(list.map(r=>r.id)),changes=C.changes(records,D).filter(c=>ids.has(c.id));$('changes').innerHTML='<p class="notice">'+changes.length+'件の変更を表示。絞り込み条件が適用されます。保存ファイルには絞り込み外を含む全変更を収録します。全件の一括反映はありません。</p>'+changes.map(ch=>'<article class="change"><h3>'+esc(ch.edited.name)+' · '+esc(ch.id)+'</h3><span class="statusBadge">'+esc(ch.implementation.label)+'</span><p class="small">変更項目：'+esc(ch.fields.join(' / '))+'</p>'+ch.fields.map(k=>'<details><summary>'+esc(k)+' の変更前後</summary><div class="diff"><div><b>元データ</b><pre>'+esc(JSON.stringify(ch.base?.[k],null,2))+'</pre></div><div><b>編集案</b><pre>'+esc(JSON.stringify(ch.edited[k],null,2))+'</pre></div></div></details>').join('')+'<button data-edit="'+esc(ch.id)+'">編集を開く</button></article>').join('')+(changes.length?'':'<div class="empty">変更はありません</div>');}
const keyLabels={heal:'ライフ回復',recycle:'撃破済みSeedを戻す',returnSelf:'自身を手札に戻す',cancelAttack:'攻撃終了',replaceSeed:'Seed交代',attacks:'攻撃回数',ramp:'攻撃ごとの上昇',target:'対象',survive:'生存回数',survivePersistent:'生存持続',def:'DEF増減',atk:'ATK増減',skipBattle:'バトル省略',combatDef:'戦闘時DEF',noDamage:'ダメージ無効',duration:'持続',discardCost:'手札コスト',lifeCost:'ライフコスト',draw:'ドロー',lifeDamage:'ライフダメージ',tag:'対象タグ',class:'対象段階',element:'属性専用処理',specified:'指定処理',passive:'常時処理'};
const keyValues={};for(const p of Object.values(D.plans))for(const [k,v]of Object.entries(p)){keyValues[k]||=[];if(!keyValues[k].some(x=>C.equal(x,v)))keyValues[k].push(v);}
function planEditor(r){
 const entries=Object.entries(r.skill.plan);return '<p class="notice">既存プログラムの構造から選択します。効果・対象・条件・コスト・回数の組合せが一致した場合のみ「既存効果に一致」。未一致は実装検証待ちです。使用回数は各個体1ターン1回、対戦中Seed1／Middle2／MOB3回です。常時効果は回数を使いません。</p><label>既存スキルを土台にする<select id="programSelect"><option value="">選択してください（名前・説明もコピー）</option>'+options(Object.entries(D.plans).map(([id])=>[id,'#'+id+' '+(D.records.find(f=>String(f.skill.program)===id)?.skill.name||'未使用プログラム')]),'')+'</select></label><div class="actions"><button id="loadProgram">選んだ既存スキルを読み込む</button></div><div id="planRows">'+entries.map(([k,v])=>'<div class="planrow"><b>'+esc(keyLabels[k]||k)+'<br><small>'+esc(k)+'</small></b><select aria-label="'+esc(k)+' の値" data-plan="'+esc(k)+'">'+options([...keyValues[k]||[],...((keyValues[k]||[]).some(x=>C.equal(x,v))?[]:[v])].map(x=>[JSON.stringify(x),typeof x==='object'?JSON.stringify(x):String(x)]),JSON.stringify(v))+'</select><button data-remove-plan="'+esc(k)+'" aria-label="'+esc(k)+' を除く">×</button></div>').join('')+'</div><div class="tagsedit"><label>効果・条件などを追加<select id="planAddKey">'+options(Object.keys(keyValues).map(k=>[k,(keyLabels[k]||k)+' / '+k]),'')+'</select></label><button id="addPlan">追加</button></div><p class="small">複雑な属性・指定スキルの値は原構造を表示します。任意コードは実行しません。異なるフィギュアへ移すと個別ID・タグ依存の確認が必要です。</p>';
}
function materialEditor(m,path,label){
 const kind=m.any?'any':m.id!==undefined?'id':m.tag!==undefined?'tag':m.attribute!==undefined?'attribute':m.rarity!==undefined?'rarity':'class';
 return '<div class="recipe"><label>'+esc(label)+'の指定<select data-material-path="'+path+'">'+options([['id','フィギュアID'],['tag','タグID'],['attribute','属性'],['rarity','レア度'],['class','段階'],['any','OR条件（いずれか）']],kind)+'</select></label>'+(kind==='any'?m.any.map((x,i)=>materialEditor(x,path+'.any.'+i,'候補'+(i+1))).join(''):input(label+' ('+kind+')',path+'.'+kind,m[kind]||''))+'</div>';
}
function recipesEditor(r){return '<label><input type="checkbox" data-path="summon.normal" '+(r.summon.normal?'checked':'')+'>手札から通常召喚できる案</label>'+r.summon.recipes.map((rec,i)=>'<div class="recipe"><div class="formgrid">'+input('レシピ名','summon.recipes.'+i+'.label',rec.label||'')+select('素材の段階','summon.recipes.'+i+'.fromClass',rec.fromClass??'',[['','特殊・未指定'],...C.classes.map(k=>[k,classLabels[k]])])+input('レシピID','summon.recipes.'+i+'.id',rec.id||'')+'<label><input type="checkbox" data-path="summon.recipes.'+i+'.special" '+(rec.special?'checked':'')+'>特殊融合</label></div>'+rec.materials.map((m,j)=>materialEditor(m,'summon.recipes.'+i+'.materials.'+j,'素材'+(j+1))).join('')+'<details><summary>原レシピの詳細（未編集項目も保持）</summary><pre>'+esc(JSON.stringify(rec,null,2))+'</pre></details><button data-remove-recipe="'+i+'" class="danger">このレシピ案を除く</button></div>').join('')+'<button id="addRecipe">＋ 素材2枠のレシピを追加</button><h4>条件進化</h4><p class="small">既存のpassiveを保持します。ここでの進化設定も案として保存し、現行特殊例外を勝手に削除しません。</p>'+(r.summon.passive.evolve?'<div class="formgrid">'+input('進化先フィギュアID','summon.passive.evolve.target',r.summon.passive.evolve.target)+input('手札コスト','summon.passive.evolve.cost',r.summon.passive.evolve.cost,'number')+input('必要タグID（空欄可）','summon.passive.evolve.tag',r.summon.passive.evolve.tag||'')+'<label><input type="checkbox" data-path="summon.passive.evolve.field" '+(r.summon.passive.evolve.field?'checked':'')+'>場の素材も使う</label></div><button id="removeEvolution">条件進化案を除く</button>':'<button id="addEvolution">＋ 条件進化の案を追加</button>')+area('召喚条件の補足・期待する動作','summon.notes',r.summon.notes)+'<details><summary>その他の元passive情報</summary><pre>'+esc(JSON.stringify(r.summon.passive,null,2))+'</pre></details>';}
function renderEditor(){
 const r=current();if(!r)return;const st=C.status(r,D);$('editorTitle').textContent=r.name+' / '+r.id;$('editorThumb').src=C.imageFor(r.id,D);
 $('editorBody').innerHTML='<div class="editorInner"><div class="hero"><img src="'+C.imageFor(r.id,D)+'" alt="'+esc(r.name)+'"><div><h2>'+esc(r.name)+'</h2><p>固定ID '+esc(r.id)+' / UID '+esc(r.uid)+'</p><span id="skillStatus" class="statusBadge '+(st.code.includes('required')?'required':'')+'">'+esc(st.label)+'</span></div></div><p class="small">変更は入力ごとに下書き保存。本体・既存ゲームセーブは変更しません。追加画像も下書きに保存します。</p><h3 class="sectiontitle">01 / 基本データ</h3><div class="formgrid">'+input('名称','name',r.name)+input('シリーズ（表示上の分類）','series',r.series)+select('段階','soulClass',r.soulClass,C.classes.map(k=>[k,classLabels[k]]))+select('レア度','rarity',r.rarity,['R','SR','SSR','UR','MOB'])+input('ATK','atk',r.atk,'number')+input('DEF','def',r.def,'number')+input('属性','attribute',r.attribute)+input('攻撃種別','attackType',r.attackType)+input('役割','role',r.role)+'</div><h4>所属タグ</h4><p class="small">素材の条件タグは所属ではありません。独自タグIDも保持し、未登録タグとして警告します。</p><div class="chips">'+r.tags.map((t,i)=>'<button class="tagremove" data-remove-tag="'+i+'">'+esc(tagNames.get(t)||t)+' ('+esc(t)+') ×</button>').join('')+'</div><div class="tagsedit"><label>タグ追加<select id="tagAdd">'+options(D.tags.map(t=>[t.id,t.name+' / '+t.id]),'')+'</select></label><button id="addTag">追加</button></div><div class="tagsedit"><label>新規タグID<input id="customTag" placeholder="custom-example"></label><button id="addCustomTag">追加</button></div><h3 class="sectiontitle">02 / スキル</h3><div class="formgrid">'+select('編集モード','skill.mode',r.skill.mode,[['existing','既存エンジンの効果を組み立て'],['custom','独自スキル・自由記述']])+input('スキル名','skill.name',r.skill.name)+area('効果の説明文（プログラムとは別項目）','skill.description',r.skill.description)+'</div>'+(r.skill.mode==='custom'?'<p class="warning">追加実装が必要。この自由記述は文字データです。ゲームで実行済み・実装済みにはなりません。元の既存プランは保持します。</p><div class="formgrid">'+['target','timing','condition','cost','uses','example'].map((k,i)=>area(['対象','発動時点','発動条件','コスト','回数・上限','期待する具体例'][i],'skill.custom.'+k,r.skill.custom[k]||'')).join('')+'</div>':'<div class="formgrid">'+select('発動時点','skill.timing',r.skill.timing,Object.entries(timings))+'</div>'+planEditor(r))+'<h4>他のフィギュアからスキルだけコピー</h4><label>コピー元を名前・IDで絞り込む<input id="copySearch" type="search" placeholder="例：ミータ / 02"></label><label>コピー元<select id="copyFrom">'+options(records.filter(f=>f.id!==r.id).map(f=>[f.id,f.name+' / '+f.id+' / '+f.skill.name]),'')+'</select></label><p class="small">名前・説明・効果プラン・独自案・発動時点をコピー。コピー後は元に戻す操作が可能です。</p><button id="copySkill">選んだ1体からコピー</button><h3 class="sectiontitle">03 / 召喚方法</h3>'+recipesEditor(r)+'<h3 class="sectiontitle">04 / 変更比較と確認</h3><div id="warnings" class="warnlist"></div><details><summary>このフィギュアの変更前後</summary><div id="singleDiff"></div></details><div class="actions stickyedit"><button id="undo" '+(!history.length?'disabled':'')+'>1操作戻す</button><button id="resetOne" class="danger">元データへ</button><button id="done" class="primary">一覧に戻る</button></div></div>';
 bindEditor();renderWarnings();
}
function renderWarnings(){const r=current();if(!r)return;const st=C.status(r,D);$('skillStatus').textContent=st.label;$('skillStatus').classList.toggle('required',st.code.includes('required'));const warns=C.validate(records,D).filter(w=>w.id===r.id);$('warnings').innerHTML=warns.map(w=>'<p class="warning">'+esc(w.message)+'</p>').join('')||'<p class="notice">構造チェックで警告はありません。本体反映・実対戦検証は別途必要です。</p>';const b=base.get(r.id);$('singleDiff').innerHTML='<div class="diff"><div><b>元データ</b><pre>'+esc(JSON.stringify(b,null,2))+'</pre></div><div><b>編集中</b><pre>'+esc(JSON.stringify(r,null,2))+'</pre></div></div>';if($('undo'))$('undo').disabled=!history.length;}
function bindEditor(){
 const body=$('editorBody');body.querySelectorAll('[data-path]').forEach(el=>{let focused=false;el.addEventListener('focus',()=>{focused=false;});const handler=()=>{if(!focused){checkpoint();focused=true;}const p=el.dataset.path,v=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;setpath(current(),p,v);persist();if(p==='skill.mode'){renderEditor();}};el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',handler);});
 body.querySelectorAll('[data-plan]').forEach(el=>el.onchange=()=>mutate(()=>{current().skill.plan[el.dataset.plan]=JSON.parse(el.value);current().skill.program=null;},false));
 body.querySelectorAll('[data-remove-plan]').forEach(el=>el.onclick=()=>mutate(()=>{delete current().skill.plan[el.dataset.removePlan];current().skill.program=null;},true));
 body.querySelectorAll('[data-remove-tag]').forEach(el=>el.onclick=()=>mutate(()=>current().tags.splice(Number(el.dataset.removeTag),1),true));
 body.querySelectorAll('[data-material-path]').forEach(el=>el.onchange=()=>mutate(()=>setpath(current(),el.dataset.materialPath,el.value==='any'?{any:[{tag:''},{tag:''}]}:{[el.value]:''}),true));
 body.querySelectorAll('[data-remove-recipe]').forEach(el=>el.onclick=()=>mutate(()=>current().summon.recipes.splice(Number(el.dataset.removeRecipe),1),true));
 $('addTag').onclick=()=>mutate(()=>{if(!current().tags.includes($('tagAdd').value))current().tags.push($('tagAdd').value);},true);
 $('addCustomTag').onclick=()=>{const t=$('customTag').value.trim();if(t)mutate(()=>{if(!current().tags.includes(t))current().tags.push(t);},true);};
 if($('addPlan'))$('addPlan').onclick=()=>mutate(()=>{const k=$('planAddKey').value;current().skill.plan[k]=clone(keyValues[k][0]);current().skill.program=null;},true);
 if($('loadProgram'))$('loadProgram').onclick=()=>{const id=$('programSelect').value;if(id==='')return;const source=D.records.find(f=>String(f.skill.program)===id);mutate(()=>{if(source)current().skill=clone(source.skill);else {current().skill.plan=clone(D.plans[id]);current().skill.program=Number(id);}},true);};
 $('copySearch').oninput=()=>{const q=$('copySearch').value.toLowerCase();$('copyFrom').innerHTML=options(records.filter(f=>f.id!==selected&&(f.name+' '+f.id+' '+f.skill.name).toLowerCase().includes(q)).map(f=>[f.id,f.name+' / '+f.id+' / '+f.skill.name]),'');$('copySkill').disabled=!$('copyFrom').options.length;};
 $('copySkill').onclick=()=>{const source=records.find(f=>f.id===$('copyFrom').value);if(source)mutate(()=>current().skill=clone(source.skill),true);};
 $('addRecipe').onclick=()=>mutate(()=>current().summon.recipes.push({id:'draft-'+current().id+'-'+Date.now(),target:current().id,fromClass:current().soulClass==='mob'?'middle':'seed',materials:[{id:''},{id:''}],label:'新しい融合案',special:false}),true);
 if($('addEvolution'))$('addEvolution').onclick=()=>mutate(()=>{current().summon.passive.evolve={target:'',cost:1,tag:'',field:false};},true);
 if($('removeEvolution'))$('removeEvolution').onclick=()=>mutate(()=>{delete current().summon.passive.evolve;},true);
 $('undo').onclick=()=>{if(!history.length)return;const old=history.pop();if(old.source&&old.source!==D){refreshSource(old.source);void saveSource();}records=old.records;orphans=old.orphans;C.installWorkspace(old.workshop);persist();renderEditor();};
 $('resetOne').disabled=!base.has(selected);$('resetOne').onclick=()=>{if(!base.has(selected))return;if(confirm('この1体の編集を元データに戻します。1操作戻すで取り消せます。'))mutate(()=>{records[records.findIndex(r=>r.id===selected)]=clone(base.get(selected));delete window.MPB_WORKSHOP_STATE.images[selected];},true);};
 $('done').onclick=closeEditor;
}
function openEditor(id){selected=id;lastFocus=document.activeElement;renderEditor();$('editor').showModal();document.body.classList.add('modal');$('editor').scrollTop=0;$('closeEditor').focus();}
function closeEditor(){const id=selected;$('editor').close();selected=null;document.body.classList.remove('modal');render();const button=[...$('cards').querySelectorAll('[data-edit]')].find(b=>b.dataset.edit===id);(button||$('search')).focus({preventScroll:true});}
function download(name,text,type){try{const blob=new Blob([text],{type:type||'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);saveMessage('出力を開始しました · ダウンロード先を確認してください',storageError);}catch(e){saveMessage('出力失敗 · 救出テキストからJSONをコピーしてください',true);$('rescueText').value=snapshot();}}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);}
function textReport(){const changes=C.changes(records,D),warnings=C.validate(records,D);return 'MOB PIECE BATTLE 編集変更表\n本体へ未反映／未実行\nSchema: '+D.schema+'\nSource: '+D.sourceVersion+'\nSHA256: '+D.sourceHash+'\n変更: '+changes.length+'体\n\n'+changes.map(c=>'■ '+c.id+' '+c.edited.name+'\n'+c.implementation.label+'\n'+c.fields.map(k=>'['+k+']\n変更前: '+JSON.stringify(c.base?.[k],null,2)+'\n変更後: '+JSON.stringify(c.edited[k],null,2)).join('\n')+'\n警告:\n'+warnings.filter(w=>w.id===c.id).map(w=>'・'+w.message).join('\n')).join('\n\n')+'\n\n未解決の読込データ:\n'+JSON.stringify(orphans,null,2);}
function stageImport(text){try{pendingImport=C.parseImport(text,D);const p=pendingImport;$('importInfo').textContent=(p.conflict?'⚠ 別sourceVersion / sourceHashです。衝突確認が必要。':'同一元データです。')+' 読込元 '+String(p.value.sourceHash).slice(0,16)+' / 現在 '+D.sourceHash.slice(0,16)+'。 '+p.value.records.length+'体。欠落ID '+p.missing.length+'（現在値保持）、未知ID '+p.unknown.length+'（未解決データとして保持）。現在の編集を読み込み値で置換します。';$('applyImport').hidden=false;$('cancelImport').hidden=false;}catch(e){pendingImport=null;$('importInfo').textContent='読み込み中止: '+e.message;$('applyImport').hidden=true;$('cancelImport').hidden=true;}}
function applyImport(){if(!pendingImport)return;checkpoint();const p=pendingImport;records=C.importRecords(p,records);orphans=[...(p.value.unresolvedImports||[]),...p.unknown,...(p.conflict?[{reason:'source-version-conflict',sourceVersion:p.value.sourceVersion,sourceHash:p.value.sourceHash,originalChanges:p.value.changes||[]}]:[])];pendingImport=null;persist();$('importInfo').textContent='読み込み完了。元のsnapshotは変更していません。';$('applyImport').hidden=true;$('cancelImport').hidden=true;render();}
for(const k of ['rarity','attribute'])$(k).innerHTML+=options([...new Set(D.records.map(r=>r[k]))],'');$('series').innerHTML+=options(D.groups,'');$('tag').innerHTML+=options(D.tags.map(t=>[t.id,t.name+' / '+t.id]),'');$('version').textContent='SNAPSHOT '+D.sourceHash.slice(0,12);$('figureIDs').innerHTML=options(D.records.map(r=>[r.id,r.name]),'');$('tagIDs').innerHTML=options(D.tags.map(t=>[t.id,t.name]),'');$('archives').textContent='除外: '+D.archived.map(f=>f.id+' '+f.name).join(' / ');
let composing=false;$('search').addEventListener('compositionstart',()=>composing=true);$('search').addEventListener('compositionend',()=>{composing=false;limit=48;render();});$('search').addEventListener('input',()=>{if(!composing){limit=48;render();}});
for(const k of ['series','soulClass','rarity','attribute','tag'])$(k).onchange=()=>{limit=48;render();};$('clearFilters').onclick=()=>{for(const k of ['search','series','soulClass','rarity','attribute','tag'])$(k).value='';limit=48;render();};
for(const [id,v]of [['viewCards','cards'],['viewGroups','groups'],['viewChanges','changes'],['openChanges','changes']])$(id).onclick=()=>{view=v;render();if(id==='openChanges')window.scrollTo({top:170,behavior:'auto'});};
$('more').onclick=()=>{limit+=48;render();};$('groupMode').onchange=render;document.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(b.dataset.edit);});
$('closeEditor').onclick=closeEditor;$('editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});
$('openIO').onclick=()=>{$('io').showModal();document.body.classList.add('modal');};$('closeIO').onclick=()=>{$('io').close();document.body.classList.remove('modal');};$('io').addEventListener('close',()=>document.body.classList.remove('modal'));
$('draft').onclick=()=>download('MOB-PIECE-draft-'+stamp()+'.json',snapshot());
$('patch').onclick=()=>{const e=C.envelope(records,D,orphans);delete e.records;e.kind='mpb-editor-patch';e.warnings=C.validate(records,D).filter(w=>e.changes.some(c=>c.id===w.id));download('MOB-PIECE-patch-'+stamp()+'.json',JSON.stringify(e,null,2));};
$('txt').onclick=()=>download('MOB-PIECE-changes-'+stamp()+'.txt','\ufeff'+textReport(),'text/plain;charset=utf-8');$('rescue').onclick=()=>{$('rescueText').value=snapshot();$('rescueText').select();};
$('import').onchange=async()=>{const f=$('import').files[0];if(!f)return;try{if(f.size>30*1024*1024)throw Error('30MBを超えるファイルは読み込めません');stageImport(await f.text());}catch(e){$('importInfo').textContent='読込失敗: '+e.message;}finally{$('import').value='';}};
$('applyImport').onclick=applyImport;$('cancelImport').onclick=()=>{pendingImport=null;$('applyImport').hidden=true;$('cancelImport').hidden=true;$('importInfo').textContent='読み込みを中止。現在の編集は保持しました。';};
$('backup').onclick=async()=>{let t;try{t=localStorage.getItem(STORAGE+':previous');}catch{}t||=await dbGet('previous');if(t)stageImport(t);else $('importInfo').textContent='前回のバックアップはありません';};
window.addEventListener('beforeunload',e=>{if(unsaved){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===STORAGE&&e.newValue){saveMessage('別タブの編集を検出。自動統合しません。先にJSONを保存してください',true);}});
// Exposed pure state access for local verification; never executes game code.
window.Workshop={getRecords:()=>clone(records),getOrphans:()=>clone(orphans),snapshot,stageImport,applyImport,openEditor,closeEditor,status:()=>({storageError,unsaved}),textReport};
// Imported sources are persisted separately; draft storage keys remain unchanged.
function refreshSource(next){D=next;for(const k of Object.keys(keyValues))delete keyValues[k];for(const p of Object.values(D.plans))for(const [k,v]of Object.entries(p)){keyValues[k]||=[];if(!keyValues[k].some(x=>C.equal(x,v)))keyValues[k].push(v);}base=new Map(D.records.map(r=>[r.id,r]));tagNames=new Map(D.tags.map(t=>[t.id,t.name]));for(const k of ['rarity','attribute'])$(k).innerHTML=options([['','すべて'],...[...new Set(D.records.map(r=>r[k]))]],'');$('tag').innerHTML=options([['','すべて'],...D.tags.map(t=>[t.id,t.name+' / '+t.id])],'');$('figureIDs').innerHTML=options(D.records.map(r=>[r.id,r.name]),'');$('tagIDs').innerHTML=options(D.tags.map(t=>[t.id,t.name]),'');$('version').textContent='SNAPSHOT '+D.sourceHash.slice(0,12);$('archives').textContent='除外: '+D.archived.map(f=>f.id+' '+f.name).join(' / ');document.querySelector('h1 span').textContent=D.records.length;}
function saveSource(){return new Promise(resolve=>{try{const tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(JSON.stringify({schema:'mpb-editor-source/1',kind:'mpb-editor-source',data:D}),'source');tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);}catch{resolve(false);}});}
function syncPreview(p){const merged=C.mergeImport(p,records);$('importInfo').textContent='変更対象 '+p.patches.length+'体。競合 '+merged.conflicts.length+'項目、未登録 '+merged.unknown.length+'件。安全に一致した変更だけを反映します。競合は現在値を保持し、下書きJSONの未解決情報に元の案を残します。'+(p.conflict?' 元データの版は異なります。':'')+merged.conflicts.map(x=>'\n'+x.id+' / '+(x.path||[]).join('.')+'：現在 '+JSON.stringify(x.current)+' / 読込案 '+JSON.stringify(x.proposed)).join('');return merged;}
stageImport=function(text){try{if(JSON.parse(text).kind==='mpb-editor-source'){const next=C.parseSource(text),p=C.parseImport(snapshot(),next);pendingImport={source:next,parsed:p};const merged=C.mergeImport(p,next.records,next.workshop);$('importInfo').textContent='本体スナップショット '+next.records.length+'体へ更新。手元の編集を変更項目だけ再適用します。競合 '+merged.conflicts.length+'項目は最新本体値を保持し、編集案を未解決情報へ残します。';}else{pendingImport=C.parseImport(text,D);syncPreview(pendingImport);}$('applyImport').hidden=false;$('cancelImport').hidden=false;}catch(e){pendingImport=null;$('importInfo').textContent='読み込み中止: '+e.message;$('applyImport').hidden=true;$('cancelImport').hidden=true;}};
applyImport=function(){if(!pendingImport)return;checkpoint();const input=pendingImport,p=input.parsed||input,merged=C.mergeImport(p,input.source?input.source.records:records,input.source?input.source.workshop:window.MPB_WORKSHOP_STATE);if(input.source)refreshSource(input.source);records=merged.records;C.installWorkspace(merged.workshop);orphans=[...orphans,...(p.value.unresolvedImports||[]),...merged.unknown,...merged.conflicts];pendingImport=null;persist();if(input.source)void saveSource().then(ok=>{if(!ok)saveMessage('本体データの保存失敗。スナップショットと下書きJSONを保存してください',true);});$('importInfo').textContent='安全な変更を読み込みました。競合 '+merged.conflicts.length+'項目は現在値を保持し、下書きへ保管しました。';$('applyImport').hidden=true;$('cancelImport').hidden=true;render();};
$('applyImport').onclick=()=>applyImport();
$('sourceExport').onclick=()=>download('MOB-PIECE-current-source-'+stamp()+'.json',JSON.stringify({schema:'mpb-editor-source/1',kind:'mpb-editor-source',data:D}));
window.Workshop.stageImport=text=>stageImport(text);window.Workshop.applyImport=()=>applyImport();window.Workshop.getSource=()=>clone(D);

document.querySelector('main').inert=true;$('openIO').disabled=true;$('openChanges').disabled=true;render();saveMessage('保存済み下書きを確認しています…');
(async()=>{try{let local;try{local=localStorage.getItem(STORAGE);}catch{}db=await Promise.race([openDB(),new Promise(r=>setTimeout(()=>r(null),1800))]);const storedSource=db?await dbGet('source'):null;if(storedSource){const newer=C.parseSource(storedSource);if(newer.extractedAt>D.extractedAt){refreshSource(newer);C.installWorkspace(newer.workshop);records=clone(D.records);}}const indexed=db?await dbGet('current'):null;const candidates=[local,indexed].filter(Boolean).map(t=>{try{return {text:t,p:C.parseImport(t,D)};}catch{return null;}}).filter(Boolean).sort((a,b)=>String(b.p.value.exportedAt).localeCompare(String(a.p.value.exportedAt)));if(candidates.length){const {p,text}=candidates[0];if(p.conflict){orphans.push({reason:'unapplied-source-conflict',payload:p.value});stageImport(text);saveMessage('別版の下書きがあります。「保存・出力」で競合を確認',true);}else if(!unsaved){const restored=C.mergeImport(p,records);records=restored.records;C.installWorkspace(restored.workshop);orphans=[...(p.value.unresolvedImports||[]),...restored.conflicts,...restored.unknown];render();saveMessage('自動下書きを復元しました');}}else if(local||indexed)saveMessage('保存データを復元できません。バックアップ／JSONを確認してください',true);else saveMessage('元データを読み込みました');}catch(e){saveMessage('下書き復元を確認できません。JSONまたはバックアップを確認してください',true);}finally{document.querySelector('main').inert=false;$('openIO').disabled=false;$('openChanges').disabled=false;}})();
