/* Stable-ID, field-level three-way merge. Incoming snapshots never overwrite edits. */
(function(root){
const C=root.MPB_CORE,copy=x=>x===undefined?undefined:C.clone(x),eq=C.equal;
function paths(a,b,p=[]){if(eq(a,b))return [];if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b))return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>paths(a[k],b[k],[...p,k]));return [{path:p,base:copy(a),value:copy(b)}];}
const get=(o,p)=>p.reduce((v,k)=>v?.[k],o);function set(o,p,v){for(const k of p.slice(0,-1)){if(!o[k]||typeof o[k]!=='object')o[k]={};o=o[k];}if(v===undefined)delete o[p.at(-1)];else o[p.at(-1)]=copy(v);}
const originalParse=C.parseImport;
C.parseImport=function(text,data){const raw=JSON.parse(text);if(raw.schema!==data.schema)throw Error('未対応schema');const patch=Array.isArray(raw.changes)?raw.changes:null;const candidate={...raw,records:raw.records||patch?.map(c=>c.edited)};const parsed=originalParse(JSON.stringify(candidate),data);if(patch){const seen=new Set();for(const c of patch){if(!c||(!c.base&&!(c.base===null&&c.edited?.editorAdded))||!c.edited||(c.base&&c.id!==c.base.id)||c.id!==c.edited.id||seen.has(c.id)||!Array.isArray(c.fields))throw Error('差分のbase/ID/fieldsが不正');seen.add(c.id);if(c.base&&c.base.uid!==c.edited.uid)throw Error('固定UIDは変更できません');originalParse(JSON.stringify({...candidate,records:[c.edited]}),data);}parsed.patches=patch;}else if(!parsed.conflict)parsed.patches=C.changes(parsed.value.records,data);else{parsed.patches=[];parsed.unbased=true;}return parsed;};
C.mergeImport=function(parsed,current){const records=copy(current),by=new Map(records.map(r=>[r.id,r])),conflicts=[],unknown=[];for(const c of parsed.patches||[]){const target=by.get(c.id);if(!target){unknown.push({reason:'unknown-id',change:copy(c)});continue;}for(const field of c.fields){if(['id','uid'].includes(field)||!Object.hasOwn(c.edited,field))continue;for(const d of paths(c.base[field],c.edited[field],[field])){const value=get(target,d.path);if(eq(value,d.value))continue;if(eq(value,d.base))set(target,d.path,d.value);else conflicts.push({reason:'field-conflict',id:c.id,path:d.path,base:d.base,current:copy(value),proposed:d.value});}}}if(parsed.unbased)unknown.push({reason:'foreign-snapshot-without-base',payload:copy(parsed.value)});return {records,conflicts,unknown};};
C.importRecords=(parsed,current)=>C.mergeImport(parsed,current).records;
C.parseSource=function(text){const o=JSON.parse(text,(k,v)=>{if(['__proto__','prototype','constructor'].includes(k))throw Error('不正なキー');return v;});if(o.schema!=='mpb-editor-source/1'||o.kind!=='mpb-editor-source')throw Error('本体スナップショット形式ではありません');const d=o.data;if(!d||d.schema!=='mpb-editor/1'||!Array.isArray(d.tags)||!d.plans||!d.images||!d.rules||!Array.isArray(d.groups)||!Array.isArray(d.archived)||typeof d.sourceHash!=='string')throw Error('本体データの構造が不正');originalParse(JSON.stringify({schema:d.schema,sourceHash:d.sourceHash,sourceVersion:d.sourceVersion,records:d.records}),d);for(const src of Object.values(d.images))if(typeof src!=='string'||(!/^data:image\/(webp|png|jpeg);base64,/.test(src)&&!/^assets\/[a-zA-Z0-9_.-]+$/.test(src)))throw Error('画像は同梱assetsまたは画像データに限ります');return d;};
const originalStatus=C.status;C.status=function(r,d){if(r.skill.mode==='custom')return originalStatus(r,d);const source=d.records.find(x=>x.id===r.id);if(source&&eq(source.skill,r.skill))return {code:'source-unchanged',label:'現行本体の実装'};return originalStatus(r,d);};
root.MPB_CORE=C;
})(typeof window==='undefined'?globalThis:window);
