import {QUALIFIER_POINTS,QUALIFIER_REWARDS,RANK_UP_REWARDS,MASTER_BONUS,MASTER_PRIZE,isQualifierWeek,isRankUpWeek,labelDate} from '../data/competition.js';
import {isPlayerMaster,currentQualifier,currentRankUp,leagueStandings,currentLeagueMatches,leagueFinalTable,getLeagueFinal,getMasterChallenge} from '../game/competition.js';

const money=n=>Number(n||0).toLocaleString('ja-JP');
const reward=(r)=>r?`${money(r.coins)} COIN / ${money(r.diamonds)} DIAMOND`:'報酬設定待ち';
const battleBtn=(type,label='BATTLE START')=>`<button class="competition-battle-start" data-comp-battle="${type}"><small>2本先取</small><b>${label}</b><span>→</span></button>`;

function scheduleCard(c){const d=c.profile.competition.date;return `<section class="season-card"><div><small>SEASON CALENDAR</small><b>${labelDate(d)}</b></div><button data-comp="next-week">NEXT WEEK →</button></section>`;}
function ranking(c,full=false){const rows=leagueStandings(c.profile,{full}).slice(0,12);return `<div class="league-ranking"><div class="rank-head"><b>MOB LEAGUE POINT</b><span>TOP 8 → 12月本戦</span></div>${rows.map(r=>`<div class="rank-row ${r.isPlayer?'player-row':''} ${r.position<=8?'qualified':''}"><strong>${r.position}</strong><span>${r.name}<small>${r.isPlayer?'YOU':r.rank}</small></span><b>${r.points} PT</b></div>`).join('')}</div>`;}
function qualifier(c){const p=c.profile,d=p.competition.date;if(!isQualifierWeek(d.month,d.week)||d.month>11)return '';
  if(isPlayerMaster(p))return `<section class="event-card master-card"><small>MOB MASTER EXEMPTION</small><h2>予選免除</h2><p>王者はMOBリーグ予選・本戦を免除。第1週・第3週に自動で王者特典を受け取ります。</p><div class="reward-line">${money(MASTER_BONUS.coins)} COIN <i>+</i> ${MASTER_BONUS.diamonds} DIAMOND</div></section>`;
  const q=currentQualifier(p);const done=q?.results.length||0;const point=QUALIFIER_POINTS[p.rank],rw=QUALIFIER_REWARDS[p.rank];const next=q?.opponents?.[done];return `<section class="event-card qualifier-card"><small>MONTH ${d.month} / WEEK ${d.week}</small><h2>MOB LEAGUE QUALIFIER</h2><div class="event-meta"><span>RANK ${p.rank}</span><span>${done} / 2 MATCH</span><span>${p.competition.leaguePoints} PT</span></div><p>同ランクとの予選を2試合。勝敗に応じて年間リーグポイントが増減します。</p><div class="rule-strip"><span>WIN <b>+${point.win} PT</b></span><span>LOSE <b>${point.loss} PT</b></span><span>WIN REWARD <b>${money(rw.coins)} / 💎${rw.diamonds}</b></span></div>${done<2?`<div class="opponent-box"><small>NEXT OPPONENT</small><b>${next?.name||'CPU'} · RANK ${p.rank}</b><span>1試合＝2本先取</span></div>${battleBtn('qualifier','QUALIFIER START')}`:`<div class="event-complete">✓ 今週の予選2試合終了</div>`}</section>`;}
function rankUp(c){const p=c.profile,d=p.competition.date;if(!isRankUpWeek(d.month,d.week)||isPlayerMaster(p))return '';const t=currentRankUp(p);const rw=RANK_UP_REWARDS[p.rank];if(!t)return `<section class="event-card cup-card"><small>APR / JUL / NOV · WEEK 2</small><h2>RANK UP TOURNAMENT</h2><p>同ランク8人によるトーナメント。参加は自由。優勝すると${p.rank==='SS'?'SSのまま優勝報酬を獲得':'次のランクへ昇格'}します。</p><div class="prize-grid"><span>RUNNER-UP<b>${reward(rw?.runnerUp)}</b></span><span>WINNER<b>${reward(rw?.winner)}</b></span></div><div class="join-actions"><button data-comp="cup-skip">今回は出ない</button><button data-comp="cup-join">参加する</button></div></section>`;
  if(t.status==='skipped')return `<section class="event-card cup-card"><h2>RANK UP TOURNAMENT</h2><div class="event-complete">今回は不参加です</div></section>`;
  const names=['QUARTER FINAL','SEMI FINAL','FINAL'];return `<section class="event-card cup-card"><small>8 PLAYER TOURNAMENT</small><h2>${names[t.round]||'RESULT'}</h2><div class="tournament-road">${names.map((n,i)=>`<span class="${i<t.round?'done':i===t.round&&t.status==='active'?'current':''}">${n}<b>${t.results[i]?t.results[i].won?'WIN':'LOSE':i===t.round&&t.status==='active'?t.opponents[i]:'—'}</b></span>`).join('')}</div>${t.status==='active'?`<div class="opponent-box"><small>NEXT OPPONENT</small><b>${t.opponents[t.round]}</b><span>1試合＝2本先取</span></div>${battleBtn('cup','TOURNAMENT START')}`:`<div class="event-complete">${t.results.at(-1)?.won?'🏆 TOURNAMENT WINNER':'TOURNAMENT FINISHED'}${t.rankAfter!==t.rankAtEntry?`<strong>RANK UP ${t.rankAtEntry} → ${t.rankAfter}</strong>`:''}${t.reward?`<small>${reward(t.reward)}</small>`:''}</div>`}</section>`;}
function leagueFinal(c){const p=c.profile,d=p.competition.date;if(d.month!==12||d.week>2)return '';const lf=getLeagueFinal(p);const matches=currentLeagueMatches(p);const playerIn=lf.finalists.some(x=>x.id==='PLAYER');const table=leagueFinalTable(p);return `<section class="event-card final-card"><small>DECEMBER · MOB LEAGUE</small><h2>TOP 8 ROUND ROBIN</h2><p>1月〜11月のリーグポイント上位8名による総当たり戦。12月第1週は4試合、第2週は3試合。</p>${!playerIn?'<div class="event-complete">PLAYERは今年のTOP 8圏外です。MOBリーグはCPUで進行します。</div>':`<div class="week-match-list">${matches.map((m,i)=>`<div><span>MATCH ${i+1}</span><b>${m.name}</b><em>${m.result?m.result.won?'WIN':'LOSE':'NEXT'}</em></div>`).join('')}</div>${matches.some(x=>!x.result)?battleBtn('league','LEAGUE MATCH START'):'<div class="event-complete">✓ 今週の本戦を完了</div>'}`}<div class="final-table">${table.map(r=>`<div class="${r.id==='PLAYER'?'player-row':''}"><strong>${r.position}</strong><span>${r.name}</span><b>${r.wins}W-${r.losses}L</b></div>`).join('')}</div></section>`;}
function masterChallenge(c){const p=c.profile,d=p.competition.date;if(d.year<2||d.month!==12||d.week!==3)return '';const mc=getMasterChallenge(p);if(!mc)return `<section class="event-card master-card"><small>DECEMBER · WEEK 3</small><h2>MOB MASTER MATCH</h2><p>今年の決定戦はありません。</p></section>`;const involved=mc.defender==='PLAYER'||mc.challenger==='PLAYER';return `<section class="event-card master-card"><small>BEST OF 5 MATCHES · FIRST TO 3</small><h2>MOB MASTER MATCH</h2><div class="master-versus"><span>${mc.defender==='PLAYER'?'PLAYER':mc.defender}<small>MOB MASTER</small></span><b>${mc.defenderWins} - ${mc.challengerWins}</b><span>${mc.challenger==='PLAYER'?'PLAYER':mc.challenger}<small>LEAGUE CHAMPION</small></span></div><p>1試合は2本先取。最大5試合を行い、先に3試合を取った側がMOB MASTERになります。</p>${mc.winner?`<div class="event-complete"><strong>WINNER · ${mc.winner==='PLAYER'?'PLAYER':mc.winner}</strong><small>${mc.winner==='PLAYER'?reward(MASTER_PRIZE):'MOB MASTER決定'}</small></div>`:involved?battleBtn('master','MASTER MATCH START'):'<div class="event-complete">CPU同士の決定戦は自動進行します。</div>'}</section>`;}
function yearlyRules(){const prizeRows=Object.entries(RANK_UP_REWARDS).map(([rank,r])=>`<div class="rank-prize-row"><strong>${rank}</strong><span>${reward(r.runnerUp)}</span><b>${reward(r.winner)}</b></div>`).join('');return `<details class="competition-rules"><summary>年間大会ルールを見る</summary><div><b>MOB LEAGUE</b><p>1〜11月の第1・第3週に予選2試合。年間ポイントTOP8が12月のMOBリーグへ進出。</p><b>RANK UP TOURNAMENT</b><p>4・7・11月の第2週。8人トーナメント。参加自由。優勝でF→E→D→C→B→A→S→SSへ昇格。SS優勝ではMOB MASTERにはならず、SSのままです。</p><div class="rank-prize-table"><div class="rank-prize-head"><strong>RANK</strong><span>RUNNER-UP</span><b>WINNER</b></div>${prizeRows}</div><b>MOB MASTER</b><p>1年目はMOBリーグ優勝者が初代MASTER。2年目以降は12月第3週にリーグ王者が現MASTERへ挑戦。5番勝負・3番先取。</p></div></details>`;}
export function competitionScreen(c){const p=c.profile;return `<section class="competition-page"><div class="competition-heading"><span class="eyebrow">ANNUAL COMPETITION</span><h1>TOURNAMENT</h1><p>MOBリーグとランクアップ大会で、1年を戦い抜け。</p></div>${scheduleCard(c)}<div class="competition-status"><span>RANK <b>${p.rank}</b></span><span>LEAGUE <b>${p.competition.leaguePoints} PT</b></span><span>${isPlayerMaster(p)?'<b>MOB MASTER</b>':'TOP 8を目指す'}</span></div>${qualifier(c)}${rankUp(c)}${leagueFinal(c)}${masterChallenge(c)}${ranking(c)}${yearlyRules()}</section>`;}
