import {stageBadge} from '../components/soul-performance.js';
import {publicAsset} from '../data/public-assets.js';
import {towerStarters} from '../data/tower.js';
import catalog from '../data/soul-catalog.js';
import {soulById,ensureSoulDecks,validateSoulDeck,soulDeckAddStatus} from '../game/soul-battle.js';
import {selectedAceIds} from './acePicker.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view='lineup';
export function selectDeckView(value){if(['lineup','inventory','starters'].includes(value))view=value;}
export function deckWorkshopScreen(c,filters,inventory,assistMarkup){
 const ids=ensureSoulDecks(c.profile),slot=c.profile.soulDeckSlot||0,check=validateSoulDeck(ids,c.profile.owned,{profile:c.profile}),stage=['seed','middle','mob','all'].includes(c.profile.soulDeckFilter)?c.profile.soulDeckFilter:'seed';
 const counts={};for(const id of ids)counts[id]=(counts[id]||0)+1;
 const unique=[...new Set(ids)],chosen=selectedAceIds(slot).filter(id=>unique.includes(id));const heroes=[...new Set([...chosen,...unique.filter(id=>soulById.get(id)?.soulClass!=='seed'),...unique])].filter(id=>soulById.has(id)&&!soulById.get(id).retired).slice(0,5);
 const image=id=>{const f=soulById.get(id);return f?`<img src="${esc(f.image)}" alt="${esc(f.name)}">`:'';};
 const packageArt=publicAsset('assets/towers/layers/starter-package-oct09.png');
 const filtersMarkup=`<div class="deck-stage-tabs" aria-label="段階で絞り込み">${[['all','すべて',ids.length],['seed','シード',check.counts.seed],['middle','ミドル',check.counts.middle],['mob','MOB',check.counts.mob]].map(([id,label,count])=>`<button data-soul-filter="${id}" aria-pressed="${stage===id}" class="${stage===id?'selected':''}"><span>${id==='all'?label:stageBadge({soulClass:id})}</span><b>${count}</b></button>`).join('')}</div>`;
 const lineup=`<div class="deck-panel-heading"><h2>いまの編成 <small>${ids.length}体</small></h2><button data-deck-plan="aces">5エースから編成 ↗</button></div><div class="deck-lineup-grid">${unique.filter(id=>stage==='all'||!soulById.get(id)||soulById.get(id).soulClass===stage).map(id=>{const f=soulById.get(id),status=f&&!f.retired?soulDeckAddStatus(c.profile,id):{allowed:false};return `<article class="deck-piece-stack"><button ${!f||f.retired?'data-soul-remove="'+ids.indexOf(id)+'"':'data-figure-info'+'="'+esc(id)+'"'}>${image(id)}${f?stageBadge(f):''}<b>${esc(f?.name||'未対応の旧ID')}</b></button>${f&&!f.retired&&f.soulClass!=='seed'?`<button class="deck-material-button" data-soul-recommend="${esc(id)}">おすすめの融合素材を見る</button>`:''}<div class="deck-quantity"><button data-soul-remove="${ids.indexOf(id)}" aria-label="${esc(f?.name||id)}を1体外す">−</button><strong aria-label="編成数${counts[id]}">${counts[id]}</strong><button data-soul-add="${esc(id)}" ${status.allowed?'':'disabled'} aria-label="${esc(f?.name||id)}を1体追加">＋</button></div></article>`;}).join('')||'<p class="deck-empty">この段階はまだ空いています。<br>「追加」から仲間を選ぼう。</p>'}</div><details class="deck-extra-tools"><summary>おまかせ編成・詳しいアシスト</summary><p class="deck-template-note">合計45体・段階の配分は自由（シード45体もOK）。同じIDはシード・ミドル各3体、MOB1体まで。DECK 1と2は同じIDを共有できません。</p><div class="soul-actions"><button data-soul-auto>おまかせ編成</button></div>${assistMarkup()}</details>`;
 const starters=`<div class="deck-panel-heading"><h2>初期スターターテンプレート</h2></div><div class="deck-starter-stage"><img src="${packageArt}" alt="スターターパッケージ"><span class="package-badge">3つの冒険、45体ずつ。</span></div><div class="deck-starter-products">${towerStarters.map((s,i)=>`<article class="deck-starter-product starter-${s.id}"><small>STARTER ${String(i+1).padStart(2,'0')}</small><h3>${esc(s.name)}</h3><div class="starter-members">${s.deck.slice(-3).map(image).join('')}</div><button data-piece-starter="${s.id}">この45体をセット</button></article>`).join('')}</div><p class="deck-template-note">所持分だけを使用し、選択中のDECKだけを置き換えます。所持品は増えません。</p>`;
 const inventoryMarkup=`<div class="deck-panel-heading"><h2>仲間を追加</h2><button data-deck-reset-filters>絞り込み解除</button></div><div class="deck-search-tools"><label>名前・ID・タグ<input type="search" id="deck-search" value="${esc(filters.query||'')}" placeholder="仲間を探す" autocomplete="off"></label><label>タグ<select id="deck-tag-filter"><option value="ALL">すべてのタグ</option>${catalog.tags.map(t=>`<option value="${t.id}" ${filters.tag===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>レア度<select id="deck-rarity-filter">${['ALL','R','SR','SSR','UR','MOB'].map(r=>`<option value="${r}" ${filters.rarity===r?'selected':''}>${r==='ALL'?'すべてのレア度':r}</option>`).join('')}</select></label></div><div class="soul-grid" id="deck-inventory">${inventory(c,stage,filters,counts)}</div>`;
 return `<section class="deck-workshop soul-library" data-deck-view="${view}"><header class="deck-workshop-heading"><h1>デッキをつくる</h1><span>MY DECK</span></header><div class="soul-slots">${Array.from({length:5},(_,i)=>`<button data-soul-slot="${i}" aria-pressed="${slot===i}" class="${slot===i?'selected':''}">DECK ${i+1}</button>`).join('')}</div><div class="deck-primary-actions"><button data-deck-build-new>1からデッキ編成</button><button data-soul-clear>DECK ${slot+1}を空にする</button></div><div class="deck-table"><div class="deck-table-label"><b>編成の主役</b><button data-deck-plan="aces">エースを選ぶ ↗</button></div><div class="deck-heroes">${Array.from({length:5},(_,i)=>heroes[i]?`<button data-${soulById.get(heroes[i])?.soulClass==='seed'?'figure-info':'soul-recommend'}="${esc(heroes[i])}">${image(heroes[i])}</button>`:`<span class="deck-hero-empty">${i+1}</span>`).join('')}</div></div><div class="deck-view-tabs" aria-label="編成メニュー">${[['lineup','編成'],['inventory','追加・入れ替え'],['starters','スターター']].map(([id,label])=>`<button data-deck-view="${id}" aria-pressed="${view===id}" class="${view===id?'selected':''}">${id==='starters'?`<img src="${packageArt}" alt="">`:''}${label}</button>`).join('')}</div>${view==='starters'?'':filtersMarkup}<div class="deck-panel-scroll" tabindex="-1">${view==='starters'?starters:view==='inventory'?inventoryMarkup:lineup}</div><footer class="deck-decision"><div><strong>${ids.length}<small> / 45体</small></strong><span>${check.valid?'保存済み · 対戦できます':esc(check.errors[0]||'編成中')}</span></div><button data-deck-done ${check.valid?'':'disabled'}>このデッキで決定</button></footer></section>`;
}
