import summonMessages from '../data/summon-messages.json' with {type:'json'};
import {testSettings} from '../data/test-settings.js';
import {banners,poolFor,pickupsFor,mainPickupFor,figureRate,ratesFor,OWN_CAP,OVERFLOW_RUBY,RARITY_RANK} from '../data/gacha.js';
import {prepareDraw,welcomeGift} from '../game/gacha.js';
import {commitProfile,saveProfile} from '../game/profile.js';
import {playSummon} from '../components/summon.js';
let ctx,refresh,notify,dialog,cleanup,returnFocus;let busy=false;
const gachaArt=f=>ctx.art(f).replace('loading="lazy"','loading="eager"');
const percent=n=>`${(n*100).toFixed(3)}%`;
const asset=path=>`${import.meta.env?.BASE_URL??'./'}${path}`;
export function gachaScreen(c){const b=banners.find(x=>x.id===c.profile.bannerId)||banners[0];return `<section class="gacha-page"><div class="gacha-heading"><div><span class="eyebrow">THE NEXT PIECE IS YOURS</span><h1>GACHA</h1></div><span class="gacha-wallet"><span class="mob-currency" aria-label="MOB">MOB</span> <b>${c.profile.diamonds}</b><small>ルビー ${c.profile.rubies}</small></span></div>${!c.profile.welcomeClaimed?'<button class="welcome-gift" data-gacha="gift"><span>WELCOME GIFT <b>はじめの10連を、あなたに。</b></span><strong>MOB 50<small>受け取る →</small></strong></button>':''}${testSettings.enabled?'<button class="test-wallet" data-gacha="max">TEST ONLY · ダイヤ（MOB）MAXにする</button>':''}<div class="gacha-carousel" aria-label="ガチャバナー">${banners.map(x=>`<button class="banner-slide" data-banner="${x.id}" style="--banner-color:${x.color}" aria-label="${x.name}の詳細"><span class="banner-number">SUMMON COLLECTION / ${x.id}</span><img src="${asset(`gacha/${x.id}.png`)}" alt="${x.name}"><span class="banner-bottom"><b>${x.name}</b><small>${x.subtitle}</small></span></button>`).join('')}</div><div class="carousel-controls"><button data-gacha="prev" aria-label="前のガチャ">←</button><div>${banners.map(x=>`<button data-select-banner="${x.id}" aria-label="${x.name}へ" aria-pressed="${x.id===b.id}" class="${x.id===b.id?'selected':''}"></button>`).join('')}</div><button data-gacha="next" aria-label="次のガチャ">→</button></div><div class="gacha-selection"><span class="eyebrow">NOW SELECTED</span><h2 data-banner-name>${b.name}</h2><p>10連は最後の1体がSR以上確定</p><div class="draw-actions"><button data-draw="1"><small>1回ひく</small><b>MOB 5</b></button><button data-draw="10"><span>SR以上 1体確定</span><small>10連ひく</small><b>MOB 50</b></button></div><button class="lineup-link" data-gacha="lineup">ラインナップ・提供割合を見る →</button>${c.profile.lastDraw?'<button class="last-result" data-gacha="last">前回の獲得結果を見る</button>':''}</div><details class="effect-guide"><summary>演出ギャラリー <span>獲得なしのプレビュー</span></summary><p>「ざわざわ…！」は高レアへの期待演出です。激アツゲート！はUR以上、主役のおでまし！はメインピックアップを含む場合だけ出現します。</p><div>${Object.entries(summonMessages.cues).map(([id,values])=>[id,values[0]]).map(([id,label])=>`<button data-preview="${id}">${String(label).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))} ↗</button>`).join('')}</div><small>演出で提供割合は変わりません。</small></details></section>`;}
function current(){return banners.find(b=>b.id===ctx.profile.bannerId)||banners[0];}
function bindImages(root){root.querySelectorAll('img').forEach(img=>{img.addEventListener('error',()=>{img.hidden=true;if(img.nextElementSibling?.classList.contains('missing'))img.nextElementSibling.hidden=false;});});}
function open(content){if(!dialog){returnFocus=document.activeElement;dialog=document.createElement('dialog');dialog.className='gacha-dialog';document.body.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();if(!busy)close();});dialog.addEventListener('click',handleDialog);dialog.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.querySelector('.figure-detail')){e.preventDefault();dialog.querySelector('.figure-detail').remove();dialog.querySelector('.gacha-sheet').inert=false;dialog.querySelector('[data-detail]')?.focus();}});dialog.showModal();}dialog.innerHTML=content;bindImages(dialog);dialog.querySelector('button')?.focus();}
function close(){cleanup?.();cleanup=null;dialog?.close();dialog?.remove();dialog=null;busy=false;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});}
const head=(en,title)=>`<header class="sheet-heading"><div><small>${en}</small><h2>${title}</h2></div><button data-gacha="close" aria-label="閉じる">×</button></header>`;
function detail(id){const f=ctx.byId.get(id);if(!f)return;const old=dialog.querySelector('.figure-detail');old?.remove();const layer=document.createElement('div');layer.className='figure-detail';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.setAttribute('aria-label',f.name);layer.innerHTML=`<section><button class="detail-back" data-gacha="detail-close">← 性能を閉じる</button><div class="detail-hero rarity-${f.rarity}">${gachaArt(f)}<span>${f.rarity}</span></div><small>${f.displayNo} / 所持 ${ctx.profile.owned[id]||0} / ${OWN_CAP[f.rarity]}</small><h2>${f.name}</h2><div class="stat-grid">${Object.entries({HP:f.mobPiece.hp,ATK:f.mobPiece.attack,DEF:f.mobPiece.defense,SPD:f.mobPiece.speed,COST:f.mobPiece.cost}).map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div><h3>ピースタグ</h3><div class="detail-tags">${f.tags.map(id=>ctx.tags.find(t=>t.id===id)).filter(Boolean).map(t=>`<p><b>${t.name}</b><span>2体：${t.pieceTwo?.label||'—'}</span><span>3体：${t.pieceThree?.label||'—'}</span></p>`).join('')}</div></section>`;dialog.querySelector('.gacha-sheet').inert=true;dialog.append(layer);bindImages(layer);layer.querySelector('button').focus();}
function lineup(){const b=current();const picks=pickupsFor(b);open(`<section class="gacha-sheet lineup-sheet">${head('LINEUP / '+b.id,'全'+poolFor(b).length+'種')}<p class="sheet-note">${b.name}<br>メインピックアップ：${mainPickupFor(b).name}</p><div class="rate-table"><div><b>レア度</b><b>通常</b><b>10連の最後</b></div>${['R','SR','SSR','UR','MOB'].map(r=>`<div><span>${r}</span><span>${percent(ratesFor(b)[r]||0)}</span><span>${percent(ratesFor(b,true)[r]||0)}</span></div>`).join('')}</div><p class="sheet-note">排出対象が存在するレア度で重みを再配分しています。各フィギュアの通常／10連最後の提供割合を表示。重複排出あり。</p><div class="lineup-grid">${poolFor(b).map(f=>`<button class="result-tile rarity-${f.rarity}" data-detail="${f.sourceId}"><span>${f.rarity}${picks.some(p=>p.sourceId===f.sourceId)?' / PU':''}</span>${gachaArt(f)}<b>${f.name}</b><small>${percent(figureRate(b,f))}<br>最後 ${percent(figureRate(b,f,true))}</small></button>`).join('')}</div><p class="sheet-note">所持上限 R15 / SR12 / SSR7 / UR4 / MOB2。超過時は自動でルビー R1 / SR3 / SSR5 / UR12 / MOB30へ変換。</p><button class="sheet-primary" data-gacha="close">ガチャに戻る</button></section>`);}
function bannerDetail(){const b=current();open(`<section class="gacha-sheet">${head('SUMMON / '+b.id,b.name)}<img class="sheet-banner" src="${asset('gacha/'+b.id+'.png')}" alt="${b.name}"><p class="sheet-note">全${poolFor(b).length}種 / 10連の最後はSR以上確定</p><div class="draw-actions"><button data-draw="1"><small>1回ひく</small><b>MOB 5</b></button><button data-draw="10"><small>10連ひく</small><b>MOB 50</b></button></div><button class="lineup-link" data-gacha="lineup">ラインナップ・提供割合を見る →</button><button class="sheet-primary" data-gacha="close">キャンセル</button></section>`);}
function confirmDraw(count){if(busy)return;const b=current();open(`<section class="gacha-sheet confirm-sheet">${head('MOB MAPLE','このガチャを引く？')}<p>${b.name}</p><div class="confirm-cost"><span>${count===10?'10連':'1回'}</span><b>MOB ${count*5}</b></div><p class="sheet-note">所持MOB ${ctx.profile.diamonds} → ${Math.max(0,ctx.profile.diamonds-count*5)}${count===10?'<br>最後の1体はSR以上確定':''}</p><div class="confirm-actions"><button data-gacha="close">いいえ</button><button data-confirm-draw="${count}" class="sheet-primary">はい、引く</button></div><p class="draw-error" role="alert"></p></section>`);}
function result(draw){busy=false;const rows=draw.entries,converted=rows.filter(e=>e.converted),rubyTotal=converted.reduce((n,e)=>n+e.ruby,0);const narration=converted.length?`<div class="limit-convert-callout" role="status" aria-live="polite"><small>COLLECTION LIMIT OVER</small><strong>RUBY CONVERT!</strong><p>所持上限を超えた ${converted.length}体を自動変換！<br><b>ルビー +${rubyTotal}</b> を獲得した！</p></div>`:'';open(`<section class="gacha-sheet result-sheet">${head('YOUR NEW COLLECTION','FIGURE GET!')}${narration}<p class="sheet-note">${rows.length}体のピースと出会いました。<br>タップして性能を確認できます。</p><div class="result-grid ${rows.length===1?'single-result':''}">${rows.map(e=>{const f=ctx.byId.get(e.id);return `<button class="result-tile rarity-${f.rarity} ${e.converted?'converted':''}" data-detail="${e.id}"><span>${f.rarity}${e.isNew?' <em>NEW</em>':''}</span>${gachaArt(f)}<b>${f.name}</b><small class="${e.converted?'ruby-converted':''}">${e.converted?'LIMIT OVER → ルビー +'+e.ruby:'獲得！'}</small></button>`;}).join('')}</div><p class="conversion-total">${converted.length?`ナレーション：所持上限を超えたフィギュアは自動でルビーへ変換されました。合計 +${rubyTotal} RUBY`:'獲得したフィギュアは保存されています。'}</p><button class="sheet-primary" data-gacha="close">ガチャに戻る</button></section>`);}
function cinematic(draw,preview=false){const b=banners.find(b=>b.id===draw.bannerId);const rows=draw.entries.map(e=>ctx.byId.get(e.id));const hero=draw.cue==='pickup'?rows.find(f=>f.sourceId===mainPickupFor(b).sourceId):[...rows].sort((a,b)=>RARITY_RANK[b.rarity]-RARITY_RANK[a.rarity])[0];busy=true;open('');cleanup=playSummon(dialog,{cue:draw.cue,hero,art:gachaArt,reduced:ctx.profile.reducedMotion||matchMedia('(prefers-reduced-motion: reduce)').matches,preview,onFinish:()=>{cleanup=null;busy=false;if(preview)close();else result(draw);}});bindImages(dialog);}
async function draw(count){if(busy)return;busy=true;try{const next=prepareDraw(ctx.profile,current(),count);if(!commitProfile(next))throw new Error('保存できませんでした。MOBは消費していません。');refresh({preserveScroll:true});const loadingDialog=dialog;dialog.querySelector('.draw-error').textContent='ピースを読み込み中…';await Promise.all(next.lastDraw.entries.map(e=>new Promise(resolve=>{const img=new Image();const timer=setTimeout(resolve,2500);img.onload=img.onerror=()=>{clearTimeout(timer);resolve();};img.src=asset(ctx.byId.get(e.id).image);})));if(dialog!==loadingDialog)return;cinematic(next.lastDraw);}catch(error){busy=false;dialog.querySelector('.draw-error').textContent=error.message;}}
function preview(cue){const b=current();const pool=poolFor(b);const f=cue==='pickup'?mainPickupFor(b):pool.find(f=>cue==='ultra'?RARITY_RANK[f.rarity]>=4:cue==='chance'?f.rarity==='SSR':f.rarity==='R');cinematic({bannerId:b.id,cue,entries:[{id:f.sourceId}]},true);}
function handleDialog(e){const button=e.target.closest('button');if(!button)return;if(button.dataset.draw){confirmDraw(Number(button.dataset.draw));return;}if(button.dataset.gacha==='lineup'){lineup();return;}if(button.dataset.detail){detail(button.dataset.detail);return;}if(button.dataset.gacha==='detail-close'){dialog.querySelector('.figure-detail').remove();dialog.querySelector('.gacha-sheet').inert=false;dialog.querySelector('[data-detail]')?.focus({preventScroll:true});return;}if(button.dataset.gacha==='close'&&!busy)close();if(button.dataset.confirmDraw)draw(Number(button.dataset.confirmDraw));}
export function initGacha(c,render,toast){ctx=c;refresh=render;notify=toast;window.addEventListener('hashchange',close);}
export function bindGacha(){const rail=document.querySelector('.gacha-carousel');if(!rail)return;const selected=banners.findIndex(b=>b.id===ctx.profile.bannerId);rail.scrollLeft=rail.clientWidth*selected;let timer;rail.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!rail.isConnected)return;const i=Math.max(0,Math.min(banners.length-1,Math.round(rail.scrollLeft/rail.clientWidth)));ctx.profile.bannerId=banners[i].id;saveProfile();document.querySelector('[data-banner-name]').textContent=banners[i].name;document.querySelectorAll('[data-select-banner]').forEach(el=>{const active=el.dataset.selectBanner===banners[i].id;el.classList.toggle('selected',active);el.setAttribute('aria-pressed',String(active));});},100);});}
export function handleGacha(button){if(button.dataset.banner){ctx.profile.bannerId=button.dataset.banner;saveProfile();bannerDetail();return;}if(button.dataset.selectBanner){select(button.dataset.selectBanner);return;}if(button.dataset.draw){confirmDraw(Number(button.dataset.draw));return;}if(button.dataset.preview){preview(button.dataset.preview);return;}const action=button.dataset.gacha;if(action==='max'&&testSettings.enabled){if(commitProfile({...structuredClone(ctx.profile),diamonds:testSettings.maxCurrency})){refresh({preserveScroll:true});notify('テスト用残高をMAXにしました');}else notify('保存できませんでした');return;}if(action==='gift'){try{if(!commitProfile(welcomeGift(ctx.profile)))throw new Error('保存できませんでした。時間をおいてお試しください。');refresh({preserveScroll:true});notify('ウェルカムギフト：50MOBを受け取りました');}catch(e){notify(e.message);}}if(action==='lineup')lineup();if(action==='last'&&ctx.profile.lastDraw)result(ctx.profile.lastDraw);if(action==='next'||action==='prev'){const i=banners.findIndex(b=>b.id===ctx.profile.bannerId);select(banners[(i+(action==='next'?1:-1)+banners.length)%banners.length].id);}}
function select(id){const i=banners.findIndex(b=>b.id===id);ctx.profile.bannerId=id;saveProfile();const rail=document.querySelector('.gacha-carousel');rail.scrollTo({left:rail.clientWidth*i,behavior:ctx.profile.reducedMotion?'instant':'smooth'});}

