import {validateDeck} from '../game/deck.js';
import {unlocks,normalizeBattleProgress} from '../game/battle.js';
import {FREE_BATTLE,RANK_MATCH_REWARDS} from '../data/battle.js';
const heading=(en,ja)=>`<div class="page-heading"><span class="eyebrow">MOB PIECE BATTLE</span><h1>${en}</h1><p>${ja}</p></div>`;
const card=(c,f,action)=>`<article class="figure-card"><div class="card-art"><span class="card-rarity">${f.rarity}</span>${c.art(f)}</div><small>${f.displayNo} · COST ${f.mobPiece.cost} · 所持 ${c.profile.owned[f.sourceId]||0}</small><b>${f.name}</b><button ${action==='add'?`data-add="${f.sourceId}"`:`data-center="${f.sourceId}"`} ${f.pending?'disabled':''}>${f.pending?'未公開':action==='add'?'＋ 追加 ('+c.profile.deck.filter(id=>id===f.sourceId).length+')':c.profile.centerId===f.sourceId?'センター設定中':'センターに設定'}</button></article>`;
export function collectionScreen(c,query,rarity){const rows=c.figures.filter(f=>(rarity==='ALL'||f.rarity===rarity)&&(`${f.name} ${f.displayNo}`.toLowerCase().includes(query.toLowerCase())));return `<section class="library">${heading('FIGURE','お気に入りを、コレクションルームの主役に。')}<label class="search-label">フィギュア検索<input id="figure-search" type="search" placeholder="名前・図鑑番号で検索" aria-label="名前・図鑑番号で検索"></label><div class="filters">${['ALL','R','SR','SSR','UR','MOB'].map(r=>`<button data-filter="${r}" class="${rarity===r?'selected':''}">${r}</button>`).join('')}</div><p class="count">${rows.length} / ${c.figures.length} FIGURES <span>図鑑プレビュー</span></p><div class="figure-grid">${rows.map(f=>card(c,f,'center')).join('')||'<p>一致するフィギュアがありません。</p>'}</div></section>`;}
export function deckScreen(c){const result=validateDeck(c.profile.deck,c.byId);return `<section class="library">${heading('MY DECK','25体のピースで、自分だけのチームを。')}<div class="deck-meter"><span>FIGURES <b>${result.count}<small>/25</small></b></span><span>TOTAL COST <b>${result.cost}<small>/80</small></b></span></div><p class="notice">編成プランとして保存します。未所持のピースも試せます。戦闘接続時に所持数を確認します。</p><p class="cap-guide">同一フィギュア上限：R・SR 3体 / SSR・UR 2体 / MOB 1体</p><div class="deck-slots">${Array.from({length:25},(_,i)=>{const f=c.byId.get(c.profile.deck[i]);return f?`<button data-remove="${i}" aria-label="${f.name}を編成から外す">${c.art(f)}<small>${i+1} ×</small></button>`:`<div><span>＋</span><small>${String(i+1).padStart(2,'0')}</small></div>`;}).join('')}</div><p class="deck-ready">${result.valid?'✓ 25体・COST・重複上限の条件を満たしています':'あと'+(25-result.count)+'体でチーム完成'}<small>編成中のピースをタップすると外せます</small></p><h2 class="section-title">ADD A PIECE <span>フィギュアを選ぶ</span></h2><div class="figure-grid">${c.figures.filter(f=>!f.pending).map(f=>card(c,f,'add')).join('')}</div></section>`;}
export function battleScreen(c){
  normalizeBattleProgress(c.profile);const u=unlocks(c.profile),rankReward=RANK_MATCH_REWARDS[c.profile.rank];
  const diff=(id,label,open)=>{const r=FREE_BATTLE[id];return `<button class="battle-difficulty ${id}" data-battle-start="free:${id}" ${open?'':'disabled'}><span><small>${open?'FREE BATTLE':'LOCKED'}</small><b>${label}</b><em>${open?`${r.coins.toLocaleString('ja-JP')} COIN + ${r.diamonds} DIAMOND`:id==='hard'?'RANK Cで解放':'RANK Aで解放'}</em></span><strong>→</strong></button>`;};
  return `<section class="library battle-hub">${heading('BATTLE','25体のデッキから5体を引き、2本先取で勝負。')}<div class="arena-intro">${c.icon('battle')}<b>5 vs 5</b><span>25体デッキ / 毎BATTLE 5体DRAW / 2勝先取</span></div><div class="battle-system-note"><b>CENTER</b><span>3番のフィギュアは全能力+25%</span><b>EXCHANGE</b><span>各BATTLEで1体だけ交換可能</span><b>PIECE BOOST</b><span>1試合に1回、選んだ1体をそのBATTLEだけ全能力+15%</span></div><h2 class="section-title">FREE BATTLE <span>難易度を選択</span></h2><div class="battle-difficulty-list">${diff('easy','EASY',true)}${diff('hard','HARD',u.hard)}${diff('inferno','INFERNO',u.inferno)}</div><h2 class="section-title">RANK MATCH <span>F → SS</span></h2><button class="rank-match-start" data-battle-start="rank"><span><small>CURRENT RANK</small><b>RANK ${c.profile.rank}</b><em>${c.profile.rankPoints}/5 POINT</em></span><span><small>WIN REWARD</small><b>${rankReward.coins.toLocaleString('ja-JP')} COIN</b><em>+ ${rankReward.diamonds} DIAMOND</em></span><strong>START →</strong></button><h2 class="section-title">COMPETITION <span>年間大会</span></h2><button class="mode tournament-live" data-go="tournament"><span class="mode-icon">${c.icon('tournament')}</span><span><small>ANNUAL COMPETITION</small><b>TOURNAMENT</b><em>MOBリーグ / ランクアップトーナメント</em></span><span>→</span></button><div class="future-mode-row"><button disabled>SPECIAL BATTLE<small>今後追加予定</small></button><button disabled>BOSS RAID<small>今後追加予定</small></button></div></section>`;
}
export function infoScreen(c,route){if(route==='settings')return `<section class="library">${heading('SETTINGS','心地よく遊ぶための設定。')}<button class="setting-row" data-action="motion"><span>動きを抑える</span><b>${c.profile.reducedMotion?'ON':'OFF'}</b></button><p class="notice">センターフィギュア・編成プラン・設定はこのブラウザに保存されます。</p></section>`;if(route==='profile')return `<section class="library">${heading('COLLECTOR','あなたのコレクションは、ここから。')}<div class="arena-intro"><b>RANK ${c.profile.rank}</b><span>MOB LEAGUE ${c.profile.competition.leaguePoints} POINT</span></div><p class="notice">現在 ${c.profile.competition.date.year}年目 ${c.profile.competition.date.month}月 第${c.profile.competition.date.week}週。年間大会の詳細はBATTLE → TOURNAMENTから確認できます。</p><button class="simple-cta" data-go="tournament">大会スケジュールを見る →</button></section>`;return `<section class="library">${heading('GACHA','新しい出会いを、準備中。')}<div class="arena-intro">${c.icon('gacha')}<b>COMING SOON</b></div><p class="notice">入手機能は今後追加予定です。まずは図鑑で、お気に入りのピースを見つけよう。</p><button class="simple-cta" data-go="figure">図鑑を見る →</button></section>`;}
