import {validateDeck,RULES,DECK_SLOT_COUNT} from '../game/deck.js';
import {unlocks,normalizeBattleProgress} from '../game/battle.js';
import {FREE_BATTLE,RANK_MATCH_REWARDS} from '../data/battle.js';
import {figureRecord} from '../game/records.js';
const heading=(en,ja)=>`<div class="page-heading"><span class="eyebrow">MOB PIECE BATTLE</span><h1>${en}</h1><p>${ja}</p></div>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(c,f,action)=>{const owned=c.profile.owned[f.sourceId]||0,isOwned=owned>0,rec=figureRecord(c.profile,f.sourceId);return `<article class="figure-card ${isOwned?'owned':'locked'}"><button class="card-art" data-figure-info="${f.sourceId}" aria-label="${isOwned?esc(f.name):'未所持フィギュア'}の詳細"><span class="card-rarity">${f.rarity}</span>${c.art(f)}${!isOwned?'<span class="figure-lock">?</span>':''}</button><small>${f.displayNo} · COST ${f.mobPiece.cost} · 所持 ${owned}</small><b>${isOwned?esc(f.name):'？？？'}</b><em>出場 ${rec.appearances} · 勝利 ${rec.matchWins}</em>${action==='center'?`<button data-center="${f.sourceId}" ${!isOwned||f.pending?'disabled':''}>${!isOwned?'未所持':c.profile.centerId===f.sourceId?'センター設定中':'センターに設定'}</button>`:`<button data-add="${f.sourceId}" ${!isOwned||f.pending?'disabled':''}>${!isOwned?'未所持':'＋ 追加 ('+c.profile.deck.filter(id=>id===f.sourceId).length+')'}</button>`}</article>`;};
export function collectionScreen(c,query,rarity,status='ALL'){
 const released=c.figures.filter(f=>!f.pending),ownedCount=released.filter(f=>(c.profile.owned[f.sourceId]||0)>0).length;
 const rows=released.filter(f=>{const own=(c.profile.owned[f.sourceId]||0)>0;return (rarity==='ALL'||f.rarity===rarity)&&(status==='ALL'||(status==='OWNED'&&own)||(status==='MISSING'&&!own))&&(`${f.name} ${f.displayNo}`.toLowerCase().includes(query.toLowerCase()));});
 const rarityStats=['R','SR','SSR','UR','MOB'].map(r=>{const all=released.filter(f=>f.rarity===r).length,own=released.filter(f=>f.rarity===r&&(c.profile.owned[f.sourceId]||0)>0).length;return `<span><small>${r}</small><b>${own}/${all}</b></span>`;}).join('');
 return `<section class="library collection-page">${heading('FIGURE','No.001から続くMOBフィギュア図鑑。集めた記録も残ります。')}<div class="dex-overview"><div><small>COLLECTION</small><b>${ownedCount}<em>/ ${released.length}</em></b><span>${Math.round(ownedCount/Math.max(1,released.length)*100)}% COMPLETE</span></div><div class="dex-rarity">${rarityStats}</div></div><label class="search-label">フィギュア検索<input id="figure-search" type="search" placeholder="名前・図鑑番号で検索" aria-label="名前・図鑑番号で検索"></label><div class="collection-status">${[['ALL','ALL'],['OWNED','所持'],['MISSING','未所持']].map(([id,label])=>`<button data-collection-status="${id}" class="${status===id?'selected':''}">${label}</button>`).join('')}</div><div class="filters">${['ALL','R','SR','SSR','UR','MOB'].map(r=>`<button data-filter="${r}" class="${rarity===r?'selected':''}">${r}</button>`).join('')}</div><p class="count">${rows.length} FIGURES <span>タップで詳細</span></p><div class="figure-grid">${rows.map(f=>card(c,f,'center')).join('')||'<p>一致するフィギュアがありません。</p>'}</div></section>`;
}
export function deckScreen(c){
 const result=validateDeck(c.profile.deck,c.byId,c.profile.owned),ownedRows=c.figures.filter(f=>!f.pending&&(c.profile.owned[f.sourceId]||0)>0);
 const pickerCards=ownedRows.map(f=>{const used=c.profile.deck.filter(id=>id===f.sourceId).length,own=c.profile.owned[f.sourceId]||0,cap=Math.min(own,RULES.duplicateCaps[f.rarity]||1),disabled=used>=cap;return `<button class="deck-pick-card" data-pick-figure="${f.sourceId}" ${disabled?'disabled':''}><span class="deck-pick-art">${c.art(f)}</span><span><small>${f.displayNo} · ${f.rarity} · COST ${f.mobPiece.cost}</small><b>${esc(f.name)}</b><em>所持 ${own} / 編成 ${used}${disabled?' · 上限':''}</em></span></button>`;}).join('');
 const tabs=Array.from({length:DECK_SLOT_COUNT},(_,i)=>{const ids=c.profile.deckPresets?.[i]||[],r=validateDeck(ids,c.byId,c.profile.owned);return `<button data-deck-slot="${i}" class="${c.profile.activeDeckSlot===i?'active':''}"><small>DECK</small><b>${i+1}</b><em>${r.count}/25 · C${r.cost}</em></button>`;}).join('');
 return `<section class="library">${heading('MY DECK','5つのデッキを保存。25体のピースで、自分だけのチームを。')}<div class="deck-presets">${tabs}</div><div class="deck-meter"><span>FIGURES <b>${result.count}<small>/25</small></b></span><span>TOTAL COST <b>${result.cost}<small>/80</small></b></span></div><div class="deck-tools"><button data-auto-deck>おまかせ編成</button><button data-clear-deck>デッキを空にする</button></div><p class="notice">空いている枠をタップすると、所持フィギュアだけを一覧表示します。現在は DECK ${c.profile.activeDeckSlot+1} を編集中です。</p><p class="cap-guide">同一フィギュア編成上限：R・SR 3体 / SSR・UR 2体 / MOB 1体</p><div class="deck-slots">${Array.from({length:25},(_,i)=>{const f=c.byId.get(c.profile.deck[i]);return f?`<button data-remove="${i}" class="filled" aria-label="${esc(f.name)}を編成から外す">${c.art(f)}<small>${i+1} ×</small></button>`:`<button class="empty" data-open-deck-picker="${i}" aria-label="${i+1}番にフィギュアを追加"><span>＋</span><small>${String(i+1).padStart(2,'0')}</small></button>`;}).join('')}</div><p class="deck-ready">${result.valid?'✓ 25体・COST・重複上限・所持数の条件を満たしています':'あと'+Math.max(0,25-result.count)+'体でチーム完成'}<small>編成中のピースをタップすると外せます</small></p><h2 class="section-title">ADD A PIECE <span>所持フィギュアから追加</span></h2><div class="figure-grid">${ownedRows.map(f=>card(c,f,'add')).join('')||'<p class="notice">所持フィギュアがありません。</p>'}</div><div class="deck-picker" data-deck-picker hidden><div class="deck-picker-sheet"><div class="deck-picker-head"><div><small>OWNED FIGURES</small><h2>フィギュアを選ぶ</h2></div><button data-close-deck-picker aria-label="閉じる">×</button></div><p>所持しているフィギュアのみ表示しています。</p><div class="deck-picker-list">${pickerCards||'<div class="deck-picker-empty">所持フィギュアがありません。</div>'}</div></div></div></section>`;
}
export function battleScreen(c){
  normalizeBattleProgress(c.profile);const u=unlocks(c.profile),rankReward=RANK_MATCH_REWARDS[c.profile.rank];
  const diff=(id,label,open)=>{const r=FREE_BATTLE[id];return `<button class="battle-difficulty ${id}" data-battle-start="free:${id}" ${open?'':'disabled'}><span><small>${open?'FREE BATTLE':'LOCKED'}</small><b>${label}</b><em>${open?`${r.coins.toLocaleString('ja-JP')} COIN + ${r.diamonds} DIAMOND`:id==='hard'?'RANK Cで解放':'RANK Aで解放'}</em></span><strong>→</strong></button>`;};
  return `<section class="library battle-hub">${heading('BATTLE','25体のデッキから5体を引き、2本先取で勝負。')}<div class="arena-intro">${c.icon('battle')}<b>5 vs 5</b><span>25体デッキ / 毎BATTLE 5体DRAW / 2勝先取</span></div><div class="battle-system-note"><b>CENTER</b><span>3番のフィギュアは全能力+25%</span><b>EXCHANGE</b><span>各BATTLEで1体だけ交換可能</span><b>PIECE BOOST</b><span>1試合に1回、選んだ1体をそのBATTLEだけ全能力+15%</span></div><h2 class="section-title">FREE BATTLE <span>難易度を選択</span></h2><div class="battle-difficulty-list">${diff('easy','EASY',true)}${diff('hard','HARD',u.hard)}${diff('inferno','INFERNO',u.inferno)}</div><h2 class="section-title">RANK MATCH <span>F → SS</span></h2><button class="rank-match-start" data-battle-start="rank"><span><small>CURRENT RANK</small><b>RANK ${c.profile.rank}</b><em>${c.profile.rankPoints}/5 POINT</em></span><span><small>WIN REWARD</small><b>${rankReward.coins.toLocaleString('ja-JP')} COIN</b><em>+ ${rankReward.diamonds} DIAMOND</em></span><strong>START →</strong></button><h2 class="section-title">COMPETITION <span>年間大会</span></h2><button class="mode tournament-live" data-go="tournament"><span class="mode-icon">${c.icon('tournament')}</span><span><small>ANNUAL COMPETITION</small><b>TOURNAMENT</b><em>MOBリーグ / ランクアップトーナメント</em></span><span>→</span></button><div class="future-mode-row"><button disabled>SPECIAL BATTLE<small>今後追加予定</small></button><button disabled>BOSS RAID<small>今後追加予定</small></button></div></section>`;
}
export function infoScreen(c,route){if(route==='settings')return `<section class="library">${heading('SETTINGS','心地よく遊ぶための設定。')}<button class="setting-row" data-action="motion"><span>動きを抑える</span><b>${c.profile.reducedMotion?'ON':'OFF'}</b></button><p class="notice">センターフィギュア・5つのデッキ・設定・対戦履歴はこのブラウザに保存されます。</p></section>`;if(route==='profile'){const h=c.profile.battleHistory||[],battles=Number(c.profile.battleStats?.battles??h.length),wins=Number(c.profile.battleStats?.wins??h.filter(x=>x.won).length);return `<section class="library">${heading('COLLECTOR','あなたのコレクションと戦績。')}<div class="arena-intro"><b>RANK ${c.profile.rank}</b><span>MOB LEAGUE ${c.profile.competition.leaguePoints} POINT</span></div><div class="profile-stats"><span><small>BATTLES</small><b>${battles}</b></span><span><small>WINS</small><b>${wins}</b></span><span><small>FIGURES</small><b>${c.figures.filter(f=>(c.profile.owned[f.sourceId]||0)>0).length}</b></span></div><div class="profile-links"><button data-go="history">BATTLE HISTORY <span>対戦履歴 →</span></button><button data-go="hall">HALL OF FAME <span>歴代MOB MASTER →</span></button><button data-go="mission">MISSION <span>達成報酬 →</span></button></div><p class="notice">現在 ${c.profile.competition.date.year}年目 ${c.profile.competition.date.month}月 第${c.profile.competition.date.week}週。</p><button class="simple-cta" data-go="tournament">大会スケジュールを見る →</button></section>`;}return `<section class="library">${heading(route==='shop'?'SHOP':route==='event'?'EVENT':'SCREEN','今後追加予定のコンテンツです。')}<div class="arena-intro"><b>COMING SOON</b></div><p class="notice">基盤は拡張可能な状態で準備されています。</p></section>`;}
