import {allMissionStates} from '../game/missions.js?v=6.1.1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=m=>{const pct=Math.min(100,Math.round(m.progress/Math.max(1,m.target)*100));return `<article class="mission-card ${m.claimed?'claimed':m.complete?'ready':''}"><div><small>${esc(m.category)}</small><b>${esc(m.title)}</b><p>${esc(m.description)}</p></div><div class="mission-progress"><span><i style="width:${pct}%"></i></span><b>${Math.min(m.progress,m.target)} / ${m.target}</b></div><div class="mission-reward"><span>${m.reward.coins.toLocaleString('ja-JP')} COIN</span><span>${m.reward.diamonds} DIAMOND</span></div><button data-mission-claim="${m.id}" ${m.complete&&!m.claimed?'':'disabled'}>${m.claimed?'受取済み':m.complete?'受け取る':'挑戦中'}</button></article>`;};
export function missionScreen(c){
  const states=allMissionStates(c.profile,{figures:c.figures,byId:c.byId});
  const ready=states.filter(x=>x.complete&&!x.claimed),claimed=states.filter(x=>x.claimed),open=states.filter(x=>!x.complete&&!x.claimed);
  const categories=[...new Set(open.map(x=>x.category))];
  return `<section class="library mission-page"><div class="asset-page-heading">${c.menuArt('mission','mission-title-art','MISSION')}<div><span class="eyebrow">PLAY · COLLECT · ACHIEVE</span><h1>MISSION</h1><p>達成済みミッションを最上部へ表示。まとめて受け取れます。</p></div></div><div class="mission-summary"><span><small>CLAIMABLE</small><b>${ready.length}</b></span><span><small>COMPLETE</small><b>${claimed.length}/${states.length}</b></span></div><button class="mission-claim-all" data-mission-claim-all ${ready.length?'':'disabled'}>${ready.length?`達成報酬を一括受け取り · ${ready.length}件`:'受け取れる報酬はありません'}</button>${ready.length?`<section class="mission-group ready-group"><h2>CLAIM NOW <span>達成済み</span></h2><div class="mission-list">${ready.map(card).join('')}</div></section>`:''}${categories.map(cat=>`<section class="mission-group"><h2>${esc(cat)}</h2><div class="mission-list">${open.filter(x=>x.category===cat).map(card).join('')}</div></section>`).join('')}${claimed.length?`<details class="mission-claimed"><summary>受取済みミッション ${claimed.length}件</summary><div class="mission-list">${claimed.map(card).join('')}</div></details>`:''}</section>`;
}
