const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=t=>{const d=new Date(Number(t)||0);return Number.isNaN(d.getTime())?'—':`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const mini=(c,id)=>{const f=c.byId.get(id);return f?`<span class="history-mini" title="${esc(f.name)}">${c.art(f)}</span>`:'';};
const modeGroup=r=>{const m=String(r.mode||'');if(m.startsWith('free-'))return 'FREE';if(m==='random')return 'RANDOM';if(m.startsWith('qualifier')||m.startsWith('mob-league'))return 'LEAGUE';if(m.startsWith('rankup-tournament'))return 'TOURNAMENT';if(m.startsWith('mob-master'))return 'MASTER';return 'OTHER';};
export function historyScreen(c,filter='ALL'){
 const all=[...(c.profile.battleHistory||[])].reverse(),rows=filter==='ALL'?all:all.filter(r=>modeGroup(r)===filter);
 const tabs=[['ALL','ALL'],['FREE','FREE BATTLE'],['RANDOM','RANDOM BATTLE'],['LEAGUE','MOB LEAGUE'],['TOURNAMENT','RANK TOURNAMENT'],['MASTER','MOB MASTER']];
 return `<section class="library history-page"><div class="asset-page-heading">${c.menuArt('history','history-title-art','HISTORY')}<div><span class="eyebrow">BATTLE ARCHIVE</span><h1>HISTORY</h1><p>対戦相手・日時・結果・使用デッキをモード別に確認できます。</p></div></div><div class="history-summary"><b>${all.length}</b><span>RECORDED MATCHES</span></div><div class="history-filters">${tabs.map(([id,label])=>`<button data-history-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div><div class="history-list">${rows.length?rows.map(r=>`<details class="history-card ${r.won?'win':'lose'}"><summary><span class="history-result-icon">${c.iconArt(r.won?'win':'loss','history-result-art',r.won?'WIN':'LOSE')}</span><span><small>${esc(r.title||r.mode||'BATTLE')}</small><b>${r.won?'WIN':'LOSE'} · ${(r.score||[0,0]).join(' - ')}</b><em>VS ${esc(r.opponentName||'CPU')}</em></span><time>${fmt(r.at)}</time></summary><div class="history-detail"><h3>PLAYER DECK</h3><div class="history-deck">${(r.playerDeck||[]).map(id=>mini(c,id)).join('')||'<p>旧バージョンの記録です</p>'}</div><h3>OPPONENT DECK</h3><div class="history-deck">${(r.opponentDeck||[]).map(id=>mini(c,id)).join('')||'<p>旧バージョンの記録です</p>'}</div>${(r.rounds||[]).length?`<h3>BATTLE BREAKDOWN</h3><div class="history-rounds">${r.rounds.map(x=>`<div><b>BATTLE ${x.round} · ${x.won?'WIN':'LOSE'}</b><span>${(x.pHand||[]).map(id=>mini(c,id)).join('')}</span>${x.boostId?`<small>PIECE BOOST：${esc(c.byId.get(x.boostId)?.name||x.boostId)}</small>`:''}</div>`).join('')}</div>`:''}</div></details>`).join(''):'<p class="notice">この条件の対戦記録はありません。</p>'}</div></section>`;
}
export function hallOfFameScreen(c){const comp=c.profile.competition||{},seasons=[...(comp.seasonHistory||[])].reverse();const currentFinalName=comp.leagueFinal?.finalists?.find(x=>x.id===comp.masterHolder)?.name;const holder=comp.masterHolder==='PLAYER'?'PLAYER':(currentFinalName||seasons.find(x=>x.masterHolder?.id===comp.masterHolder)?.masterHolder?.name||comp.masterHolder||'未決定');return `<section class="library hall-page"><div class="page-heading"><span class="eyebrow">MOB LEAGUE LEGACY</span><h1>HALL OF FAME</h1><p>歴代MOBリーグとMOB MASTERの記録。</p></div><div class="master-throne">${c.rankArt('MOB_MASTER','master-rank-art','MOB MASTER')}<small>CURRENT MOB MASTER</small><b>${esc(holder)}</b><span>${comp.masterSinceYear?`${comp.masterSinceYear}年目から在位`:'王者決定前'}</span></div>${seasons.length?`<div class="season-archive">${seasons.map(s=>`<article class="season-card"><header><small>SEASON</small><b>YEAR ${s.year}</b></header><div><span>MOB LEAGUE CHAMPION</span><strong>${esc(s.leagueChampion?.name||'—')}</strong></div><div><span>MOB MASTER</span><strong>${esc(s.masterHolder?.name||'—')}</strong></div>${s.masterChallenge?`<p>MASTER MATCH：${esc(s.masterChallenge.defenderName)} ${s.masterChallenge.defenderWins} - ${s.masterChallenge.challengerWins} ${esc(s.masterChallenge.challengerName)}<br>WINNER：${esc(s.masterChallenge.winnerName||'—')}</p>`:''}${s.leagueTable?.length?`<details><summary>最終順位を見る</summary>${s.leagueTable.map(x=>`<p>${x.position}. ${esc(x.name)} · ${x.wins}勝${x.losses}敗</p>`).join('')}</details>`:''}</article>`).join('')}</div>`:'<p class="notice">シーズン終了後、歴代記録がここに保存されます。</p>'}</section>`;}
