import {stageBadge} from '../components/soul-performance.js';
import {deckWorkshopScreen} from './deckWorkshop.js';
import {publicAsset} from '../data/public-assets.js';
import {towerStarters} from '../data/tower.js';
import {isFavorite} from '../game/favorites.js';
import {acquisitionText} from '../game/acquisition.js';
import {familyIds,familyCollectionMarkup} from '../game/family-collection.js';
import {elementIds,elementCollectionMarkup} from '../game/element-collection.js';
import {release} from '../game/initial-release.js';
import {pieceStarters} from '../game/piece-starters.js';
import {deckAssistMarkup} from './soulDeckAssist.js';
import {soulStarters} from '../game/soul-starters.js';
import {testSettings} from '../data/test-settings.js';
import {availableDeckOwned,soulCopyLimits} from '../game/deck-legality.js';
import {soulFigures,soulById,classNames,quotas,validateSoulDeck,ensureSoulDecks,soulDeckAddStatus} from '../game/soul-battle.js';
import catalog from '../data/soul-catalog.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tagName=id=>catalog.tags.find(t=>t.id===id)?.name||id;
const timing=f=>f.soulSkill.timingLabel;
export function soulInfo(f){const s=soulById.get(f.sourceId||f.id);if(!s)return '<p>原典照合待ち</p>';return `<div class="soul-chips">${stageBadge(s)}<b>${s.attribute}属性</b><b>${s.rarity}</b></div><div class="soul-stats"><span>ATK <b>${s.atk}</b></span><span>DEF <b>${s.def}</b></span></div><p>入手：${esc(acquisitionText(s.id))}</p><h3>${esc(s.soulSkill.name)}</h3><small>${timing(s)} · 各個体1ターン1回・対戦中シード1／ミドル2／MOB3回（常時効果を除く）</small><p>${esc(s.soulSkill.description)}</p><div class="soul-tags">${s.tags.map(t=>`<span>${esc(tagName(t))}</span>`).join('')}</div>${s.soulClass==='seed'?'':`<details><summary>融合素材を見る</summary><p>${(s.fusionMaterials||[]).map(r=>`${r.special?'MOB SOUL FUSION · ATK/DEF +25':classNames[r.fromClass]}：${esc(r.label)}`).join('<br>')||'条件付きの召喚で登場します'}</p></details>`}`;}
const head=(title,sub)=>`<div class="page-heading"><span class="eyebrow">MOB PIECE BATTLE · SOUL FUSION</span><h1>${title}</h1><p>${sub}</p></div>`;
const rank={R:1,SR:2,SSR:3,UR:4,MOB:5};
export function collectionScreen(c,query='',rarity='ALL',status='ALL',sort='DEX_ASC',tag='ALL',group='main',favoritesOnly=false){
 const rows=soulFigures.filter(f=>(!favoritesOnly||isFavorite(c.profile,f.id))&&(group==='ALL'||f.collection===group)&&(rarity==='ALL'||f.rarity===rarity)&&(tag==='ALL'||f.tags.includes(tag))&&(status==='ALL'||(status==='OWNED')===((c.profile.owned[f.id]||0)>0))&&([f.name,f.id,...f.tags.map(tagName)].join(' ').normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').toLowerCase())));
 rows.sort(({id:a}, {id:b})=>{const x=soulById.get(a),y=soulById.get(b);return ({RARITY_DESC:()=>rank[y.rarity]-rank[x.rarity],ATTRIBUTE:()=>x.attribute.localeCompare(y.attribute,'ja'),TAG:()=>x.tags.map(tagName).join().localeCompare(y.tags.map(tagName).join(),'ja'),ATK_DESC:()=>y.atk-x.atk,DEF_DESC:()=>y.def-x.def,NAME_ASC:()=>x.name.localeCompare(y.name,'ja')}[sort]||(()=>0))()||a.localeCompare(b);});
 return `<section class="library soul-library">${head('FIGURE',`編集できるスターター2デッキで出発。全${soulFigures.length}体のソウル。`)}<a class="soul-link" href="./figure-catalog.html" target="_blank" rel="noopener">全性能・原典・レシピのHTML一覧 ↗</a><label>コレクション<select id="figure-collection">${[["main","メイン（初期・追加）"],["collab","コラボ（MOB STORYほか）"],["ALL","すべて"]].map(([id,name])=>`<option value="${id}" ${group===id?"selected":""}>${name}</option>`).join("")}</select></label><label class="search-label">フィギュア検索<input id="figure-search" value="${esc(query)}" placeholder="名前・ID・タグで検索"></label><div class="dex-controls"><label>並び順<select id="figure-sort">${[['DEX_ASC','ID順'],['RARITY_DESC','レア度順'],['ATTRIBUTE','属性順'],['TAG','タグ順'],['ATK_DESC','ATK順'],['DEF_DESC','DEF順'],['NAME_ASC','名前順']].map(([id,n])=>`<option value="${id}" ${sort===id?'selected':''}>${n}</option>`).join('')}</select></label><label>タグ<select id="figure-tag-filter"><option value="ALL">すべて</option>${catalog.tags.map(t=>`<option value="${t.id}" ${tag===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label></div><div class="filters">${['ALL','R','SR','SSR','UR','MOB'].map(r=>`<button data-filter="${r}" class="${rarity===r?'selected':''}">${r}</button>`).join('')}</div><button class="favorite-filter" data-figure-favorites aria-pressed="${favoritesOnly}">★ お気に入りだけ</button><p data-figure-count>${rows.length} FIGURES</p><div class="soul-grid">${rows.map(f=>`<article class="soul-card collection-card"><button class="figure-favorite" data-figure-favorite="${f.id}" aria-pressed="${isFavorite(c.profile,f.id)}" aria-label="${esc(f.name)}のお気に入り${isFavorite(c.profile,f.id)?'解除':'登録'}">${isFavorite(c.profile,f.id)?'★':'☆'}</button><button data-figure-info="${f.id}" aria-label="${esc(f.name)}の性能"><small>${f.rarity} · ${f.attribute}</small>${c.art(c.byId.get(f.id))}<b>${esc(f.name)}</b></button><small>${esc(acquisitionText(f.id))}</small><small>${classNames[f.soulClass]} · 所持 ${c.profile.owned[f.id]||0}</small><p>ATK <b>${f.atk}</b> / DEF <b>${f.def}</b></p><button data-center="${f.id}" ${(c.profile.owned[f.id]||0)<1?'disabled':''}>展示する</button></article>`).join('')||'<p class="figure-empty">該当するフィギュアがありません。検索やタグ、お気に入りの条件を変えてください。</p>'}</div><div class="collection-rewards"></div></section>`;
}

function deckInventory(c,selected,filters,counts){
 const rows=[...soulFigures,...(catalog.archivedFigures||[])].filter(f=>(selected==='all'||f.soulClass===selected)&&(!filters.rarity||filters.rarity==='ALL'||f.rarity===filters.rarity)&&(c.profile.owned[f.id]||0)>0&&(!filters.tag||filters.tag==='ALL'||f.tags.includes(filters.tag))&&[f.name,f.id,...f.tags.map(tagName)].join(' ').normalize('NFKC').toLowerCase().includes((filters.query||'').normalize('NFKC').toLowerCase()));
 return rows.map(f=>{const status=soulDeckAddStatus(c.profile,f.id),reason=status.reasons.join(' / '),note='deck-reason-'+f.id;return `<article class="soul-card"><button ${f.soulClass==='seed'?'data-figure-info':'data-soul-recommend'}="${f.id}"><small>${f.rarity} · ${f.attribute}</small>${c.art(c.byId.get(f.id))}<b>${esc(f.name)}</b></button>${stageBadge(f)}${f.soulClass!=='seed'&&!f.retired?'<small class="recommend-hint">タップでおすすめシードを見る</small>':''}<p>ATK ${f.atk} / DEF ${f.def}</p><small>編成 ${counts[f.id]||0} / 所持 ${c.profile.owned[f.id]}</small><button data-soul-add="${f.id}" aria-describedby="${note}" ${status.allowed?'':'disabled'}>＋ 編成</button><small id="${note}" class="deck-add-reason">${esc(reason||'追加できます')}</small></article>`;}).join('')||'<p>現在の階級・検索・タグに一致する所持フィギュアがありません。「全階級・絞り込み解除」で確認できます。</p>';
}
export function deckScreen(c,filters={}){return deckWorkshopScreen(c,filters,deckInventory,deckAssistMarkup);}
export function battleScreen(c){const check=validateSoulDeck(ensureSoulDecks(c.profile),c.profile.owned,{profile:c.profile}),hero=c.byId.get(c.profile.centerId)||c.byId.get(ensureSoulDecks(c.profile)[0]);return `<section class="battle-hub"><header><h1>対戦</h1><p>お気に入りのデッキで、次の一戦へ。</p></header><div class="battle-hub-hero" style="--versus-art:url('${new URL(publicAsset('assets/towers/layers/versus-arena-retro-oct09.png'),document.baseURI).href}')"><h2>小さな仲間と、<br>大きな勝負。</h2><p>3つの枠から、<br>逆転のフュージョン。</p>${hero?`<img src="${esc(hero.image)}" alt="" draggable="false">`:''}</div><button class="tower-entry" data-go="tower"><div><small>冒険を進める</small>モブタワーマスターへの道</div><span>↗</span></button><div class="battle-ready"><span>デッキ ${check.count}/45 · ${check.valid?'準備完了':'編成中'}</span><button data-go="deck">デッキを編集</button></div><h2>CPUと対戦</h2><div class="soul-mode-grid">${['easy','normal','hard'].map((d,i)=>`<button data-battle-start="free:${d}" ${!check.valid?'disabled':''}><b>${['初級','中級','上級'][i]}</b><span>${['基本を試そう','腕試しをしよう','強敵に挑もう'][i]}</span></button>`).join('')}</div><div class="battle-other-modes"><button data-battle-start="random" ${!check.valid?'disabled':''}>ランダムマッチ</button><button data-go="tournament">大会・リーグ</button></div><details class="soul-rules"><summary>対戦ルールを見る</summary><p>場は最大3体。手札は5体まで補充し、必要なドローができなければ敗北。初期ライフは400。ATKとDEFの差がライフダメージになります。</p><p>専用融合はシード2体からミドル、ミドル2体からMOBへ。強化は同名+30、タグ+20、属性+15、両方一致+25。各個体1回だけ。素材は場同士か手札と場です。</p><p>スキルは各個体1ターン1回。戦闘中の上限はシード1回・ミドル2回・MOB3回です。バトルへ進むと通常スキル・融合・召喚は終了します。</p></details></section>`;}
