import {towerStarters} from '../data/tower.js';
import {isFavorite} from '../game/favorites.js';
import {freeEnemies} from '../game/free-enemies.js';
import {acquisitionText} from '../game/acquisition.js';
import {familyIds,familyCollectionMarkup} from '../game/family-collection.js';
import {elementIds,elementCollectionMarkup} from '../game/element-collection.js';
import {release} from '../game/initial-release.js';
import {pieceStarters} from '../game/piece-starters.js';
import {deckAssistMarkup} from './soulDeckAssist.js';
import {soulStarters} from '../game/soul-starters.js';
import {testSettings} from '../data/test-settings.js';
import {availableDeckOwned,soulCopyLimits} from '../game/deck-legality.js';
import {soulFigures,soulById,classNames,quotas,validateSoulDeck,ensureSoulDecks,soulDeckAddStatus} from '../game/soul-battle.js';
import catalog from '../data/soul-catalog.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tagName=id=>catalog.tags.find(t=>t.id===id)?.name||id;
const timing=f=>f.soulSkill.timingLabel;
export function soulInfo(f){const s=soulById.get(f.sourceId||f.id);if(!s)return '<p>原典照合待ち</p>';return `<div class="soul-chips"><b>${classNames[s.soulClass]}</b><b>${s.attribute}属性</b><b>${s.rarity}</b></div><div class="soul-stats"><span>ATK <b>${s.atk}</b></span><span>DEF <b>${s.def}</b></span></div><p>入手：${esc(acquisitionText(s.id))}</p><h3>${esc(s.soulSkill.name)}</h3><small>${timing(s)} · 各個体1ターン1回・対戦中シード1／ミドル2／MOB3回（常時効果を除く）</small><p>${esc(s.soulSkill.description)}</p><div class="soul-tags">${s.tags.map(t=>`<span>${esc(tagName(t))}</span>`).join('')}</div><details><summary>フュージョン条件・原典を見る</summary><p>${(s.fusionMaterials||[]).map(r=>`${r.special?'MOB SOUL FUSION · ATK/DEF +20':classNames[r.fromClass]}：${esc(r.label)}`).join('<br>')||'手札から直接召喚'}</p><p>フュージョン先：${s.fusionTargets.map(id=>esc(soulById.get(id).name)).join(' / ')||'なし'}</p><p>原典：${esc(s.source.soul?.text||s.source.traitText)}<br>${esc(s.source.statsText)}</p><p>${esc(s.source.decision)}</p></details>`;}
const head=(title,sub)=>`<div class="page-heading"><span class="eyebrow">MOB PIECE BATTLE · SOUL FUSION</span><h1>${title}</h1><p>${sub}</p></div>`;
const rank={R:1,SR:2,SSR:3,UR:4,MOB:5};
export function collectionScreen(c,query='',rarity='ALL',status='ALL',sort='DEX_ASC',tag='ALL',group='main',favoritesOnly=false){
 const rows=soulFigures.filter(f=>(!favoritesOnly||isFavorite(c.profile,f.id))&&(group==='ALL'||f.collection===group)&&(rarity==='ALL'||f.rarity===rarity)&&(tag==='ALL'||f.tags.includes(tag))&&(status==='ALL'||(status==='OWNED')===((c.profile.owned[f.id]||0)>0))&&([f.name,f.id,...f.tags.map(tagName)].join(' ').normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').toLowerCase())));
 rows.sort(({id:a}, {id:b})=>{const x=soulById.get(a),y=soulById.get(b);return ({RARITY_DESC:()=>rank[y.rarity]-rank[x.rarity],ATTRIBUTE:()=>x.attribute.localeCompare(y.attribute,'ja'),TAG:()=>x.tags.map(tagName).join().localeCompare(y.tags.map(tagName).join(),'ja'),ATK_DESC:()=>y.atk-x.atk,DEF_DESC:()=>y.def-x.def,NAME_ASC:()=>x.name.localeCompare(y.name,'ja')}[sort]||(()=>0))()||a.localeCompare(b);});
 return `<section class="library soul-library">${head('FIGURE',`編集できるスターター2デッキで出発。全${soulFigures.length}体のソウル。`)}<a class="soul-link" href="./figure-catalog.html" target="_blank" rel="noopener">全性能・原典・レシピのHTML一覧 ↗</a><label>コレクション<select id="figure-collection">${[["main","メイン（初期・追加）"],["collab","コラボ（MOB STORYほか）"],["ALL","すべて"]].map(([id,name])=>`<option value="${id}" ${group===id?"selected":""}>${name}</option>`).join("")}</select></label><label class="search-label">フィギュア検索<input id="figure-search" value="${esc(query)}" placeholder="名前・ID・タグで検索"></label><div class="dex-controls"><label>並び順<select id="figure-sort">${[['DEX_ASC','ID順'],['RARITY_DESC','レア度順'],['ATTRIBUTE','属性順'],['TAG','タグ順'],['ATK_DESC','ATK順'],['DEF_DESC','DEF順'],['NAME_ASC','名前順']].map(([id,n])=>`<option value="${id}" ${sort===id?'selected':''}>${n}</option>`).join('')}</select></label><label>タグ<select id="figure-tag-filter"><option value="ALL">すべて</option>${catalog.tags.map(t=>`<option value="${t.id}" ${tag===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label></div><div class="filters">${['ALL','R','SR','SSR','UR','MOB'].map(r=>`<button data-filter="${r}" class="${rarity===r?'selected':''}">${r}</button>`).join('')}</div><button class="favorite-filter" data-figure-favorites aria-pressed="${favoritesOnly}">★ お気に入りだけ</button><p data-figure-count>${rows.length} FIGURES</p><div class="soul-grid">${rows.map(f=>`<article class="soul-card collection-card"><button class="figure-favorite" data-figure-favorite="${f.id}" aria-pressed="${isFavorite(c.profile,f.id)}" aria-label="${esc(f.name)}のお気に入り${isFavorite(c.profile,f.id)?'解除':'登録'}">${isFavorite(c.profile,f.id)?'★':'☆'}</button><button data-figure-info="${f.id}" aria-label="${esc(f.name)}の性能"><small>${f.rarity} · ${f.attribute}</small>${c.art(c.byId.get(f.id))}<b>${esc(f.name)}</b></button><small>${esc(acquisitionText(f.id))}</small><small>${classNames[f.soulClass]} · 所持 ${c.profile.owned[f.id]||0}</small><p>ATK <b>${f.atk}</b> / DEF <b>${f.def}</b></p><button data-center="${f.id}" ${(c.profile.owned[f.id]||0)<1?'disabled':''}>展示する</button></article>`).join('')||'<p class="figure-empty">該当するフィギュアがありません。検索やタグ、お気に入りの条件を変えてください。</p>'}</div><div class="collection-rewards"></div></section>`;
}

function deckInventory(c,selected,filters,counts){
 const rows=[...soulFigures,...(catalog.archivedFigures||[])].filter(f=>(selected==='all'||f.soulClass===selected)&&(c.profile.owned[f.id]||0)>0&&(!filters.tag||filters.tag==='ALL'||f.tags.includes(filters.tag))&&[f.name,f.id,...f.tags.map(tagName)].join(' ').normalize('NFKC').toLowerCase().includes((filters.query||'').normalize('NFKC').toLowerCase()));
 return rows.map(f=>{const status=soulDeckAddStatus(c.profile,f.id),reason=status.reasons.join(' / '),note='deck-reason-'+f.id;return `<article class="soul-card"><button ${f.soulClass==='seed'?'data-figure-info':'data-soul-recommend'}="${f.id}"><small>${f.rarity} · ${f.attribute}</small>${c.art(c.byId.get(f.id))}<b>${esc(f.name)}</b></button><small>${classNames[f.soulClass]}</small>${f.soulClass!=='seed'&&!f.retired?'<small class="recommend-hint">タップでおすすめシードを見る</small>':''}<p>ATK ${f.atk} / DEF ${f.def}</p><small>編成 ${counts[f.id]||0} / 所持 ${c.profile.owned[f.id]}</small><button data-soul-add="${f.id}" aria-describedby="${note}" ${status.allowed?'':'disabled'}>＋ 編成</button><small id="${note}" class="deck-add-reason">${esc(reason||'追加できます')}</small></article>`;}).join('')||'<p>現在の階級・検索・タグに一致する所持フィギュアがありません。「全階級・絞り込み解除」で確認できます。</p>';
}
export function deckScreen(c,filters={}){const ids=ensureSoulDecks(c.profile),v=validateSoulDeck(ids,c.profile.owned,{profile:c.profile}),selected=['seed','middle','mob','all'].includes(c.profile.soulDeckFilter)?c.profile.soulDeckFilter:'seed';const counts=Object.fromEntries(ids.map(id=>[id,ids.filter(x=>x===id).length]));return `<section class="library soul-library">${head('SOUL DECK','合計45体・段階の配分は自由（シード45体もOK）')}<div class="soul-slots">${Array.from({length:5},(_,i)=>`<button data-soul-slot="${i}" class="${c.profile.soulDeckSlot===i?'selected':''}">DECK ${i+1}</button>`).join('')}</div><div class="soul-deck-count"><b>${ids.length} / 45</b><span>${v.valid?'READY TO BATTLE':'編成中'}<br>通常ドローはシードのみ</span></div><div class="soul-actions"><button data-soul-auto>おまかせ編成</button><button data-soul-clear>編成を空にする</button></div><p class="notice">${v.errors.join(' / ')||'所持数の範囲で編成できます。山札は対戦開始時にシャッフルされます。同じIDはシード3体、ミドル・MOB各1体まで。DECK 1と2では同じIDを共有できません。'}</p><section class="test-figure-tool"><b>初期スターターテンプレート</b><p>所持数が揃ったデッキをセットできます。選択中のスロットだけを置き換え、所持品は増えません。</p><div class="soul-actions">${towerStarters.map(t=>`<button data-piece-starter="${t.id}">${t.name}をセット</button>`).join('')}</div></section>${deckAssistMarkup()}<div class="soul-tabs"><button data-soul-filter="all" class="${selected==='all'?'selected':''}">全階級<b>${ids.length} / 45</b></button>${Object.entries(quotas).map(([k,n])=>`<button data-soul-filter="${k}" class="${selected===k?'selected':''}">${classNames[k]}<b>${v.counts[k]}体</b></button>`).join('')}</div><div class="soul-selected">${ids.map((id,i)=>({f:soulById.get(id),i})).filter(({f})=>selected==='all'||!f||f.soulClass===selected).map(({f,i})=>f?.retired?`<button data-soul-remove="${i}">BATTLE対象外 · ${esc(f.name)} · 外す</button>`:!f?`<button data-soul-remove="${i}">未対応の旧ID · 外す</button>`:`<div class="soul-selected-piece"><button ${f.soulClass==='seed'?'data-figure-info':'data-soul-recommend'}="${f.id}" aria-label="${esc(f.name)}${f.soulClass==='seed'?'の性能':'のおすすめシード'}">${c.art(c.byId.get(f.id))}<span>${esc(f.name)}</span></button><button data-soul-remove="${i}" aria-label="${esc(f.name)}を編成から外す">− 外す</button></div>`).join('')||'<p>この領域にはまだ編成されていません。</p>'}</div><h2>所持フィギュアから追加</h2><button data-deck-reset-filters>全階級・絞り込み解除</button><label class="search-label">名前・ID・タグ検索<input type="search" id="deck-search" value="${esc(filters.query||'')}" placeholder="名前・ID・タグ" autocomplete="off"></label><label>タグで絞り込み<select id="deck-tag-filter"><option value="ALL">すべてのタグ</option>${catalog.tags.map(t=>`<option value="${t.id}" ${filters.tag===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><div class="soul-grid" id="deck-inventory">${deckInventory(c,selected,filters,counts)}</div></section>`;}
export function battleScreen(c){const check=validateSoulDeck(ensureSoulDecks(c.profile),c.profile.owned,{profile:c.profile});return `<section class="library soul-library">${head('SOUL BATTLE','3つの枠から、逆転のフュージョン。')}<button class="tower-entry" data-go="tower"><div><small>STORY</small>モブタワーマスターへの道</div><span>↗</span></button><div class="soul-rules-banner"><b>400 LIFE</b><span>ATK vs DEF<br>差分がライフダメージ</span></div><p>デッキ ${check.count}/45 · ${check.valid?'準備完了':'編成を完成させてください'}</p><button class="simple-cta" data-go="deck">デッキを編集 →</button><div class="soul-mode-grid">${freeEnemies.map(e=>`<button data-battle-start="free:normal:${e.id}" ${!check.valid?'disabled':''}><small>THEME FREE BATTLE</small><b>${esc(e.name)}</b><span>${esc(e.description)}</span><small>${esc(e.supportSummary||'')}</small></button>`).join('')}${['easy','normal','hard'].map((d,i)=>`<button data-battle-start="free:${d}" ${!check.valid?'disabled':''}><small>CPU FREE BATTLE</small><b>${['EASY','NORMAL','HARD'][i]}</b><span>手動ターンバトル →</span></button>`).join('')}<button data-battle-start="random" ${!check.valid?'disabled':''}>ランダムマッチ</button><button data-go="tournament">大会・リーグへ →</button></div><details class="soul-rules" open><summary>新ルール</summary><p>場は最大3体。空き枠があれば何度でも召喚できます。手札を5体へ補充し、引けなくなったら敗北。直接攻撃はありません。</p><p>専用融合：シード2体 → ミドル1体 → ミドル2体 → MOBソウル1体。強化召喚：属性かタグ一致で各+15、両方一致または同一IDで各+30。残す個体を選び、段階は維持します。別IDでは残スキル回数を引き継ぎ、同一IDではリセットします。レシピと専用領域のフィギュアが必要です。素材は場×場、手札×場。手札×手札はできません。</p><p>スキルは各個体1ターン1回。対戦中の上限はシード1回・ミドル2回・MOB3回で、常時効果は回数を消費しません。使用者はそのターン素材にできません。対応型は攻撃宣言時・相手スキル発動時・撃破時に使用できます。バトルへ進むと通常スキル・フュージョン・召喚は終了です。クフレイは使用後も素材にできる例外です。</p></details></section>`;}
