import {soulFigures,soulById,classNames,validateSoulDeck,ensureSoulDecks,autoSoulDeck,createSoulBattle,summon,fusionOptions,fuse,canSkill,useSkill,beginBattle,attack,endTurn,cpuMain,cpuAttack,stats} from '../game/soul-battle.js';
import {esc} from './soulLibrary.js';
export async function launchBattle({profile,request,onResolved}){
 const deck=ensureSoulDecks(profile),check=validateSoulDeck(deck,profile.owned);if(!check.valid)throw Error(check.errors[0]||'45体（シード30・ミドル10・MOB5）のデッキを完成させてください');
 const strength=request.difficulty==='easy'?1:request.difficulty==='hard'?3:2;
 const cpuOwned=Object.fromEntries(soulFigures.map(f=>[f.id,(strength===1?['R','SR']:strength===2?['R','SR','SSR','UR']:['R','SR','SSR','UR','MOB']).includes(f.rarity)?5:0]));
 const state=createSoulBattle([deck,autoSoulDeck(cpuOwned)],['PLAYER',request.opponentName||'CPU']);
 const dialog=document.createElement('dialog');dialog.className='soul-battle-dialog';document.body.append(dialog);dialog.showModal();let selected=null,materials=[],targetMode=null,error='',settled=false,meta=null;
 const asset=f=>`<img src="${new URL(f.image,document.baseURI).href}" alt="${esc(f.name)}">`;
 function field(side){return `<div class="soul-field">${state.players[side].field.map((p,i)=>{if(!p)return `<div class="soul-empty">${i+1}<small>EMPTY</small></div>`;const f=soulById.get(p.id),s=stats(p);return `<button data-piece="${p.uid}" data-side="${side}" class="soul-piece ${selected===p.uid||materials.includes(p.uid)?'selected':''}"><small>${f.rarity} · ${f.attribute}</small>${asset(f)}<b>${esc(f.name)}</b><span>ATK ${s.atk} / DEF ${s.def}</span><em>${p.skillTurn===state.turn?'素材不可':classNames[f.soulClass]}</em><em>${p.attacks?'攻撃 '+p.attacks+'/'+(1+p.extra):''}</em></button>`;}).join('')}</div>`;}
 function render(){
 const p=state.players[0],cpu=state.players[1],own=state.active===0,main=state.phase==='main',chosen=p.field.find(f=>f?.uid===selected),opts=fusionOptions(state,0,materials);
 dialog.innerHTML=`<section class="soul-arena"><header><div><small>SOUL FUSION</small><b>${esc(request.title||'SOUL BATTLE')}</b></div><button data-quit>退出</button></header><div class="soul-turn"><b>TURN ${state.turn}</b><span>${own?'あなた':'相手'} · ${main?'メイン':state.phase==='finished'?'終了':'バトル'}</span></div><div class="soul-life enemy"><span>${esc(cpu.name)} <small>山札 ${cpu.deck.length} · 手札 ${cpu.hand.length}</small></span><b>${cpu.life}<small>/400</small></b><meter max="400" value="${cpu.life}"></meter></div>${field(1)}<div class="soul-versus">${state.winner!==null?(state.winner===0?'VICTORY':'DEFEAT'):targetMode?'相手フィギュアを選択':own?'YOUR MOVE':'OPPONENT TURN'}</div>${field(0)}<div class="soul-life"><span>PLAYER <small>山札 ${p.deck.length} · 墓地 ${p.grave.length}</small></span><b>${p.life}<small>/400</small></b><meter max="400" value="${p.life}"></meter></div><div class="soul-command"><p role="status">${esc(error||state.log.at(-1))}</p>${state.winner!==null?`<h2>${esc(state.reason)}</h2><p>${esc(meta?.message||'対戦終了')}</p><button data-close-result>戻る</button>`:`<p class="soul-skill-budget">あなたのスキル：${p.skillUsed?'使用済み':'残り1回'} / 相手：${cpu.skillUsed?'使用済み':'残り1回'}</p>${chosen?`<div class="soul-active-info"><b>${esc(soulById.get(chosen.id).soulSkill.name)}</b><p>${esc(soulById.get(chosen.id).soulSkill.description)}</p></div>`:''}<div class="soul-actions"><button data-skill ${!chosen||!canSkill(state,0,chosen.uid)?'disabled':''}>ソウルスキル</button>${own&&main?`<button data-material ${!chosen||chosen.skillTurn===state.turn?'disabled':''}>${materials.includes(selected)?'素材から外す':'素材に選ぶ'}</button><button data-phase>バトルへ →</button>`:own?'<button data-end>ターン終了 →</button>':main?'<button data-cpu-phase>CPUバトルへ →</button>':'<button data-cpu-step>次のCPU攻撃 →</button>'}</div>${!own&&main?'<p>相手メイン中です。対応スキルを使う場合は、自分の駒を選択してください。</p>':''}${own&&main?`<div class="soul-fusion-options">${materials.length===2?(opts.length?opts.filter((r,i,a)=>a.findIndex(x=>x.target===r.target)===i).map(r=>`<button data-fuse="${r.id}">融合 → ${esc(soulById.get(r.target).name)}<small>${esc(r.label)}</small></button>`).join(''):'<p>この素材で召喚できるフィギュアは専用領域にありません。</p>'):'<p>融合する駒を2体、素材に選んでください。</p>'}</div>`:''}<div class="soul-hand">${p.hand.map((id,i)=>{const f=soulById.get(id);return `<button data-summon="${i}" ${!own||!main||!p.field.includes(null)?'disabled':''}>${asset(f)}<b>${esc(f.name)}</b><span>${f.atk} / ${f.def}</span></button>`;}).join('')}</div><details><summary>専用領域 · ${p.reserve.length}体</summary><div class="soul-reserve">${p.reserve.map(id=>`<span>${esc(soulById.get(id).name)} / ${classNames[soulById.get(id).soulClass]}</span>`).join('')}</div></details>`}</div><details class="soul-log"><summary>対戦ログ</summary>${state.log.slice(-30).map(t=>`<p>${esc(t)}</p>`).join('')}</details></section>`;
 }
 const result=()=>({won:state.winner===0,battleFor:state.winner===0?1:0,battleAgainst:state.winner===1?1:0,match:{ruleset:'soul-v1',playerDeckOriginal:deck,cpuDeckOriginal:state.players[1].original,history:[{pHand:state.players[0].used,cHand:state.players[1].used,won:state.winner===0}],life:state.players.map(p=>p.life),reason:state.reason},soulState:state});
 async function settle(){if(state.winner!==null&&!settled){settled=true;meta=await onResolved?.(result());}}
 render();return new Promise(resolve=>{
 const close=value=>{dialog.close();dialog.remove();resolve(value);};
 dialog.addEventListener('cancel',e=>{e.preventDefault();showQuit();});
 function showQuit(){const box=document.createElement('div');box.className='soul-quit';box.innerHTML='<section><h2>対戦を終了しますか？</h2><p>この対戦は敗北として記録されます。</p><button data-stay>戻る</button><button data-forfeit>降参する</button></section>';dialog.append(box);box.querySelector('[data-stay]').onclick=()=>box.remove();box.querySelector('[data-forfeit]').onclick=async()=>{state.winner=1;state.reason='降参';state.phase='finished';await settle();render();};}
 dialog.onclick=async e=>{const b=e.target.closest('button');if(!b)return;error='';try{
  if(b.hasAttribute('data-quit')){if(settled)close(result());else showQuit();return;}
  if(b.hasAttribute('data-close-result')){close(result());return;}
  if(b.hasAttribute('data-summon')){summon(state,0,Number(b.dataset.summon),state.players[0].field.indexOf(null));targetMode=null;}
  if(b.hasAttribute('data-piece')){const uid=Number(b.dataset.piece),side=Number(b.dataset.side);if(side===0){selected=uid;targetMode=state.phase==='battle'&&state.active===0?'attack':null;}else if(targetMode==='skill'){useSkill(state,0,selected,uid);targetMode=null;}else if(targetMode==='attack'){attack(state,0,selected,uid);targetMode=null;}}
  if(b.hasAttribute('data-material')){materials=materials.includes(selected)?materials.filter(x=>x!==selected):[...materials.slice(-1),selected];}
  if(b.hasAttribute('data-fuse')){fuse(state,0,materials,b.dataset.fuse);materials=[];selected=null;}
  if(b.hasAttribute('data-skill')){const f=state.players[0].field.find(f=>f?.uid===selected);if(soulById.get(f.id).soulSkill.effects.some(e=>e.target==='enemy'))targetMode='skill';else useSkill(state,0,selected);}
  if(b.hasAttribute('data-phase')){beginBattle(state,0);targetMode=selected?'attack':null;materials=[];}
  if(b.hasAttribute('data-end')){endTurn(state,0);selected=null;targetMode=null;if(state.winner===null)cpuMain(state);}
  if(b.hasAttribute('data-cpu-phase'))beginBattle(state,1);
  if(b.hasAttribute('data-cpu-step')){cpuAttack(state);selected=null;targetMode=null;}
  await settle();
 }catch(err){error=err.message;}render();};
 });
}
