import {grassTower} from '../data/tower.js';
import {towerState,towerDeckOptions,prepareTowerStart,prepareTowerResult,towerMatchRequest,prepareTowerThirdDeck,prepareTowerAbandon} from '../game/tower.js';
import {launchBattle} from './soulDuelRuntime.js';
import {commitProfile,saveProfile} from '../game/profile.js?v=7.3.0';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let floor=null,keys=[],order=[0,1,2,0,1],abandon=false,locked=false;
window.addEventListener('hashchange',()=>{floor=null;abandon=false;});
const score=a=>{const w=a.results.filter(Boolean).length;return `${w} <span>−</span> ${a.results.length-w}`;};
const options=(ctx,key)=>towerDeckOptions(ctx.profile).map(o=>`<option value="${o.key}" ${o.key===key?'selected':''} ${o.check.valid?'':'disabled'}>${esc(o.name)}${o.check.valid?' · 45枚':' · 要編集'}</option>`).join('');
export function towerScreen(ctx){
 const t=towerState(ctx.profile),a=t.active,last=t.last;
 const top=`<header class="tower-heading"><button data-go="home" aria-label="ホームに戻る">‹</button><div><small>ROAD TO TOWER MASTER</small><h1>${grassTower.title}</h1></div><button data-go="shop" aria-label="ショップ">SHOP</button></header>`;
 let content='';
 if(a){content=`<section class="tower-series"><small>${a.floor}F · RANK ${a.rank} · ${a.need}勝先取</small><h2>${esc(a.opponent)}</h2><div class="tower-score" aria-label="現在の勝敗">${score(a)}</div><p>あなた <span>対</span> マスター</p><div class="tower-match-track">${a.assignment.map((d,i)=>`<div class="${i<a.results.length?(a.results[i]?'won':'lost'):i===a.results.length?'current':''}"><small>第${i+1}戦</small><b>${a.floor===5?'ABC'[d]:'◆'}</b><span>${i<a.results.length?(a.results[i]?'WIN':'LOSE'):i===a.results.length?'NEXT':'待機'}</span></div>`).join('')}</div><p class="tower-note">編成と割当は開始時の内容で固定されています。<br>中断した試合は最初から再開できます。勝敗記録は保持されます。</p><div class="tower-dock"><button class="tower-primary" data-tower-play>第${a.results.length+1}戦へ · ${esc(a.decks[a.assignment[a.results.length]].name)}</button><button data-tower-abandon>この連戦をやり直す</button></div></section>`;}
 else content=`${last?`<div class="tower-last ${last.won?'won':''}" role="status"><b>${last.won?'FLOOR CLEAR!':'次はきっと、もっと先へ。'}</b><span>${last.floor}F · ${last.wins} − ${last.losses}</span>${last.reward?`<small>初回報酬 ${last.reward.coins} COIN / ${last.reward.diamonds} MOB · 保存済み</small>`:''}${last.unlockedBanners?'<button data-go="gacha">新しい混合ガチャ2つが開放！ →</button>':''}</div>`:''}<div class="tower-landscape" ${grassTower.background?`style="--tower-background:url('${esc(grassTower.background)}')"`:''}><div class="tower-cloud one"></div><div class="tower-cloud two"></div><div class="tower-hill"></div><div class="tower-building" aria-label="草原の塔・全5階"><div class="tower-roof"></div>${[...grassTower.floors].reverse().map(f=>{const done=t.cleared.includes(f.id),open=f.id===1||t.cleared.includes(f.id-1);return `<button class="tower-floor ${done?'cleared':''} ${open?'open':'locked'}" data-tower-floor="${f.id}" ${open?'':'disabled'} aria-label="${f.id}階 ${f.name} ${done?'クリア済み':open?'挑戦可能':'未開放'}"><span class="tower-floor-number">${f.id}<small>F</small></span><span><b>${f.name}</b><small>${f.id===5?'3デッキ・3勝先取':'2勝先取'} · RANK ${f.rank}</small></span><i>${done?'✓':open?'›':'🔒'}</i></button>`;}).join('')}<div class="tower-foundation"><span>GRASSLAND</span></div></div><img class="tower-guide" src="${esc(ctx.byId.get(grassTower.masterId)?.image)}" alt="草原の案内役"></div><div class="tower-map-caption"><h2>草原の塔</h2><p>${t.cleared.includes(5)?'草原制覇！ 次の地域は準備中です。':'階をタップして挑戦。ひとつずつ、頂上へ。'}</p></div><div class="tower-links"><button data-go="deck">デッキを編集</button><button data-tower-third>3つ目の編成を作る</button></div><p class="tower-note">支給された2デッキは自由に編集できます。<br>5Fでは既存の編成や「組み替えC」も選べます。</p>`;
 const setup=floor?setupMarkup(ctx):'';
 return `<section class="tower-page">${top}${content}${setup}${abandon?`<div class="tower-modal" role="dialog" aria-modal="true" aria-label="連戦のやり直し"><div class="tower-sheet"><h2>この連戦をやり直す？</h2><p>現在の連戦スコアをリセットします。所持品とクリア済みの階は変わりません。</p><button data-tower-abandon-confirm>はい、やり直す</button><button data-tower-cancel>戻る</button></div></div>`:''}</section>`;
}
function setupMarkup(ctx){const f=grassTower.floors.find(f=>f.id===floor),boss=floor===5;const count=i=>order.filter(x=>x===i).length;const legal=keys.length===(boss?3:1)&&new Set(keys).size===keys.length&&keys.every(k=>towerDeckOptions(ctx.profile).some(o=>o.key===k&&o.check.valid))&&(!boss||[0,1,2].every(i=>count(i)<=2));return `<div class="tower-modal" role="dialog" aria-modal="true" aria-label="${floor}階への挑戦"><section class="tower-sheet ${boss?'boss':''}"><header><div><small>${floor}F · RANK ${f.rank}</small><h2>${f.name}</h2></div><button data-tower-cancel aria-label="閉じる">×</button></header>${boss?`<div class="tower-dialogue"><img src="${esc(ctx.byId.get(grassTower.masterId)?.image)}" alt="草原マスター"><p>${esc(f.dialogue)}</p></div>`:`<p>${esc(f.opponent)}と最大3戦。先に2勝でクリア！</p>`}<div class="tower-deck-choices">${keys.map((k,i)=>`<label><b>${boss?'ABC'[i]:'使用デッキ'}</b><select data-tower-deck="${i}" aria-label="デッキ${boss?'ABC'[i]:'選択'}">${options(ctx,k)}</select></label>`).join('')}</div>${boss?`<p class="tower-limit">5戦の割当 · 各デッキ2回まで <b>${[0,1,2].map(i=>'ABC'[i]+' '+count(i)+'/2').join('　')}</b></p><div class="tower-assignment">${order.map((d,i)=>`<div><strong>第${i+1}戦</strong><div>${[0,1,2].map(n=>`<button data-tower-assign="${i}:${n}" aria-label="第${i+1}戦 デッキ${'ABC'[n]}" aria-pressed="${d===n}" ${d!==n&&count(n)>=2?'disabled':''}>${'ABC'[n]}</button>`).join('')}</div></div>`).join('')}</div><p class="tower-note">先に3勝した時点で終了。開始後の変更はできません。</p>`:''}<footer class="tower-confirm"><button data-tower-cancel>いいえ</button><button class="tower-primary" data-tower-start ${legal?'':'disabled'}>${boss?'この割当で挑戦':'はい、挑戦する'}</button></footer></section></div>`;}
function commit(next){if(!commitProfile(next))throw Error('保存できませんでした。操作は確定していません。');}
export function handleTowerChange(el,ctx,{render}){if(!el.hasAttribute('data-tower-deck'))return false;keys[Number(el.dataset.towerDeck)]=el.value;render();return true;}
export async function handleTower(button,ctx,{render,toast}){
 if(![...button.attributes].some(a=>a.name.startsWith('data-tower-')))return false;if(locked)return true;
 try{
 if(button.dataset.towerFloor){floor=Number(button.dataset.towerFloor);const valid=towerDeckOptions(ctx.profile).filter(o=>o.check.valid);keys=floor===5?[valid[0]?.key,valid.find(o=>o.key!==valid[0]?.key&&JSON.stringify(o.deck)!==JSON.stringify(valid[0]?.deck))?.key,'starter:mix']:[(valid.find(o=>o.key==='slot:'+ctx.profile.soulDeckSlot)||valid[0])?.key];order=[0,1,2,0,1];render();}
 else if(button.hasAttribute('data-tower-cancel')){floor=null;abandon=false;render();}
 else if(button.dataset.towerAssign){const [i,n]=button.dataset.towerAssign.split(':').map(Number);order[i]=n;render();}
 else if(button.hasAttribute('data-tower-third')){commit(prepareTowerThirdDeck(ctx.profile));location.hash='deck';toast('支給カードを組み替えました。自由に編集できます。');}
 else if(button.hasAttribute('data-tower-abandon')){abandon=true;render();}
 else if(button.hasAttribute('data-tower-abandon-confirm')){commit(prepareTowerAbandon(ctx.profile));abandon=false;render();}
 else if(button.hasAttribute('data-tower-start')){commit(prepareTowerStart(ctx.profile,floor,keys,order));floor=null;render();}
 else if(button.hasAttribute('data-tower-play')){
 locked=true;const request=towerMatchRequest(ctx.profile);
 await launchBattle({profile:ctx.profile,request,saveProfile,onResolved:result=>{const out=prepareTowerResult(ctx.profile,request.towerToken,result.won);commit(out.next);return {message:out.message,reward:out.reward};}});render();
 }
 }catch(e){toast(e.message,'error');}finally{locked=false;}return true;
}
