import {campaignOpponent} from '../data/tower-campaign.js';
import {sound} from '../audio/audio.js';
import {campaignView as towerState,currentCampaignTower,prepareCampaignStart as prepareTowerStart,prepareCampaignResult as prepareTowerResult,campaignMatchRequest as towerMatchRequest,prepareCampaignAbandon as prepareTowerAbandon} from '../game/tower-campaign.js';
import {towerDeckOptions,prepareTowerThirdDeck} from '../game/tower.js';
import {launchBattle} from './soulDuelRuntime.js';
import {commitProfile,saveProfile} from '../game/profile.js?v=7.3.0';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let opponentSlot=0;const seenUnlocks=new Set();
let floor=null,keys=[],order=[0,1,2,0,1],abandon=false,locked=false;
window.addEventListener('hashchange',()=>{floor=null;abandon=false;});
const score=a=>{const w=a.results.filter(Boolean).length;return `${w} <span>−</span> ${a.results.length-w}`;};
const options=(ctx,key)=>towerDeckOptions(ctx.profile).map(o=>`<option value="${o.key}" ${o.key===key?'selected':''} ${o.check.valid?'':'disabled'}>${esc(o.name)}${o.check.valid?' · 45枚':' · 要編集'}</option>`).join('');
export function towerScreen(ctx){
 const grassTower=towerDefinition(ctx),t=towerState(ctx.profile),a=t.active,last=t.last;
 const top=`<header class="tower-heading"><button data-go="home" aria-label="ホームに戻る">‹</button><div><small>ROAD TO TOWER MASTER</small><h1>${grassTower.title}</h1></div><button data-go="shop" aria-label="ショップ">SHOP</button></header>`;
 let content='';
 if(a){content=`<section class="tower-series"><small>${a.floor}F · RANK ${a.rank} · ${a.need}勝先取</small><h2>${esc(a.opponent)}</h2><div class="tower-score" aria-label="現在の勝敗">${score(a)}</div><p>あなた <span>対</span> マスター</p><div class="tower-match-track">${a.assignment.map((d,i)=>`<div class="${i<a.results.length?(a.results[i]?'won':'lost'):i===a.results.length?'current':''}"><small>第${i+1}戦</small><b>${a.floor===5?'ABC'[d]:'◆'}</b><span>${i<a.results.length?(a.results[i]?'WIN':'LOSE'):i===a.results.length?'NEXT':'待機'}</span></div>`).join('')}</div><p class="tower-note">編成と割当は開始時の内容で固定されています。<br>中断した試合は最初から再開できます。勝敗記録は保持されます。</p><div class="tower-dock"><button class="tower-primary" data-tower-play>第${a.results.length+1}戦へ · ${esc(a.decks[a.assignment[a.results.length]].name)}</button><button data-tower-abandon>この連戦をやり直す</button></div></section>`;}
 else content=campaignMap(ctx,t,grassTower);
 const setup=floor?setupMarkup(ctx):'';
 return `<section class="tower-page">${top}${content}${setup}${abandon?`<div class="tower-modal" role="dialog" aria-modal="true" aria-label="連戦のやり直し"><div class="tower-sheet"><h2>この連戦をやり直す？</h2><p>現在の連戦スコアをリセットします。所持品とクリア済みの階は変わりません。</p><button data-tower-abandon-confirm>はい、やり直す</button><button data-tower-cancel>戻る</button></div></div>`:''}</section>`;
}
function setupMarkup(ctx){const grassTower=towerDefinition(ctx),f=grassTower.floors.find(f=>f.id===floor),boss=floor===5;const count=i=>order.filter(x=>x===i).length;const legal=keys.length===(boss?3:1)&&new Set(keys).size===keys.length&&keys.every(k=>towerDeckOptions(ctx.profile).some(o=>o.key===k&&o.check.valid))&&(!boss||[0,1,2].every(i=>count(i)<=2));return `<div class="tower-modal" role="dialog" aria-modal="true" aria-label="${floor}階への挑戦"><section class="tower-sheet ${boss?'boss':''}"><header><div><small>${floor}F · RANK ${f.rank}</small><h2>${floor===5?f.name:esc(ctx.byId.get(campaignOpponent(grassTower,floor,opponentSlot))?.name)}</h2></div><button data-tower-cancel aria-label="閉じる">×</button></header>${boss?`<div class="tower-dialogue"><img src="${esc(ctx.byId.get(grassTower.masterId)?.image)}" alt="草原マスター"><p>${esc(f.dialogue)}</p></div>`:`<div class="tower-dialogue"><img src="${esc(ctx.byId.get(campaignOpponent(grassTower,floor,opponentSlot))?.image)}" alt="対戦相手"><p>${esc(grassTower.greeting)}</p></div><p>この相手と1戦。3人全員に勝つと次の階へ！</p>`}<div class="tower-deck-choices">${keys.map((k,i)=>`<label><b>${boss?'ABC'[i]:'使用デッキ'}</b><select data-tower-deck="${i}" aria-label="デッキ${boss?'ABC'[i]:'選択'}">${options(ctx,k)}</select></label>`).join('')}</div>${boss?`<p class="tower-limit">5戦の割当 · 各デッキ2回まで <b>${[0,1,2].map(i=>'ABC'[i]+' '+count(i)+'/2').join('　')}</b></p><div class="tower-assignment">${order.map((d,i)=>`<div><strong>第${i+1}戦</strong><div>${[0,1,2].map(n=>`<button data-tower-assign="${i}:${n}" aria-label="第${i+1}戦 デッキ${'ABC'[n]}" aria-pressed="${d===n}" ${d!==n&&count(n)>=2?'disabled':''}>${'ABC'[n]}</button>`).join('')}</div></div>`).join('')}</div><p class="tower-note">先に3勝した時点で終了。開始後の変更はできません。</p>`:''}<footer class="tower-confirm"><button data-tower-cancel>いいえ</button><button class="tower-primary" data-tower-start ${legal?'':'disabled'}>${boss?'この割当で挑戦':'はい、挑戦する'}</button></footer></section></div>`;}
function commit(next){if(!commitProfile(next))throw Error('保存できませんでした。操作は確定していません。');}
export function handleTowerChange(el,ctx,{render}){if(!el.hasAttribute('data-tower-deck'))return false;keys[Number(el.dataset.towerDeck)]=el.value;render();return true;}
export async function handleTower(button,ctx,{render,toast}){
 if(![...button.attributes].some(a=>a.name.startsWith('data-tower-')))return false;if(locked)return true;
 try{
 if(button.dataset.towerFloor){floor=Number(button.dataset.towerFloor);if(floor===5)sound.play('start',{sampleId:99});opponentSlot=Number(button.dataset.towerSlot||0);const valid=towerDeckOptions(ctx.profile).filter(o=>o.check.valid);keys=floor===5?[valid[0]?.key,valid.find(o=>o.key!==valid[0]?.key&&JSON.stringify(o.deck)!==JSON.stringify(valid[0]?.deck))?.key,'starter:mix']:[(valid.find(o=>o.key==='slot:'+ctx.profile.soulDeckSlot)||valid[0])?.key];order=[0,1,2,0,1];render();}
 else if(button.hasAttribute('data-tower-cancel')){floor=null;abandon=false;render();}
 else if(button.dataset.towerAssign){const [i,n]=button.dataset.towerAssign.split(':').map(Number);order[i]=n;render();}
 else if(button.hasAttribute('data-tower-third')){commit(prepareTowerThirdDeck(ctx.profile));location.hash='deck';toast('支給カードを組み替えました。自由に編集できます。');}
 else if(button.hasAttribute('data-tower-abandon')){abandon=true;render();}
 else if(button.hasAttribute('data-tower-abandon-confirm')){commit(prepareTowerAbandon(ctx.profile));abandon=false;render();}
 else if(button.hasAttribute('data-tower-start')){commit(prepareTowerStart(ctx.profile,floor,keys,order,opponentSlot));floor=null;render();}
 else if(button.hasAttribute('data-tower-play')){
 locked=true;const request=towerMatchRequest(ctx.profile);
 sound.stopAll();await launchBattle({profile:ctx.profile,request,saveProfile,onResolved:result=>{const out=prepareTowerResult(ctx.profile,request.towerToken,result.won);commit(out.next);return {message:out.message,reward:out.reward};}});render();
 }
 }catch(e){toast(e.message,'error');}finally{locked=false;}return true;
}

function towerDefinition(ctx){const t=currentCampaignTower(ctx.profile);return {...t,floors:Array.from({length:5},(_,i)=>({id:i+1,rank:i===4?t.bossRank:t.rank,name:i===4?'タワーマスター':(i+1)+'F',opponent:ctx.byId.get(campaignOpponent(t,i+1))?.name,dialogue:t.dialogue}))};}
function campaignMap(ctx,t,tower){const last=t.last,key=last?.unlock?last.towerId+':'+last.unlock:null,animate=key&&!seenUnlocks.has(key);if(key)seenUnlocks.add(key);return `${last?`<div class="tower-last ${last.won?'won':''}" role="status"><b>${last.nextTower?'次のタワーへ！':last.floorClear?'FLOOR CLEAR!':last.won?'WIN!':'もう一度、挑戦しよう。'}</b>${last.reward?`<small>初回報酬 ${last.reward.coins} COIN / ${last.reward.diamonds} MOB · 保存済み</small>`:''}${last.nextTower?`<span>${esc(last.nextTower)}</span>`:''}${last.unlockedBanners?'<button data-go="gacha">新しいガチャが開放！</button>':''}</div>`:''}<div class="campaign-sign"><h2>${esc(tower.name)}</h2><p>3人全員に勝利して、頂上へ。</p></div><div class="campaign-map" style="--region:${tower.color}"><div class="campaign-paint" aria-hidden="true"><img src="${tower.background}" alt="" draggable="false"></div><div class="campaign-floors">${[...tower.floors].reverse().map(f=>{const done=t.cleared.includes(f.id),open=f.id===1||t.cleared.includes(f.id-1),defeated=t.defeated?.[f.id]||[];return `<section class="campaign-floor ${open?'open':'locked'} ${done?'cleared':''} ${animate&&last.unlock===f.id?'just-unlocked':''}" aria-label="${f.id}階 RANK ${f.rank}"><header><strong>${f.id}F</strong><span>${f.id===5?'MASTER · ':''}RANK ${f.rank}</span><i aria-label="${open?'開放':'未開放'}">${done?'✓':open?'':'🔒'}</i></header><div class="campaign-opponents">${Array.from({length:f.id===5?1:3},(_,slot)=>{const figure=ctx.byId.get(campaignOpponent(tower,f.id,slot)),beaten=f.id===5?done:defeated.includes(slot);return `<button data-tower-floor="${f.id}" data-tower-slot="${slot}" class="${beaten?'beaten':''}" ${!open||beaten&&f.id<5?'disabled':''} aria-label="${esc(figure?.name)} · ${beaten?'勝利済み':'挑戦'}"><img src="${esc(figure?.image)}" alt="" draggable="false">${beaten?'<b aria-hidden="true">×</b>':''}${f.id===5?'<small>3デッキで挑戦</small>':''}</button>`}).join('')}</div></section>`}).join('')}</div></div><div class="tower-links campaign-links"><button data-go="deck">デッキ編成</button><button data-go="shop">ショップ</button></div><p class="tower-note">相手をタップして確認。1～4Fの順番は自由です。<br>5Fでは3デッキを5戦に割り当てます。</p><button data-tower-third>3つ目の編成を作る</button>${t.cleared.includes(5)&&tower.id==='retro'?'<p class="tower-note">次のミュージックタワーは準備中です。</p>':''}`;}
