import {towerShopItems} from '../data/tower-shop.js';
import {shopUnavailable,shopPurchaseCount,prepareShopPurchase} from '../game/tower-shop.js';
import {towerStarters} from '../data/tower.js';
import {deckCubes} from '../data/battle-style.js';
import {publicAsset} from '../data/public-assets.js';
import {cubeMarkup} from '../components/battle-art.js';
import {commitProfile} from '../game/profile.js?v=7.3.0';
import {sound} from '../audio/audio.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function towerShopScreen({profile,byId}){
 const card=item=>{const f=item.kind==='figure'?byId.get(item.figureId):deckCubes.find(c=>c.id===item.cubeId),reason=shopUnavailable(profile,item);return `<article class="tower-shop-card"><div class="shop-product-art">${item.kind==='figure'?`<img src="${esc(f.image)}" alt="${esc(f.name)}" loading="lazy">`:cubeMarkup(item.cubeId)}</div><div class="shop-product-copy"><small>${item.kind==='figure'?'シングル · 1体':'デッキキューブ'}</small><h3>${esc(f.name)}</h3><p>${esc(item.note)}</p><span>${item.kind==='figure'?'所持 '+(profile.owned?.[item.figureId]||0)+'体 · ':''}購入は1回まで</span><button data-shop-buy="${item.id}" data-shop-count="${shopPurchaseCount(profile,item.id)}" ${reason?'disabled':''}>${reason||item.price.toLocaleString('ja-JP')+(item.currency==='diamonds'?' ダイヤで購入':' コインで購入')}</button></div></article>`;};
 return `<section class="tower-shop-page"><header><h1>タワーショップ</h1><p>必要な仲間を、選んで迎えよう。</p></header><div class="shop-wallet">所持コイン <b>${profile.coins.toLocaleString('ja-JP')}</b> · ダイヤ <b>${profile.diamonds.toLocaleString('ja-JP')}</b></div><h2>スターターを補う仲間</h2><p class="shop-section-note">表示した仲間が1体、必ず手に入ります。</p><div class="tower-shop-list">${towerShopItems.filter(i=>i.kind==='figure').map(card).join('')}</div><h2>デッキキューブ</h2><p class="shop-section-note">見た目を変える装備です。購入後にカスタマイズで選べます。</p><div class="tower-shop-list">${towerShopItems.filter(i=>i.kind==='cube').map(card).join('')}</div><button class="shop-customize" data-go="battle-style">キューブを装備する</button><details class="starter-package"><summary>最初のスターターパッケージ</summary><img class="starter-package-art" src="${publicAsset('assets/towers/layers/starter-package-oct09.png')}" alt="スターターパッケージ"><p>新しい冒険には、3つの45体デッキ。ぷにモブを素材に、新しいミドルへ。ガチャやショップで少しずつ育てられます。</p>${towerStarters.map(s=>`<div class="starter-package-deck"><b>${esc(s.name)}</b><span>${[...new Set(s.deck)].slice(-3).map(id=>`<img src="${esc(byId.get(id).image)}" alt="${esc(byId.get(id).name)}">`).join('')}</span><small>45体 · 受け取り済み</small></div>`).join('')}</details><button class="shop-customize" data-go="tower">タワーへ戻る</button></section>`;
}
let buying=false;
export function handleTowerShop(button,ctx,{render,toast}){if(!button.hasAttribute('data-shop-buy'))return false;if(buying)return true;buying=true;try{const next=prepareShopPurchase(ctx.profile,button.dataset.shopBuy,Number(button.dataset.shopCount));if(!commitProfile(next))throw Error('保存できませんでした。コインと所持品は変更していません');sound.play('reward');render({preserveScroll:true});toast('購入しました');}catch(e){toast(e.message,'error');}finally{buying=false;}return true;}
