import {sound} from './audio.js';
import {CUES,ATTRIBUTES} from './synthesis.js';
let installed=false;
export function soundSettingsMarkup(){const s=sound.getSettings();return `<section class="sound-settings"><h2>サウンド</h2><button class="setting-row" data-sfx-toggle aria-pressed="${!s.muted}"><span>BGM・効果音</span><b>${s.muted?'OFF':'ON'}</b></button><label>音量 <output data-sfx-level>${Math.round(s.volume*100)}%</output><input aria-label="サウンドの音量" data-sfx-volume type="range" min="0" max="100" value="${Math.round(s.volume*100)}"></label><p data-sfx-status role="status">${sound.debug().supported?'初回のタップ後に音が鳴ります。':'この環境では音声を利用できません。ゲームはそのまま遊べます。'}</p><button class="sound-gallery-link" data-go="sound">効果音を試聴する →</button></section>`;}
export function soundGalleryScreen(){return `<section class="library sound-gallery"><h1>効果音スタジオ</h1><p>試聴だけで、所持品・通貨・対戦結果は変わりません。</p>${soundSettingsMarkup()}<div class="sound-options"><label>属性<select id="sfx-attribute">${[...ATTRIBUTES,'地/闇','水/火','光/闇','闇/無'].map(a=>`<option>${a}</option>`).join('')}</select></label><label>強さ<select id="sfx-strength"><option value="small">小</option><option value="medium" selected>中</option><option value="large">大</option></select></label><label>攻撃方法<select id="sfx-type"><option>物理</option><option>魔法</option></select></label></div><p>提供SEを用途・属性で再生します。未読込時は従来音で補い、実戦では演出時間に合わせて短縮します。</p><div class="sound-cue-list">${Object.entries(CUES).map(([id,label])=>`<button data-sfx-preview="${id}">${label} ▶</button>`).join('')}</div><button data-sfx-stop>試聴を止める</button><button data-go="settings">設定に戻る</button></section>`;}
function updateControls(){const s=sound.getSettings();document.querySelectorAll('[data-sfx-toggle],[data-sound]').forEach(b=>{if(b.hasAttribute('data-sound')){b.textContent=s.muted?'SOUND OFF':'SOUND ON';b.setAttribute('aria-pressed',String(!s.muted));}else{b.setAttribute('aria-pressed',String(!s.muted));b.querySelector('b').textContent=s.muted?'OFF':'ON';}});document.querySelectorAll('[data-sfx-level]').forEach(e=>e.textContent=Math.round(s.volume*100)+'%');document.querySelectorAll('[data-sfx-status]').forEach(e=>e.textContent=sound.debug().saveFailed?'音の設定を保存できません。現在の画面では反映されています。':s.muted?'効果音はOFFです。':s.volume===0?'音量は0%です。':'効果音はONです。');}
export function installSoundUi(legacySound){if(installed)return;installed=true;sound.init(legacySound);
 let musicNotice=null;window.addEventListener('mpb:music-loading',e=>{const {loading,failed}=e.detail;musicNotice?.remove();musicNotice=null;if(!loading&&!failed)return;musicNotice=document.createElement('aside');musicNotice.className='audio-loading-note music-loading-note';musicNotice.setAttribute('role','status');const label=document.createElement('span');label.textContent=loading?'BGMを読み込んでいます…':'BGMを読み込めませんでした';musicNotice.append(label);if(failed){const retry=document.createElement('button');retry.textContent='再試行';retry.onclick=()=>sound.retryMusic();musicNotice.append(retry);}const stop=document.createElement('button');stop.textContent='BGMなしで続ける';stop.onclick=()=>sound.stopMusic();musicNotice.append(stop);document.body.append(musicNotice);});
 let audioNotice=null,audioNoticeDismissed=false;window.addEventListener('mpb:audio-loading',e=>{const {done,total,failed}=e.detail;if(audioNoticeDismissed)return;if(done===total&&!failed){audioNotice?.remove();audioNotice=null;return;}if(!audioNotice){audioNotice=document.createElement('aside');audioNotice.className='audio-loading-note';audioNotice.setAttribute('role','status');document.body.append(audioNotice);}audioNotice.replaceChildren();const text=document.createElement('span');text.textContent=done===total?'音声'+failed+'件を読み込めませんでした（従来音で継続）':'音声を準備中 '+done+' / '+total;audioNotice.append(text);if(done===total){const retry=document.createElement('button');retry.textContent='再試行';retry.onclick=()=>{void sound.preload({retry:true});};audioNotice.append(retry);}const close=document.createElement('button');close.textContent='閉じる';close.onclick=()=>{audioNoticeDismissed=true;audioNotice?.remove();audioNotice=null;};audioNotice.append(close);});
 document.addEventListener('pointerdown',()=>{void sound.unlock();},{capture:true,passive:true});document.addEventListener('touchend',()=>{void sound.unlock();},{capture:true,passive:true});document.addEventListener('click',()=>{void sound.unlock();},{capture:true});document.addEventListener('keydown',e=>{if(['Enter',' ','ArrowLeft','ArrowRight'].includes(e.key))void sound.unlock();},{capture:true});
 document.addEventListener('input',e=>{if(e.target.matches?.('[data-sfx-volume]')){sound.setSettings({volume:Number(e.target.value)/100});updateControls();}});
 document.addEventListener('change',e=>{if(e.target.matches?.('[data-sfx-volume]'))sound.play('select');else if(e.target.matches?.('select'))sound.play('select');});
 document.addEventListener('click',async e=>{const b=e.target.closest?.('button');if(!b||b.disabled)return;
  if(b.hasAttribute('data-sfx-toggle')){sound.setSettings({muted:!sound.getSettings().muted});await sound.unlock();sound.play('confirm');updateControls();return;}
  if(b.hasAttribute('data-sfx-stop')){sound.stopAll();return;}
  if(b.dataset.sfxPreview){sound.stopAll();await sound.unlock();sound.play(b.dataset.sfxPreview,{attribute:document.querySelector('#sfx-attribute')?.value,strength:document.querySelector('#sfx-strength')?.value,attackType:document.querySelector('#sfx-type')?.value});updateControls();return;}
  if(b.closest('.fx-running,.figure-lab')||b.matches('[data-go],[data-sound],[data-sfx-volume],[data-confirm-draw],[data-confirm-exchange],[data-soul-add],[data-soul-remove],[data-soul-auto],[data-soul-clear],[data-piece-starter],[data-soul-starter],[data-launch-confirm],[data-mission-claim],[data-mission-claim-all],[data-assist-apply],[data-deck-assist-undo],[data-summon],[data-empty],[data-fuse],[data-skill-confirm],[data-phase],[data-end],[data-step],[data-forfeit],[data-pass],[data-battle-start],[data-comp-battle],[data-fx-skip]'))return;
  if(b.matches('[data-piece][data-side="1"].targetable'))return;
  const back=b.matches('[data-sheet-close],[data-clear],[data-close-result],[data-launch-back]')||['close','detail-close'].includes(b.dataset.gacha)||/戻る|閉じる|キャンセル/.test(b.textContent||'');sound.play(back?'back':b.matches('[data-draw],[data-gacha="lineup"],[data-banner]')?'gachaOpen':'select');
 });
 window.addEventListener('hashchange',()=>{sound.stopAll();sound.play('navigate');});
 document.addEventListener('visibilitychange',()=>document.hidden?sound.background():sound.foreground());window.addEventListener('pagehide',()=>sound.background());window.addEventListener('pageshow',()=>sound.foreground());
}
