import messages from '../data/summon-messages.json' with {type:'json'};
const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=Object.fromEntries(Object.entries(messages).filter(([,v])=>typeof v==='string').map(([k,v])=>[k,escapeText(v)]));
// A self-contained scene: motion is cancellable and never mutates draw results.
export function playSummon(dialog,{cue,hero,art,reduced,preview,onFinish}){
 const cueText=messages.cues[cue];const copy=cueText.map(escapeText);
 dialog.classList.add('cinema-dialog');
 dialog.innerHTML=`<section class="summon-scene cue-${cue}" data-phase="ready"><canvas class="summon-sky" aria-hidden="true"></canvas><header><span>${text.brand} <small>${preview?text.previewHeader:text.header}</small></span><button data-skip>${text.skip}</button></header><div class="summon-title"><small>${text.eyebrow}</small><h2>${text.title}</h2></div><div class="summon-core" aria-hidden="true"><div class="core-shell"><img class="gacha-core-image" src="${import.meta.env?.BASE_URL??'./'}icon/gacha.png" alt="MOB"><span class="core-fallback" hidden>${text.mob}</span></div><div class="impact-lines"></div>${Array.from({length:12},(_,i)=>`<b class="mob-glyph" style="--i:${i};--x:${Math.cos(i/12*Math.PI*2)*140}px;--y:${Math.sin(i/12*Math.PI*2)*160}px;--c:${['#8ad9e2','#ffcb61','#eb81aa'][i%3]}">${text.mob}</b>`).join('')}</div><div class="summon-comet" aria-hidden="true"><b>${text.mob}</b></div><div class="summon-gate" aria-hidden="true"><i></i><i></i></div><div class="cue-cut"><small>${text.cutLabel}</small><h2>${copy[0]}</h2><p>${copy[1]}</p>${cue==='pickup'?'<span class="destiny-seal">${text.seal}<span>${text.sealLabel}</span></span>':''}</div><div class="summon-reveal rarity-${hero.rarity}"><span class="reveal-rarity">${hero.rarity}</span><div class="reveal-art">${art(hero)}</div><small>${hero.displayNo}</small><h2>${hero.name}</h2><p>${preview?text.previewResult: text.result}</p></div><footer><p class="scene-caption" aria-live="polite">${text.ready}</p><button class="release-button" data-release>${text.release} <span>${text.releaseEnglish}</span></button><button class="release-button" data-finish hidden>${preview?text.closePreview:text.showResult} →</button><small>${reduced?text.reduced:text.hint}</small></footer></section>`;
 const coreImage=dialog.querySelector('.gacha-core-image');coreImage.onerror=()=>{coreImage.hidden=true;dialog.querySelector('.core-fallback').hidden=false;};
 const scene=dialog.querySelector('.summon-scene');const canvas=dialog.querySelector('canvas');const context=canvas.getContext('2d');let disposed=false;let raf;let started=false;const timers=[];let phase='ready';let born=performance.now();
 const colors={normal:'#193b39',chance:'#8c459c',ultra:'#c06b23',pickup:'#c74840'};
 function finish(){if(disposed)return;cleanup();onFinish();}
 function cleanup(){disposed=true;cancelAnimationFrame(raf);timers.forEach(clearTimeout);dialog.classList.remove('cinema-dialog');}
 const particles=Array.from({length:65},(_,i)=>({x:(i*0.6180339)%1,y:(i*0.38197)%1,r:i%4===0?1.7:.8}));
 function paint(now){if(disposed||!dialog.open)return;const rect=canvas.getBoundingClientRect();const w=rect.width,h=rect.height;const scale=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*scale)||canvas.height!==Math.round(h*scale)){canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);}context.setTransform(scale,0,0,scale,0,0);context.clearRect(0,0,w,h);context.fillStyle=colors[cue];context.strokeStyle=colors[cue];const elapsed=(now-born)/1000;
 for(const p of particles){const travel=phase==='flight'?elapsed*.3:elapsed*.016;const x=(p.x+(reduced?0:travel))%1*w,y=(p.y+(reduced?0:travel*.8))%1*h;context.globalAlpha=.2+p.r*.22;context.beginPath();if(phase==='flight'&&!reduced){context.moveTo(x,y);context.lineTo(x-32,y-70);context.stroke();}else{context.fillRect(x,y,p.r*2,p.r*3);}}
 if(phase==='reveal'&&!reduced){for(let i=0;i<(cue==='normal'?10:38);i++){const t=(elapsed*.32+i*.075)%1;context.globalAlpha=1-t;context.fillStyle=['#f6cc6b','#d8eef2','#cfabd8'][i%3];context.fillRect((i*.618%1)*w,t*h,3+i%3,7);}}
 context.globalAlpha=1;raf=requestAnimationFrame(paint);}
 function setPhase(next,label){phase=next;scene.dataset.phase=next;born=performance.now();dialog.querySelector('.scene-caption').textContent=label;}
 function start(){if(started)return;started=true;dialog.querySelector('[data-release]').hidden=true;dialog.querySelector('.summon-title').hidden=true;setPhase('gather',messages.gather);const sequence=reduced?[[350,'cue',cueText[1]],[1900,'reveal',messages.reveal]]:[[1500,'flight',messages.flight],[3000,'cue',cueText[1]],[5700,'reveal',messages.reveal]];for(const [ms,p,label] of sequence)timers.push(setTimeout(()=>{if(disposed)return;setPhase(p,label);if(p==='reveal'){dialog.querySelector('[data-finish]').hidden=false;dialog.querySelector('[data-finish]').focus({preventScroll:true});}},ms));}
 dialog.querySelector('[data-release]').onclick=start;dialog.querySelector('[data-finish]').onclick=finish;dialog.querySelector('[data-skip]').onclick=finish;dialog.querySelector('[data-release]').focus();raf=requestAnimationFrame(paint);return cleanup;
}
