// A self-contained scene: motion is cancellable and never mutates draw results.
export function playSummon(dialog,{cue,hero,art,reduced,preview,onFinish}){
 const copy={normal:['星のかけら','新しい出会いが、近づいてくる。'],chance:['共鳴のきざし','いつもと違う輝き…'],ultra:['黄金の扉','UR以上 確定'],pickup:['運命の刻印','メインピックアップ 確定']}[cue];
 dialog.classList.add('cinema-dialog');
 dialog.innerHTML=`<section class="summon-scene cue-${cue}" data-phase="ready"><canvas class="summon-sky" aria-hidden="true"></canvas><header><span>PIECE SUMMON <small>${preview?'演出プレビュー・獲得なし':'星のかけらを、ひとつに。'}</small></span><button data-skip>スキップ →</button></header><div class="summon-title"><small>A LITTLE PIECE OF DESTINY</small><h2>想いを、解き放て。</h2></div><div class="summon-core" aria-hidden="true"><div class="core-shell"><span>M</span><i></i></div><div class="impact-lines"></div>${Array.from({length:12},(_,i)=>`<b class="mob-glyph" style="--i:${i};--x:${Math.cos(i/12*Math.PI*2)*140}px;--y:${Math.sin(i/12*Math.PI*2)*160}px;--c:${['#8ad9e2','#ffcb61','#eb81aa'][i%3]}">MOB</b>`).join('')}</div><div class="summon-comet" aria-hidden="true"></div><div class="summon-gate" aria-hidden="true"><i></i><i></i></div><div class="cue-cut"><small>RESONANCE</small><h2>${copy[0]}</h2><p>${copy[1]}</p>${cue==='pickup'?'<span class="destiny-seal">M<span>DESTINY</span></span>':''}</div><div class="summon-reveal rarity-${hero.rarity}"><span class="reveal-rarity">${hero.rarity}</span><div class="reveal-art">${art(hero)}</div><small>${hero.displayNo}</small><h2>${hero.name}</h2><p>${preview?'演出プレビュー': 'あなたのコレクションに、新しい輝き。'}</p></div><footer><p class="scene-caption" aria-live="polite">かけらを集めて、新しいピースを呼び出そう。</p><button class="release-button" data-release>解き放つ <span>RELEASE</span></button><button class="release-button" data-finish hidden>${preview?'プレビューを閉じる':'結果を見る'} →</button><small>${reduced?'動きを抑えた演出で表示します':'タップして解き放つ'}</small></footer></section>`;
 const scene=dialog.querySelector('.summon-scene');const canvas=dialog.querySelector('canvas');const context=canvas.getContext('2d');let disposed=false;let raf;let started=false;const timers=[];let phase='ready';let born=performance.now();
 const colors={normal:'#8fddeb',chance:'#c39bff',ultra:'#ffd574',pickup:'#ffda91'};
 function finish(){if(disposed)return;cleanup();onFinish();}
 function cleanup(){disposed=true;cancelAnimationFrame(raf);timers.forEach(clearTimeout);dialog.classList.remove('cinema-dialog');}
 const particles=Array.from({length:65},(_,i)=>({x:(i*0.6180339)%1,y:(i*0.38197)%1,r:i%4===0?1.7:.8}));
 function paint(now){if(disposed||!dialog.open)return;const rect=canvas.getBoundingClientRect();const w=rect.width,h=rect.height;const scale=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*scale)||canvas.height!==Math.round(h*scale)){canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);}context.setTransform(scale,0,0,scale,0,0);context.clearRect(0,0,w,h);context.fillStyle=colors[cue];context.strokeStyle=colors[cue];const elapsed=(now-born)/1000;
 for(const p of particles){const travel=phase==='flight'?elapsed*.3:elapsed*.016;const x=(p.x+(reduced?0:travel))%1*w,y=(p.y+(reduced?0:travel*.8))%1*h;context.globalAlpha=.2+p.r*.22;context.beginPath();if(phase==='flight'&&!reduced){context.moveTo(x,y);context.lineTo(x-32,y-70);context.stroke();}else{context.arc(x,y,p.r,0,Math.PI*2);context.fill();}}
 if(phase==='reveal'&&!reduced){for(let i=0;i<(cue==='normal'?10:38);i++){const t=(elapsed*.32+i*.075)%1;context.globalAlpha=1-t;context.fillStyle=['#f6cc6b','#d8eef2','#cfabd8'][i%3];context.fillRect((i*.618%1)*w,t*h,3+i%3,7);}}
 context.globalAlpha=1;raf=requestAnimationFrame(paint);}
 function setPhase(next,label){phase=next;scene.dataset.phase=next;born=performance.now();dialog.querySelector('.scene-caption').textContent=label;}
 function start(){if(started)return;started=true;dialog.querySelector('[data-release]').hidden=true;dialog.querySelector('.summon-title').hidden=true;setPhase('gather','MOBのかけらが、共鳴している…');const sequence=reduced?[[350,'cue',copy[1]],[1500,'reveal','ピースが姿を現した。']]:[[1500,'flight','想いは、星の向こうへ。'],[3000,'cue',copy[1]],[4900,'reveal','ピースが姿を現した。']];for(const [ms,p,label] of sequence)timers.push(setTimeout(()=>{if(disposed)return;setPhase(p,label);if(p==='reveal'){dialog.querySelector('[data-finish]').hidden=false;dialog.querySelector('[data-finish]').focus({preventScroll:true});}},ms));}
 dialog.querySelector('[data-release]').onclick=start;dialog.querySelector('[data-finish]').onclick=finish;dialog.querySelector('[data-skip]').onclick=finish;dialog.querySelector('[data-release]').focus();raf=requestAnimationFrame(paint);return cleanup;
}
