import assert from 'node:assert/strict';import {createRequire} from 'node:module';import path from 'node:path';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),base=process.env.MPB_TEST_URL||'http://127.0.0.1:5187';
try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#sound');await page.waitForFunction(()=>document.documentElement.dataset.mpbReady==='1');if(await page.locator('[data-initial-review]').count()){await page.locator('[data-initial-review]').first().click();await page.locator('[data-initial-confirm]').click();await page.evaluate(()=>{location.hash='sound';});}await page.locator('[data-sfx-preview="attack"]').waitFor();while(await page.locator('[data-comp="dismiss-notice"]').count())await page.locator('[data-comp="dismiss-notice"]').click();
 const debug=()=>page.evaluate(async()=>(await import('/src/audio/audio.js')).sound.debug());
 assert.equal(await page.locator('[data-sfx-preview]').count(),31);
 const attrs=await page.locator('#sfx-attribute option').evaluateAll(xs=>xs.map(x=>x.value));assert.equal(attrs.length,12);
 await page.locator('[data-sfx-toggle]').evaluate((el)=>{if(el.getAttribute('aria-pressed')==='false')el.click();});
 for(const attribute of attrs)for(const cue of ['attack','skill','fusion']){await page.selectOption('#sfx-attribute',attribute);await page.locator(`[data-sfx-preview="${cue}"]`).click();await page.waitForFunction(({cue,attribute})=>import('/src/audio/audio.js').then(({sound})=>{const h=sound.debug().history.at(-1);return h?.cue===cue&&h.attribute===attribute;}),{cue,attribute});}
 assert.equal((await debug()).errors,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'docs/sound-studio-mobile.png'});
 await page.locator('[data-sfx-volume]').fill('27');await page.locator('[data-sfx-toggle]').click();await page.reload();await page.locator('[data-sfx-toggle]').waitFor();assert.equal(await page.locator('[data-sfx-toggle]').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('[data-sfx-volume]').inputValue(),'27');const mutedBefore=(await debug()).played;await page.locator('[data-sfx-preview="attack"]').click();assert.equal((await debug()).played,mutedBefore);assert.equal((await debug()).voices,0);
 await page.locator('[data-sfx-toggle]').click();await page.locator('[data-sfx-preview="fusion"]').click();await page.waitForTimeout(70);await page.evaluate(()=>{location.hash='home';});await page.waitForTimeout(180);assert.equal((await debug()).voices,0);
 const burst=await page.evaluate(async()=>{const {sound}=await import('/src/audio/audio.js');sound.stopAll();let n=0;for(let i=0;i<25;i++)if(sound.play('attack',{attribute:'火'}))n++;return {n,...sound.debug()};});assert.equal(burst.n,1,JSON.stringify(burst));assert.ok(burst.maxVoices<=6);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await debug()).voices,0);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});await page.locator('[data-go="deck"]').first().click();await page.locator('[data-piece-starter]').first().click();assert.equal((await debug()).history.at(-1).cue,'starter');
 // Render the actual shared synthesis/bus in a real OfflineAudioContext: output and mute silence.
 const rendered=await page.evaluate(async()=>{const {createSoundSystem}=await import('/src/audio/audio.js');async function run(muted){const ctx=new OfflineAudioContext(1,96000,48000);function Context(){return {get state(){return 'running';},get currentTime(){return ctx.currentTime;},destination:ctx.destination,createGain:()=>ctx.createGain(),createDynamicsCompressor:()=>ctx.createDynamicsCompressor(),createBufferSource:()=>ctx.createBufferSource(),createBuffer:(...a)=>ctx.createBuffer(...a)};}let clock=1000;const s=createSoundSystem({host:{AudioContext:Context},storage:null,now:()=>clock});s.setSettings({volume:1,muted:false});await s.unlock();s.setSettings({muted});for(const attribute of ['火','水','雷','地','光','闇']){clock+=100;s.play('attack',{attribute,strength:'medium'});}const buffer=await ctx.startRendering(),a=buffer.getChannelData(0);let peak=0,power=0;for(const v of a){peak=Math.max(peak,Math.abs(v));power+=v*v;}return {peak,rms:Math.sqrt(power/a.length)};}return {audible:await run(false),muted:await run(true)};});assert.ok(rendered.audible.peak>0.02&&rendered.audible.peak<1);assert.ok(rendered.audible.rms>.002);assert.equal(rendered.muted.peak,0);
 const eventsPlayed=await page.evaluate(async()=>{const {createBattleDirector}=await import('/src/components/battle-director.js'),{soulFigures}=await import('/src/game/soul-battle.js'),{sound}=await import('/src/audio/audio.js');const root=document.createElement('div');root.innerHTML='<div class="duel-fx"></div>';document.body.append(root);const d=createBattleDirector(root,{profile:{reducedMotion:true},style:{fast:true,cube:{id:'hero'}}});const events=[];let seq=1000;for(const attribute of [...new Set(soulFigures.map(f=>f.attribute))]){const f=soulFigures.find(f=>f.attribute===attribute);for(const type of ['attack','skill','fusion'])events.push({type,seq:seq++,side:0,id:f.id,attribute,attackType:f.attackType,targetId:f.id,atk:f.atk,def:f.def,name:f.soulSkill.name,materialIds:[f.id,f.id]});}for(const type of ['hit','guard','defeat'])events.push({type,seq:seq++,side:0,id:'01',damage:20});events.push({type:'result',seq:seq++,side:0,reason:'試験'});await d.run(events);const count=sound.debug().history.filter(x=>x.eventId>=1000).length;d.destroy();root.remove();return count;});assert.equal(eventsPlayed,40);
 await page.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{grantMainCollection,applyPieceStarter}=await import('/src/game/piece-starters.js');const profile={owned:{},reducedMotion:true};grantMainCollection(profile,{newProfile:true});applyPieceStarter(profile,'materials-balloon');const random=Math.random;Math.random=()=>.999999;try{window.audioBattle=launchBattle({profile,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=random;}});
 await page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor();assert.ok((await debug()).history.some(x=>x.cue==='start'));assert.ok((await debug()).history.some(x=>x.cue==='draw'));
 for(let i=0;i<2;i++){await page.locator('[data-hand="0"]').click();await page.locator('[data-summon]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();}assert.ok((await debug()).history.some(x=>x.cue==='summon'));
 for(let i=0;i<2;i++){await page.locator('.duel-field.side-0 [data-piece]').nth(i).click();await page.locator('[data-material]').click();}await page.locator('[data-recipe="BALLOON-026-026"]').click();await page.locator('[data-fuse]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();assert.ok((await debug()).history.some(x=>x.cue==='fusion'));
 await page.locator('.duel-field.side-0 [data-piece]').click();await page.locator('[data-skill]').click();await page.locator('[data-skill-confirm]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();assert.ok((await debug()).history.some(x=>x.cue==='skill'));
 await page.locator('[data-sound]').click();assert.equal((await debug()).voices,0);assert.match(await page.locator('[data-sound]').textContent(),/OFF$/);await page.locator('[data-sound]').click();
 await page.locator('[data-quit]').click();await page.locator('[data-forfeit]').click();await page.locator('[data-close-result]').waitFor();assert.ok((await debug()).history.some(x=>x.cue==='lose'));await page.locator('[data-close-result]').click();assert.equal((await debug()).scopes,0);
 await page.evaluate(()=>{location.hash='settings';});await page.locator('[data-action="motion"]').click();await page.evaluate(()=>{location.hash='gacha';});await page.locator('.effect-guide summary').click();await page.locator('[data-preview="pickup"]').click();await page.locator('[data-release]').click();await page.locator('[data-finish]:visible').waitFor();for(const cue of ['gachaGather','gachaCue','gachaAssemble','gachaInk','gachaReveal'])assert.ok((await debug()).history.some(x=>x.cue===cue),cue);await page.locator('[data-finish]').click();assert.equal((await debug()).scopes,0);await page.locator('[data-preview="normal"]').click();await page.locator('[data-release]').click();await page.locator('[data-skip]').click();assert.equal((await debug()).scopes,0);assert.equal((await debug()).voices,0);
 // A new match receives a fresh scope; leaving during its introduction cancels future cues.
 await page.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{grantMainCollection}=await import('/src/game/piece-starters.js');const p={owned:{},reducedMotion:true};grantMainCollection(p,{newProfile:true});window.audioBattle2=launchBattle({profile:p,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});});await page.locator('[data-fx-skip]').waitFor();await page.evaluate(()=>{location.hash='sound';});await page.waitForTimeout(350);assert.equal((await debug()).voices,0);assert.equal((await debug()).scopes,0);
 assert.deepEqual(errors,[]);
 const silent=await browser.newPage();await silent.addInitScript(()=>{window.AudioContext=undefined;window.webkitAudioContext=undefined;});await silent.goto(base+'/#sound');await silent.waitForFunction(()=>document.documentElement.dataset.mpbReady==='1');if(await silent.locator('[data-initial-review]').count()){await silent.locator('[data-initial-review]').first().click();await silent.locator('[data-initial-confirm]').click();await silent.evaluate(()=>{location.hash='sound';});}await silent.locator('[data-sfx-preview="attack"]').waitFor();while(await silent.locator('[data-comp="dismiss-notice"]').count())await silent.locator('[data-comp="dismiss-notice"]').click();await silent.locator('[data-sfx-preview="attack"]').click();assert.equal(await silent.locator('[data-sfx-preview]').count(),31);await silent.goto(base+'/#deck');await silent.locator('[data-piece-starter]').first().click();assert.match(await silent.locator('.soul-deck-count').textContent(),/45 \/ 45/);await silent.close();
 console.log('PASS Edge: 12 attributes x attack/skill/fusion; PCM through actual audio bus '+JSON.stringify(rendered)+'; volume/mute reload; rapid-click suppression; simulated background recovery; starter; real summon/fusion/skill/forfeit; replay/route cleanup; unsupported Web Audio remains playable; no page errors. Not a physical Safari test.');
}finally{await browser.close();}
