import fs from 'node:fs';
const messages={brand:'MOB POP!',header:'MOBを集めて、ドカンとオープン！',previewHeader:'演出プレビュー・獲得なし',skip:'スキップ →',eyebrow:'READY, SET… MOB!',title:'MOB、飛び出せ！',mob:'MOB',cutLabel:'POP! POP! POP!',seal:'M',sealLabel:'SPECIAL',previewResult:'演出プレビュー',result:'ようこそ、MOBコレクション！',ready:'MOBを集めて、なにが出るかな？',release:'MOBを発射！',releaseEnglish:'LET’S POP!',closePreview:'プレビューを閉じる',showResult:'結果を見る',reduced:'動きを抑えた演出で表示します',hint:'タップしてMOBを発射！',gather:'MOBがどんどん集まってきた！',flight:'いっけー！MOBラッシュ！',reveal:'じゃーん！ピース登場！',cues:{normal:['MOB集合！','どんなピースが飛び出すかな？'],chance:['ざわざわ…！','おっ、なんだかイイ予感！'],ultra:['激アツゲート！','UR以上 確定'],pickup:['主役のおでまし！','メインピックアップ 確定']}};
fs.writeFileSync('src/data/summon-messages.json',JSON.stringify(messages,null,2)+'\n');
let p='src/components/summon.js',s=fs.readFileSync(p,'utf8');s="import messages from '../data/summon-messages.json' with {type:'json'};\nconst escapeText=value=>String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));\nconst text=Object.fromEntries(Object.entries(messages).filter(([,v])=>typeof v==='string').map(([k,v])=>[k,escapeText(v)]));\n"+s;
s=s.replace(/const copy=\{normal:.*?\}\[cue\];/, 'const cueText=messages.cues[cue];const copy=cueText.map(escapeText);');
const start=s.indexOf('dialog.innerHTML=`'),end=s.indexOf('`;\n',start)>=0?s.indexOf('`;\n',start):s.indexOf('`;\r\n',start);let markup=s.slice(start,end);let rest=s.slice(end);
for(const [key,value] of Object.entries(messages).filter(([,v])=>typeof v==='string').sort((a,b)=>b[1].length-a[1].length)){if(key==='mob'||key==='seal'||key==='sealLabel')continue;markup=markup.replaceAll("'"+value+"'",'text.'+key);markup=markup.replaceAll(value,'${text.'+key+'}');rest=rest.replaceAll("'"+value+"'",'messages.'+key);}
markup=markup.replaceAll('>MOB<','>${text.mob}<').replaceAll('>M<span>SPECIAL<','>${text.seal}<span>${text.sealLabel}<');rest=rest.replaceAll('copy[1]','cueText[1]');s=s.slice(0,start)+markup+rest;fs.writeFileSync(p,s);
p='src/screens/gacha.js';s=fs.readFileSync(p,'utf8');s="import summonMessages from '../data/summon-messages.json' with {type:'json'};\nimport {testSettings} from '../data/test-settings.js';\n"+s;
const labels="[['normal','MOB集合！'],['chance','ざわざわ…！'],['ultra','激アツゲート！'],['pickup','主役のおでまし！']]";s=s.replace(labels,"Object.entries(summonMessages.cues).map(([id,values])=>[id,values[0]])");s=s.replace('${label} ↗','${String(label).replace(/[&<>\"]/g,x=>({\'&\':\'&amp;\',\'<\':\'&lt;\',\'>\':\'&gt;\',\'"\':\'&quot;\'}[x]))} ↗');
s=s.replace('<div class="gacha-carousel"', '${testSettings.enabled?\'<button class="test-wallet" data-gacha="max">TEST ONLY · ダイヤ（MOB）MAXにする</button>\':\'\'}<div class="gacha-carousel"');
s=s.replace("const action=button.dataset.gacha;", "const action=button.dataset.gacha;if(action==='max'&&testSettings.enabled){if(commitProfile({...structuredClone(ctx.profile),diamonds:testSettings.maxCurrency})){refresh({preserveScroll:true});notify('テスト用残高をMAXにしました');}else notify('保存できませんでした');return;}");fs.writeFileSync(p,s);
