import assert from 'node:assert/strict';import{createRequire}from'node:module';import path from'node:path';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');const browser=await chromium.launch({headless:true,channel:'msedge'}),base=process.env.MPB_TEST_URL||'http://127.0.0.1:5191';
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('[data-initial-review]').first().click();await page.locator('[data-initial-confirm]').click();while(await page.locator('[data-comp="dismiss-notice"]').count())await page.locator('[data-comp="dismiss-notice"]').click();await page.goto(base+'/#figure');await page.locator('[data-element-claim]').waitFor();
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mob-piece-battle:profile:v1'))),old=await read();
 await page.evaluate(()=>{window.oldSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mob-piece-battle:profile:v1')throw Error('quota');return window.oldSetItem.call(this,k,v);};});await page.locator('[data-element-claim]').click();assert.deepEqual(await read(),old);assert.match(await page.locator('.toast').textContent(),/保存できません/);await page.evaluate(()=>{Storage.prototype.setItem=window.oldSetItem;});
 await page.locator('[data-element-claim]').evaluate(b=>{b.click();b.click();b.click();});const saved=await read();assert.equal(saved.elementCollectionVersion,1);assert.deepEqual(saved.soulDecks,old.soulDecks);for(const k of ['diamonds','rubies','coins','initialChoice'])assert.deepEqual(saved[k],old[k]);await page.reload();await page.locator('#figure-search').waitFor();assert.deepEqual(await read(),saved);
 const loaded=await page.evaluate(async()=>{const {elementIds}=await import('/src/game/element-collection.js'),{soulById}=await import('/src/game/soul-battle.js');return Promise.all([...elementIds].map(async id=>{const i=new Image;i.src=soulById.get(id).image;await i.decode();return {id,width:i.naturalWidth,height:i.naturalHeight};}));});assert.equal(loaded.length,54);assert.ok(loaded.every(x=>x.width>0&&x.height>0));
 await page.locator('#figure-search').fill('FRG');assert.equal(await page.locator('.soul-card').count(),6);assert.match(await page.locator('main').textContent(),/無料入手/);await page.screenshot({path:'docs/elements-collection-mobile.png'});await page.locator('[data-figure-info="FRG_S01"]').click();assert.match(await page.locator('dialog').textContent(),/火属性なら20/);assert.ok(!(await page.locator('dialog').textContent()).includes('口なし'));await page.screenshot({path:'docs/elements-detail-mobile.png'});await page.keyboard.press('Escape');
 await page.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{release}=await import('/src/game/initial-release.js'),{soulFigures}=await import('/src/game/soul-battle.js');const deck=[...release.starters[0].deck];deck[0]='FRG_S01';deck[1]='FRG_S03';deck[2]='FRG_S02';const p={owned:Object.fromEntries(soulFigures.map(f=>[f.id,25])),soulDecks:[deck,[],[],[],[]],soulDeckSlot:0,reducedMotion:true};const random=Math.random;Math.random=()=>.999999;try{window.elementBattle=launchBattle({profile:p,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=random;}});
 const ready=()=>page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor({timeout:60000});await ready();await page.locator('[data-hand="0"]').click();await page.locator('[data-summon]').click();await ready();const handCount=await page.locator('[data-hand]').count();await page.locator('[data-hand="0"]').click();await page.locator('[data-hand-skill]').click();assert.match(await page.locator('.duel-sheet').textContent(),/火属性|守護/);await page.screenshot({path:'docs/elements-attribute-skill-mobile.png'});await page.locator('.duel-sheet [data-sheet-close]').click();assert.equal(await page.locator('[data-hand]').count(),handCount);await page.locator('[data-hand-skill]').click();await page.locator('[data-skill-confirm]').click();await ready();assert.equal(await page.locator('[data-hand]').count(),handCount-1);await page.locator('[data-zone="grave"]').click();assert.match(await page.locator('.duel-sheet').textContent(),/モブプフ/);await page.locator('.duel-sheet [data-sheet-close]').click();await page.locator('.duel-field.side-0 [data-piece]').first().click();assert.match(await page.locator('.duel-sheet').textContent(),/90/);await page.screenshot({path:'docs/elements-buffed-field-mobile.png'});await page.locator('.duel-sheet [data-sheet-close]').click();await page.locator('[data-quit]').click();await page.locator('[data-forfeit]').click();await page.locator('[data-close-result]').click();assert.deepEqual(await read(),saved);
 // The normal draw and collection use separate state; three banners remain reachable.
 await page.goto(base+'/#gacha');assert.equal(await page.locator('[data-banner]').count(),3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS Edge mobile: 54 actual PNGs; free claim storage failure/repeated clicks/reload; old save and decks preserved; acquisition label; named family; real hand skill cancel/confirm/grave/attribute buff/detail; 3 banners; no page errors');
}finally{await browser.close();}
