import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import * as g from '../src/game/soul-battle.js';import data from '../src/data/element-additions.json' with {type:'json'};import audit from '../docs/elements-image-audit.json' with {type:'json'};import plans from '../src/game/soul-skill-programs.js';import {elementSkills}from '../src/data/element-skills.js';import {prepareElementCollection}from '../src/game/element-collection.js';import {release}from '../src/game/initial-release.js';import catalog from '../src/data/soul-catalog.js';
const deck=release.starters[0].deck,by=g.soulById;
const put=(s,side,id,slot)=>{const f={id,uid:++s.serial,attacks:0,skillTurn:-1,effects:[],attackedTargets:[],lastTarget:null,extra:0,mobFusion:false,permanentAtk:0,permanentDef:0};s.players[side].field[slot]=f;return f;};
function fresh(id,side=0,hand=true){const s=g.createSoulBattle([deck,deck]);s.active=side;s.turn=3;s.phase='main';for(const p of s.players){p.hand=[];p.field=[null,null,null];p.life=200;p.skillUsed=false;p.deck=['FRG_S01','SPI_S01','GHO_S01','FRG_S02'];p.grave=['SPI_S01','GHO_S01','SPI_M01'];p.destroyed=['GHO_S01'];}const a=put(s,side,id,0),b=put(s,side,'FRG_S01',1),c=put(s,side,'SPI_S01',2);for(const f of [a,b,c])f.effects.push({key:'atk',value:-5,until:4},{key:'def',value:-10,until:4});for(let i=0;i<3;i++){const e=put(s,1-side,['RUN_S02','CRY_S01','NIN_S01'][i],i);e.effects.push({key:'atk',value:20,until:4});}s.players[side].hand=[id,'FRG_S01'];return {s,ref:hand?{handIndex:0,id}:a.uid,a,b,c};}
const resolve=s=>{while(s.pending)g.passReaction(s,1-s.pending.side);};
const cast=(s,side,ref,o=g.cpuOptions(s,side,ref))=>{g.useSkill(s,side,ref,o);resolve(s);};
assert.equal(data.figures.length,54);assert.equal(new Set(data.figures.map(f=>f.id)).size,54);assert.equal(g.soulFigures.length,611);assert.equal(data.recipes.length,24);assert.equal(elementSkills.length,48);
for(const f of data.figures){assert.ok(plans[f.soulSkill.program]);assert.ok(f.tags.length<=catalog.rules.tagLimits[f.rarity]);assert.ok(f.tags.every(t=>catalog.tags.some(x=>x.id===t)));const row=audit.accepted.find(x=>x.id===f.id);assert.ok(row);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.image)).digest('hex'),row.hash);}
for(const id of audit.excluded.deletedRetro)assert.ok(!by.has(id));assert.equal(catalog.tags.find(t=>t.id==='mat-mouth').name,'モブの旅仲間');
let executions=0;
for(const def of elementSkills)for(const side of [0,1])for(const hand of [false,true]){const {s,ref}=fresh(def.id,side,hand),p=s.players[side],o=g.cpuOptions(s,side,ref),before=structuredClone(s);
 const choices=g.skillChoices(s,side,ref,o);if(choices.length){assert.throws(()=>g.useSkill(s,side,ref,{...o,[choices.at(-1).key]:'invalid'}));assert.deepEqual(s,before,def.id+' invalid atomic');}
 // Merely previewing choices is cancellation: no costs or mutations.
 g.skillChoices(s,side,ref,o);assert.deepEqual(s,before);
 cast(s,side,ref,o);assert.ok(p.skillUsed,def.id);if(hand)assert.equal(p.used.filter(x=>x===def.id).length,1,def.id);assert.ok(p.life>=0&&p.life<=400);assert.ok(s.players.every(x=>x.field.filter(Boolean).every(t=>g.stats(t).atk>=0&&g.stats(t).def>=0)));assert.ok(s.events.some(e=>e.type==='skill'&&e.id===def.id&&e.fromHand===hand));executions++;
}
console.log(`PASS ${executions} new skill executions: both sides x field/hand, invalid/cancel atomic, actual programs and caps`);
// Attribute-dependent results, including changed current attributes rather than original artwork.
for(const side of [0,1]){let t=fresh('FRG_S01',side),before=g.stats(t.b).atk;cast(t.s,side,t.ref,{el_a:t.b.uid});assert.equal(g.stats(t.b).atk,before+20);t=fresh('FRG_S01',side);t.b.effects.push({key:'attribute',value:'水',until:4});before=g.stats(t.b).atk;cast(t.s,side,t.ref,{el_a:t.b.uid});assert.equal(g.stats(t.b).atk,before+15);
 t=fresh('ECL_S01',side);t.s.players[side].field.forEach(x=>x.effects.push({key:'attribute',value:'水',until:4}));const snapshot=structuredClone(t.s);assert.throws(()=>cast(t.s,side,t.ref));assert.deepEqual(t.s,snapshot);
 t=fresh('ECL_M01',side);t.b.effects.push({key:'attribute',value:'火',until:4});const n=t.s.players[side].hand.length;cast(t.s,side,t.ref);assert.equal(t.s.players[side].hand.length,n); // one used, one drawn for fire + dark
 t=fresh('CRY_M02',side);const e=t.s.players[1-side].field[0];e.effects.push({key:'attribute',value:'地',until:4});const def=g.stats(e).def;cast(t.s,side,t.ref,{el_a:t.b.uid,el_e:e.uid});assert.equal(g.stats(e).def,def-30);
 t=fresh('FRG_S03',side);cast(t.s,side,t.ref,{el_a:t.b.uid});assert.ok(t.b.effects.some(e=>e.key==='pierceGuard'));
 t=fresh('DUA_S02',side);t.b.effects.push({key:'attribute',value:'水',until:4});cast(t.s,side,t.ref,{el_a:t.b.uid});assert.ok(!t.b.effects.some(e=>['atk','def'].includes(e.key)&&e.value<0));
}
console.log('PASS fire support, fire/dark link, water cleanse, wind/fire guard penetration, earth weakness, current attribute changes');
for(const def of elementSkills){const {s,ref}=fresh(def.id);const o=g.cpuOptions(s,0,ref);for(const choice of g.skillChoices(s,0,ref,o).filter(c=>c.choices.length>1)){for(const opt of choice.choices){const t=fresh(def.id);const selected={...g.cpuOptions(t.s,0,t.ref),[choice.key]:opt.value};let valid=true;for(const c of g.skillChoices(t.s,0,t.ref,selected)){if(!c.choices.some(x=>String(selected[c.key])===x.value))selected[c.key]=c.choices[0]?.value;if(!c.choices.length)valid=false;}if(valid)cast(t.s,0,t.ref,selected);}}}
console.log('PASS alternate target/mode/optional/one-effect removal choices');
for(const r of data.recipes)for(const side of [0,1])for(const hand of [false,true]){const {s}=fresh('FRG_S01',side),p=s.players[side];p.field=[null,null,null];const a=put(s,side,r.materials[0].id,0);p.hand=[r.materials[1].id];const refs=[a.uid,hand?{handIndex:0}:put(s,side,r.materials[1].id,1).uid];p.reserve=[r.target];assert.ok(g.fusionOptions(s,side,refs).some(x=>x.id===r.id));g.fuse(s,side,refs,r.id);assert.equal(p.field[0].id,r.target);assert.deepEqual(g.stats(p.field[0]),{atk:by.get(r.target).atk,def:by.get(r.target).def});assert.ok(r.materials.every(m=>p.grave.includes(m.id)));}
console.log('PASS 24 recipes x both sides x hand/field; ordinary fusion has no unrequested bonus');
const old={owned:{'01':12,'BFX046':2},diamonds:321,rubies:32,coins:98,soulDecks:release.starters.map(s=>s.deck),soulDeckSlot:1,lastDraw:{keep:true}},before=structuredClone(old),next=prepareElementCollection(old);assert.deepEqual(old,before);for(const k of Object.keys(old).filter(k=>k!=='owned'))assert.deepEqual(next[k],old[k]);for(const [id,n]of Object.entries(old.owned))assert.equal(next.owned[id],n);for(const f of data.figures)assert.equal(next.owned[f.id],f.soulClass==='mob'?1:2);assert.throws(()=>prepareElementCollection(next));
assert.equal(release.starters.length,3);assert.equal(release.banners.length,3);console.log('PASS explicit free acquisition, sufficient shared fusion seeds, no currency/deck/save overwrite, idempotence; three starters/banners unchanged');
for(const f of data.figures.filter(f=>f.id.startsWith('RETRO')))for(const side of [0,1])for(const hand of [false,true]){const {s,ref}=fresh(f.id,side,hand);cast(s,side,ref);assert.ok(s.players[side].skillUsed);if(hand)assert.ok(s.players[side].grave.includes(f.id));}
console.log('PASS 24 RETRO executions using verified existing programs (6 x both sides x hand/field)');
// Enemy AI uses the same choices and executes every new hand program in real CPU turns.
for(const d of elementSkills){const {s}=fresh(d.id,1,true);for(const f of s.players[1].field)f.effects.push({key:'skillLock',value:true,until:99},{key:'fusionLock',value:true,until:99});s.players[1].hand=[d.id];g.cpuMain(s);resolve(s);assert.ok(s.events.some(e=>e.type==='skill'&&e.id===d.id&&e.fromHand),d.id+' CPU');}
console.log('PASS enemy CPU executes all48 new hand programs');
// Tiered fusion wins over fallback; a fallback never grows above +10.
{const {s}=fresh('FRG_S01'),p=s.players[0];p.field=[null,null,null];const a=put(s,0,'FRG_S01',0),b=put(s,0,'FRG_S02',1);p.reserve=['FRG_M01'];assert.ok(g.fusionOptions(s,0,[a.uid,b.uid]).every(x=>!x.resonance));p.reserve=[];const r=g.fusionOptions(s,0,[a.uid,b.uid])[0];assert.ok(r.resonance);g.fuse(s,0,[a.uid,b.uid],r.id);assert.equal(g.stats(p.field[0]).atk,by.get('FRG_S01').atk+10);p.hand=['FRG_S03'];assert.equal(g.fusionOptions(s,0,[p.field[0].uid,{handIndex:0}]).length,0);}
// Multi-target distinctness and missing removal/grave/deck targets never debit a card.
for(const id of ['FRG_S02','FRG_M02','SPI_S01','SPI_S02','SPI_M01','SPI_B01','CRY_S01','ECL_S03']){const {s,ref}=fresh(id);for(const p of s.players){p.grave=[];p.deck=[];for(const x of p.field.filter(Boolean))x.effects=[];}const old=structuredClone(s);assert.throws(()=>cast(s,0,ref),id);assert.deepEqual(s,old);}
{const {s,ref,a}=fresh('NIN_S03'),old=structuredClone(s);assert.throws(()=>cast(s,0,ref,{el_a:a.uid,el_b:a.uid}));assert.deepEqual(s,old);}
// Top-deck order and chosen single-effect removal are exact.
{const {s,ref}=fresh('CRY_S01'),p=s.players[0],before=[...p.deck];cast(s,0,ref,{el_d:2});assert.deepEqual(p.deck,[before[2],before[0],before[1],before[3]]);}
{const {s,ref,b}=fresh('FRG_S02');b.effects.push({key:'def',value:-15,until:4});cast(s,0,ref,{el_a:b.uid,el_fx:2});assert.ok(b.effects.some(e=>e.key==='def'&&e.value===-10));assert.ok(!b.effects.some(e=>e.key==='def'&&e.value===-15));}
{const {s,ref}=fresh('GHO_M02'),p=s.players[0],before=[...p.deck];cast(s,0,ref,{el_g:1,el_g2:0});assert.deepEqual(p.deck,[...before,'GHO_S01','SPI_S01']);assert.ok(p.grave.includes('GHO_M02'));}
// A conditional bonus does not make its false branch require a card in the deck.
{const {s,ref}=fresh('ECL_M01');s.players[0].deck=[];s.players[0].field[1].effects.push({key:'attribute',value:'水',until:4});cast(s,0,ref);assert.ok(s.players[0].field[0].effects.some(e=>e.key==='def'&&e.value===20));}
// Same skill recast does not stack, and next-opponent buffs expire on the following turn.
{const {s,ref,b}=fresh('DUA_S02'),base=by.get(b.id).def;cast(s,0,ref,{el_a:b.uid});s.players[0].skillUsed=false;s.players[0].hand=['DUA_S02'];cast(s,0,{handIndex:0},{el_a:b.uid});assert.equal(b.effects.filter(e=>e.source==='DUA_S02'&&e.key==='def').length,1);s.active=1;g.startTurn(s);assert.ok(b.effects.some(e=>e.source==='DUA_S02'));s.active=0;g.startTurn(s);assert.equal(g.stats(b).def,base);}
// The split debuff respects the existing one-use barrier.
{const {s,ref}=fresh('RUN_M02'),e=s.players[1].field[0],before=g.stats(e);s.players[1].teamEffects=[{key:'debuffShield',value:'def',starts:3,until:4}];cast(s,0,ref,{el_e:e.uid,el_e2:-1});assert.deepEqual(g.stats(e),before);assert.equal(s.players[1].teamEffects.length,0);}
// Negation consumes the declared hand exactly once, but does not grant any effect.
{const {s,ref,b}=fresh('FRG_S01');s.players[1].hand=['BFX023'];const before=g.stats(b);g.useSkill(s,0,ref,{el_a:b.uid});assert.ok(s.pending);g.useSkill(s,1,{handIndex:0},{});assert.equal(s.pending,null);assert.deepEqual(g.stats(b),before);assert.equal(s.players[0].grave.filter(id=>id==='FRG_S01').length,1);}
console.log('PASS priority/+10 cap, empty/duplicate targets, ordered grave/deck choices, nonstacking/expiry, lowering barrier, negation');
// End-to-end CPU battles with every new family in legal 45-card decks.
for(const family of ['ECL','DUA','GHO','NIN','FRG','CRY','RUN','SPI']){const cards=data.figures.filter(f=>f.family===family),old=release.starters[0].deck;const ids=[...cards.filter(f=>f.soulClass==='seed').flatMap(f=>[f.id,f.id]),...old.filter(id=>by.get(id).soulClass==='seed').slice(0,24),...cards.filter(f=>f.soulClass==='middle').flatMap(f=>[f.id,f.id]),...old.filter(id=>by.get(id).soulClass==='middle').slice(0,6),cards.find(f=>f.soulClass==='mob').id,...old.filter(id=>by.get(id).soulClass==='mob').slice(0,4)];assert.ok(g.validateSoulDeck(ids).valid);const s=g.createSoulBattle([ids,ids],undefined,{random:()=>.4});for(let turn=0;turn<160&&s.winner===null;turn++){const side=s.active,p=s.players[side];if(side===1)g.cpuMain(s);else while(p.field.includes(null)&&p.hand.some((_,i)=>g.canSummonHand(s,0,i)))g.summon(s,0,p.hand.findIndex((_,i)=>g.canSummonHand(s,0,i)),p.field.indexOf(null));resolve(s);if(s.winner!==null)break;g.beginBattle(s,side);for(let step=0;step<30&&s.winner===null;step++){let pair;for(const a of p.field.filter(Boolean))for(const d of s.players[1-side].field.filter(Boolean))if(!pair&&g.canAttack(s,side,a,d))pair=[a,d];if(!pair)break;g.attack(s,side,pair[0].uid,pair[1].uid);resolve(s);}if(s.winner===null)g.endTurn(s,side);}assert.notEqual(s.winner,null,family+' CPU stalled');}
console.log('PASS eight family CPU battles terminate with legal decks');
{const {s,ref,b}=fresh('DUA_S01');cast(s,0,ref,{el_a:b.uid});const e=s.players[1].field[0];b.permanentAtk+=300;g.beginBattle(s,0);g.attack(s,0,b.uid,e.uid);resolve(s);assert.equal(s.players[0].life,210);assert.ok(!b.effects.some(e=>e.key==='nextAttackHeal'));}
{const {s,ref,b}=fresh('DUA_M02');cast(s,0,ref);s.active=1;s.turn=4;s.phase='battle';const e=s.players[1].field[0];e.permanentAtk+=g.stats(b).def+30-g.stats(e).atk;g.attack(s,1,e.uid,b.uid);resolve(s);assert.equal(s.players[0].life,190);assert.ok(!s.players[0].teamEffects.some(e=>e.key==='damageReduce'));}
{const {s,ref,b}=fresh('RUN_M01');cast(s,0,ref,{el_a:b.uid,el_mode:'guard'});s.players[0].skillUsed=false;s.players[0].hand=['RUN_M01'];cast(s,0,{handIndex:0},{el_a:b.uid,el_mode:'advance'});const effects=b.effects.filter(e=>e.source==='RUN_M01');assert.deepEqual(effects.map(e=>[e.key,e.value,e.until]),[['atk',35,3],['def',-15,3]]);}
console.log('PASS next-attack heal, first positive battle damage reduction, opposite stance replacement/expiry');
