import assert from 'node:assert/strict';import{createRequire}from'node:module';import path from'node:path';import fs from'node:fs';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');const browser=await chromium.launch({headless:true,channel:'msedge'}),base=process.env.MPB_TEST_URL||'http://127.0.0.1:5192';
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('[data-initial-review]').first().click();await page.locator('[data-initial-confirm]').click();while(await page.locator('[data-comp="dismiss-notice"]').count())await page.locator('[data-comp="dismiss-notice"]').click();await page.goto(base+'/#figure');await page.locator('[data-family-claim]').waitFor();
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mob-piece-battle:profile:v1'))),old=await read();
 await page.evaluate(()=>{window.oldSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mob-piece-battle:profile:v1')throw Error('quota');return window.oldSetItem.call(this,k,v);};});await page.locator('[data-family-claim]').click();assert.deepEqual(await read(),old);assert.match(await page.locator('.toast').textContent(),/保存できません/);await page.evaluate(()=>{Storage.prototype.setItem=window.oldSetItem;});
 await page.locator('[data-family-claim]').evaluate(b=>{b.click();b.click();b.click();});const saved=await read();assert.equal(saved.familyCollectionVersion,1);assert.deepEqual(saved.soulDecks,old.soulDecks);for(const k of ['diamonds','rubies','coins','initialChoice','elementCollectionVersion'])assert.deepEqual(saved[k],old[k]);await page.reload();await page.locator('#figure-search').waitFor();assert.deepEqual(await read(),saved);
 const loaded=await page.evaluate(async()=>{const {familyIds}=await import('/src/game/family-collection.js'),{soulById}=await import('/src/game/soul-battle.js');return Promise.all([...familyIds].map(async id=>{const i=new Image;i.src=soulById.get(id).image;await i.decode();return {id,width:i.naturalWidth,height:i.naturalHeight};}));});assert.equal(loaded.length,24);assert.ok(loaded.every(x=>x.width===1254&&x.height===1254));
 await page.locator('#figure-search').fill('M4F_NEO');assert.equal(await page.locator('.soul-card').count(),6);await page.screenshot({path:'docs/families-collection-mobile.png'});await page.locator('[data-figure-info="M4F_NEO_V01"]').click();assert.ok(!(await page.locator('dialog').textContent()).includes('効果なし'));await page.screenshot({path:'docs/families-detail-mobile.png'});await page.keyboard.press('Escape');
 await page.goto(base+'/#battle-style');await page.locator('[data-battle-mat]').first().waitFor();assert.equal(await page.locator('[data-battle-mat]').count(),14);
 const fields=await page.evaluate(async()=>{const {fieldMats}=await import('/src/data/battle-style.js');return fieldMats.filter(x=>x.id.startsWith('field11-'));});
 for(const f of fields){await page.locator(`[data-battle-mat="${f.id}"]`).click();assert.equal((await read()).battleStyle.mat,f.id);assert.ok((await page.locator('.custom-battle-preview').getAttribute('style')).includes(f.image));await page.evaluate(async image=>{const i=new Image;i.src=image;await i.decode();if(i.naturalWidth!==1254)throw Error('field dimensions');},f.image);}
 await page.reload();assert.equal((await read()).battleStyle.mat,fields.at(-1).id);await page.screenshot({path:'docs/families-style-mobile.png'});
 const savedStyle=await read(),shots=[];
 for(const [width,height]of [[390,844],[375,667]]){await page.setViewportSize({width,height});for(const f of fields){await page.evaluate(async field=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{release}=await import('/src/game/initial-release.js'),{soulFigures}=await import('/src/game/soul-battle.js');const deck=[...release.starters[0].deck];deck[0]='M4F_MIM_V01';deck[1]='M4F_SIL_V01';deck[2]='M4F_NEO_V01';const p={owned:Object.fromEntries(soulFigures.map(f=>[f.id,25])),soulDecks:[deck,[],[],[],[]],soulDeckSlot:0,reducedMotion:true,battleStyle:{mat:field,fast:true,sound:false}};const random=Math.random;Math.random=()=>.999999;try{launchBattle({profile:p,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=random;}},f.id);
 await page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor({timeout:60000});await page.locator('[data-hand="0"]').click();await page.locator('[data-summon]').click();await page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor({timeout:60000});const bg=await page.locator('.duel-stage').evaluate(e=>getComputedStyle(e).backgroundImage);assert.ok(bg.includes(f.image),bg);const file=`docs/families-field-${f.id}-${width}.png`;await page.screenshot({path:file});shots.push(file);await page.locator('[data-quit]').click();await page.locator('[data-forfeit]').click();await page.locator('[data-close-result]').click();assert.deepEqual(await read(),savedStyle);}}
 await page.goto(base+'/#gacha');assert.equal(await page.locator('[data-banner]').count(),3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);fs.writeFileSync('docs/families-browser-results.json',JSON.stringify({images:loaded,fields:fields.map(f=>f.id),screenshots:shots,viewports:[[390,844],[375,667]],savePreserved:true,errors},null,2));console.log('PASS Edge: 24 PNGs; free claim storage failure/repeated clicks/reload; save/decks/currency preserved; 14 field choices; 11 fields in real battle at two mobile ratios; 3 banners; no page errors');
}finally{await browser.close();}
