import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import * as g from '../src/game/soul-battle.js';import data from '../src/data/family-additions.json' with {type:'json'};import audit from '../docs/families-source-audit.json' with {type:'json'};import plans from '../src/game/soul-skill-programs.js';import {prepareFamilyCollection}from '../src/game/family-collection.js';import {release}from '../src/game/initial-release.js';import catalog from '../src/data/soul-catalog.js';import {fieldMats,battleStyle,setBattleStyle} from '../src/data/battle-style.js';import fields from '../src/data/field-additions.json' with {type:'json'};
const deck=release.starters[0].deck,by=g.soulById;
const put=(s,side,id,slot)=>{const f={id,uid:++s.serial,attacks:0,skillTurn:-1,effects:[],attackedTargets:[],lastTarget:null,extra:0,mobFusion:false,permanentAtk:0,permanentDef:0};s.players[side].field[slot]=f;return f;};
function fresh(id,side=0,hand=true){const s=g.createSoulBattle([deck,deck]);s.active=side;s.turn=3;s.phase='main';for(const p of s.players){p.hand=[];p.field=[null,null,null];p.life=200;p.skillUsed=false;p.deck=['FRG_S01','SPI_S01','GHO_S01','FRG_S02'];p.grave=['SPI_S01','GHO_S01','SPI_M01'];p.destroyed=['GHO_S01'];}const a=put(s,side,id,0),b=put(s,side,'FRG_S01',1),c=put(s,side,'SPI_S01',2);for(const f of [a,b,c])f.effects.push({key:'atk',value:-5,until:4},{key:'def',value:-10,until:4});for(let i=0;i<3;i++){const e=put(s,1-side,['RUN_S02','CRY_S01','NIN_S01'][i],i);e.effects.push({key:'atk',value:20,until:4});}s.players[side].hand=[id,'FRG_S01'];return {s,ref:hand?{handIndex:0,id}:a.uid,a,b,c};}
const resolve=s=>{while(s.pending)g.passReaction(s,1-s.pending.side);};
const cast=(s,side,ref,o=g.cpuOptions(s,side,ref))=>{g.useSkill(s,side,ref,o);resolve(s);};
assert.equal(data.figures.length,24);assert.equal(new Set(data.figures.map(f=>f.id)).size,24);assert.equal(g.soulFigures.length,611);assert.equal(data.recipes.length,12);
for(const f of data.figures){assert.ok(plans[f.soulSkill.program]);assert.ok(f.tags.length<=catalog.rules.tagLimits[f.rarity]);assert.ok(f.tags.every(t=>catalog.tags.some(x=>x.id===t)));const row=audit.sources.find(x=>x.entry.endsWith('/'+f.id+'_figure.png'));assert.ok(row);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.image)).digest('hex'),row.sha256);}
let executions=0;
for(const f of data.figures)for(const side of [0,1])for(const hand of [false,true]){const {s,ref,a}=fresh(f.id,side,hand),p=s.players[side],enemy=1-side;p.deck=[f.id,'FRG_S01','SPI_S01'];p.life=300;const target=s.players[enemy].field[0];if(f.soulSkill.timing!=='own-main'){s.active=enemy;s.phase='battle';s.pending={kind:f.soulSkill.timing==='attack-response'?'attack':f.soulSkill.timing==='defeat-response'?'defeat':'skill',side:enemy,uid:target.uid,targetUid:a.uid,options:{},damage:10};}const o=g.cpuOptions(s,side,ref),before=structuredClone(s);g.skillChoices(s,side,ref,o);assert.deepEqual(s,before);assert.throws(()=>g.useSkill(s,side,{handIndex:0,id:'stale'},o));assert.deepEqual(s,before);cast(s,side,ref,o);assert.ok(p.skillUsed,f.id);assert.ok(s.events.some(e=>e.type==='skill'&&e.id===f.id&&e.fromHand===hand&&e.effect));if(hand)assert.equal(p.grave.filter(id=>id===f.id).length,1);executions++;}
console.log('PASS '+executions+' actual skills: both sides, hand/field, reaction timing, cancellation and stale references');
for(const r of data.recipes)for(const side of [0,1])for(const hand of [false,true]){const {s}=fresh('FRG_S01',side),p=s.players[side];p.field=[null,null,null];const a=put(s,side,r.materials[0].id,0);p.hand=[r.materials[1].id];const refs=[a.uid,hand?{handIndex:0}:put(s,side,r.materials[1].id,1).uid];p.reserve=[r.target];assert.ok(g.fusionOptions(s,side,refs).some(x=>x.id===r.id));g.fuse(s,side,refs,r.id);assert.equal(p.field[0].id,r.target);assert.deepEqual(g.stats(p.field[0]),{atk:by.get(r.target).atk,def:by.get(r.target).def});assert.ok(r.materials.every(m=>p.grave.includes(m.id)));}
console.log('PASS 12 recipes x both sides x hand/field; ordinary fusion has no unrequested bonus');
const old={owned:{'01':12,'BFX046':2},diamonds:321,rubies:32,coins:98,soulDecks:release.starters.map(s=>s.deck),soulDeckSlot:1,lastDraw:{keep:true}},before=structuredClone(old),next=prepareFamilyCollection(old);assert.deepEqual(old,before);for(const k of Object.keys(old).filter(k=>k!=='owned'))assert.deepEqual(next[k],old[k]);for(const [id,n]of Object.entries(old.owned))assert.equal(next.owned[id],n);for(const f of data.figures)assert.equal(next.owned[f.id],f.soulClass==='mob'?1:2);assert.throws(()=>prepareFamilyCollection(next));
assert.equal(release.starters.length,3);assert.equal(release.banners.length,3);console.log('PASS explicit free acquisition, sufficient shared fusion seeds, no currency/deck/save overwrite, idempotence; three starters/banners unchanged');
for(const family of ['MIM','SIL','NEO','DOK']){const {s}=fresh('M4F_'+family+'_V01'),p=s.players[0];p.field=[null,null,null];const a=put(s,0,'M4F_'+family+'_V01',0),b=put(s,0,'M4F_'+family+'_V02',1);p.reserve=['M4F_'+family+'_M01'];assert.ok(g.fusionOptions(s,0,[a.uid,b.uid]).every(x=>!x.resonance));p.reserve=[];const r=g.fusionOptions(s,0,[a.uid,b.uid])[0];assert.ok(r.resonance);g.fuse(s,0,[a.uid,b.uid],r.id);assert.equal(g.stats(p.field[0]).atk,by.get(a.id).atk+10);p.hand=['M4F_'+family+'_V03'];assert.equal(g.fusionOptions(s,0,[p.field[0].uid,{handIndex:0}]).length,0);}
assert.equal(fieldMats.length,14);assert.equal(new Set(fieldMats.map(f=>f.id)).size,14);for(const f of fields){const row=audit.sources.find(x=>x.entry.endsWith('/'+f.image.split('/').at(-1)));assert.equal(crypto.createHash('sha256').update(fs.readFileSync('public/'+f.image)).digest('hex'),row.sha256);const p={battleStyle:{cube:'shadow',mat:'ice',fast:true,sound:true}};setBattleStyle(p,'mat',f.id);assert.equal(battleStyle(p).mat.id,f.id);assert.equal(p.battleStyle.cube,'shadow');assert.equal(p.battleStyle.fast,true);assert.equal(p.battleStyle.sound,true);}for(const id of ['inferno','ice','verdant'])assert.equal(battleStyle({battleStyle:{mat:id}}).mat.id,id);
console.log('PASS fusion priority/+10 cap, eleven original backgrounds and fourteen selections, existing style settings retained');
for(const family of ['MIM','SIL','NEO','DOK']){const cards=data.figures.filter(f=>f.family===family),old=release.starters[0].deck;const ids=[...cards.filter(f=>f.soulClass==='seed').flatMap(f=>[f.id,f.id]),...old.filter(id=>by.get(id).soulClass==='seed').slice(0,24),...cards.filter(f=>f.soulClass==='middle').flatMap(f=>[f.id,f.id]),...old.filter(id=>by.get(id).soulClass==='middle').slice(0,6),cards.find(f=>f.soulClass==='mob').id,...old.filter(id=>by.get(id).soulClass==='mob').slice(0,4)];assert.ok(g.validateSoulDeck(ids).valid);const s=g.createSoulBattle([ids,ids],undefined,{random:()=>.4});for(let turn=0;turn<160&&s.winner===null;turn++){const side=s.active,p=s.players[side];if(side===1)g.cpuMain(s);else while(p.field.includes(null)&&p.hand.some((_,i)=>g.canSummonHand(s,0,i)))g.summon(s,0,p.hand.findIndex((_,i)=>g.canSummonHand(s,0,i)),p.field.indexOf(null));resolve(s);if(s.winner!==null)break;g.beginBattle(s,side);for(let step=0;step<30&&s.winner===null;step++){let pair;for(const a of p.field.filter(Boolean))for(const d of s.players[1-side].field.filter(Boolean))if(!pair&&g.canAttack(s,side,a,d))pair=[a,d];if(!pair)break;g.attack(s,side,pair[0].uid,pair[1].uid);resolve(s);}if(s.winner===null)g.endTurn(s,side);}assert.notEqual(s.winner,null,family+' CPU stalled');}
console.log('PASS four family CPU battles terminate with legal decks');
