import fs from 'node:fs';
import figures from '../src/data/figures_master_v170.json' with {type:'json'};
import {pieceInventoryFigures} from '../src/data/piece-catalog.js';
const paths=[...figures,...pieceInventoryFigures].map(f=>f.image).filter(p=>fs.existsSync(p));
fs.writeFileSync(new URL('../src/data/available-assets.js',import.meta.url),'// Generated by scripts/index-assets.mjs; original figure paths stay unchanged.\nexport const availableAssets=new Set('+JSON.stringify([...new Set(paths)])+');\n');
