import assert from 'node:assert/strict';import {createRequire} from 'node:module';import path from 'node:path';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});const base=process.env.MPB_TEST_URL||'http://127.0.0.1:5173';
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#figure');await page.locator('#figure-collection').waitFor();while(await page.locator('[data-comp="dismiss-notice"]').count())await page.locator('[data-comp="dismiss-notice"]').click();assert.equal(await page.locator('.soul-card').count(),207);
 const images=await page.evaluate(async()=>{const {materialFigures}=await import('/src/data/piece-catalog.js');return Promise.all(materialFigures.map(f=>new Promise(r=>{const im=new Image();im.onload=()=>r(im.naturalWidth>0);im.onerror=()=>r(false);im.src=f.image;})));});assert.equal(images.length,135);assert.ok(images.every(Boolean));
 await page.selectOption('#figure-collection','collab');assert.equal(await page.locator('.soul-card').count(),302);await page.selectOption('#figure-collection','ALL');assert.equal(await page.locator('.soul-card').count(),509);
 await page.selectOption('#figure-collection','main');await page.locator('#figure-search').fill('モブサンゴ');await page.waitForTimeout(300);await page.screenshot({path:'docs/materials-figure-mobile.png'});
 await page.goto(base+'/#deck');assert.equal(await page.locator('[data-piece-starter]').count(),11);for(const id of ['materials-ocean','materials-sweets','materials-mouth','materials-balloon']){await page.locator(`[data-piece-starter="${id}"]`).click();assert.match(await page.locator('.soul-deck-count').textContent(),/45 \/ 45/);}
 await page.reload();assert.match(await page.locator('.soul-deck-count').textContent(),/45 \/ 45/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mob-piece-battle:profile:v1')));assert.equal(saved.pieceCollectionVersion,2);const old={...saved,pieceCollectionVersion:1,owned:{'01':12,'16':2,'piece:049':4},soulDecks:[['16'],['piece:049'],[],[],[]],diamonds:444,coins:555,rubies:66,testMode:false,centerId:'16'};
 await page.evaluate(v=>localStorage.setItem('mob-piece-battle:profile:v1',JSON.stringify(v)),old);await page.reload();const migrated=await page.evaluate(()=>JSON.parse(localStorage.getItem('mob-piece-battle:profile:v1')));for(const k of ['soulDecks','diamonds','coins','rubies','centerId'])assert.deepEqual(migrated[k],old[k],k);for(const [id,n]of Object.entries(old.owned))assert.equal(migrated.owned[id],n);assert.ok(migrated.owned.NS001>=2);await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mob-piece-battle:profile:v1')).owned),migrated.owned);
 await page.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{grantMainCollection,applyPieceStarter}=await import('/src/game/piece-starters.js');const profile={owned:{},reducedMotion:true};grantMainCollection(profile,{newProfile:true});applyPieceStarter(profile,'materials-balloon');const random=Math.random;Math.random=()=>.999999;try{window.materialBattle=launchBattle({profile,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=random;}});
 await page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor();assert.match(await page.locator('.duel-player.side-1').textContent(),/バルーンスターター/);
 for(let i=0;i<2;i++){await page.locator('[data-hand="0"]').click();await page.locator('[data-summon]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();}
 for(let i=0;i<2;i++){await page.locator('.duel-field.side-0 [data-piece]').nth(i).click();await page.locator('[data-material]').click();}
 await page.locator('[data-recipe="BALLOON-026-026"]').click();await page.locator('[data-fuse]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();assert.match(await page.locator('.duel-field.side-0').textContent(),/モブコケネ/);
 await page.locator('.duel-field.side-0 [data-piece]').click();await page.locator('[data-skill]').click();await page.locator('[data-skill-confirm]').click();await page.locator('.duel-dialog:not(.fx-running)').waitFor();assert.match(await page.locator('.duel-budget').textContent(),/使用済み/);await page.screenshot({path:'docs/materials-balloon-fusion-mobile.png'});assert.deepEqual(errors,[]);
 console.log('PASS browser: all135 images; 207/302/509 collection; 11 starter buttons; 4 selections/reload; v1 save migration; enemy starter; same-color balloon fusion and skill UI; no page errors');
}finally{await browser.close();}

