import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import * as g from '../src/game/soul-battle.js';import catalog from '../src/data/soul-catalog.js';import data from '../src/data/oct05-additions.json' with {type:'json'};import spec from '../src/data/oct05-spec.json' with {type:'json'};import {freeEnemies} from '../src/game/free-enemies.js';import {buildAceDeck} from '../src/game/ace-deck.js';import {fusionRecommendations,countIds} from '../src/game/soul-deck-assist.js';import {acquisitionText}from'../src/game/acquisition.js';import {release}from'../src/game/initial-release.js';import {availableDeckOwned}from'../src/game/deck-legality.js';import {matchesMaterial,recipeMaterialClass}from'../src/game/fusion-rules.js';
const by=g.soulById,owned=Object.fromEntries(g.soulFigures.map(f=>[f.id,f.soulClass==='seed'?3:1])),all={owned,soulDecks:[[],[],[],[],[]],soulDeckSlot:0};
assert.equal(data.figures.length,62);assert.equal(g.soulFigures.length,673);assert.equal(new Set(g.soulFigures.map(f=>f.id)).size,673);
for(const f of data.figures){assert.ok(fs.existsSync(f.image),f.image);assert.ok(f.tags.every(t=>catalog.tags.some(x=>x.id===t)));assert.ok(f.tags.length<=catalog.rules.tagLimits[f.rarity]);assert.ok(acquisitionText(f.id).includes('ガチャ：'));assert.ok(Number.isFinite(f.atk)&&Number.isFinite(f.def));if(f.soulClass!=='seed')assert.ok(fusionRecommendations(f.id,owned).length,'New figure unreachable '+f.id);}
for(const p of spec.patches){const f=by.get(p.id);if(p.soulClass)assert.equal(f.soulClass,p.soulClass);if(p.rarity)assert.equal(f.rarity,p.rarity);for(const t of p.explicitTags)assert.ok(f.tags.includes(t),p.id+' lost specified tag '+t);}
console.log('PASS 62 real images, unique IDs, specified stats/classes/rarities/tags, acquisition and full fusion paths');
const seed=g.soulFigures.find(f=>f.soulClass==='seed'),mid=g.soulFigures.find(f=>f.soulClass==='middle'),mob=g.soulFigures.find(f=>f.soulClass==='mob');
for(const[f,n]of[[seed,3],[mid,1],[mob,1]]){assert.equal(g.validateSoulDeck(Array(n).fill(f.id),owned).errors.length,0);assert.ok(g.validateSoulDeck(Array(n+1).fill(f.id),owned).errors.length);}
const old={...structuredClone(all),soulDecks:[[seed.id,seed.id,seed.id,seed.id],[seed.id],[],[],[]]},before=structuredClone(old);assert.deepEqual(g.ensureSoulDecks(old),before.soulDecks[0]);assert.deepEqual(old,before);assert.throws(()=>g.setSoulDeck(old,[...old.soulDecks[0],mid.id]));assert.deepEqual(old,before);const repaired=g.prepareSoulDeck(old,[seed.id,seed.id,seed.id]);assert.equal(repaired.soulDecks[0].length,3);assert.deepEqual(old,before);assert.throws(()=>g.prepareSoulDeck(old,[mid.id,seed.id]));assert.equal(g.validateSoulDeck([seed.id],owned,{profile:old,slot:2}).errors.length,0);assert.equal(availableDeckOwned(old)[seed.id],0);
assert.equal(fs.existsSync('src/game/oct05-collection.js'),false);assert.ok(!fs.readFileSync('src/app.js','utf8').includes('data-oct05-claim'));assert.deepEqual(old,before);
const p=structuredClone(all),snapshot=structuredClone(p),aceIds=['NS2_050','NS2_051','NS2_052','NS2_053','NS2_054'],built=buildAceDeck(p,aceIds);assert.ok(g.validateSoulDeck(built.deck,p.owned,{profile:p}).valid);for(const id of aceIds)assert.ok(built.deck.includes(id));assert.deepEqual(p,snapshot);assert.throws(()=>buildAceDeck(p,aceIds.slice(1)));assert.throws(()=>buildAceDeck({...p,owned:{}},aceIds));const reserved=structuredClone(p);reserved.soulDecks[1]=[aceIds[0]];assert.throws(()=>buildAceDeck(reserved,aceIds));console.log('PASS per-ID 3/1/1 limits, slots 1/2 only, old-save preservation/repair, five aces, no inventory grants, no unapproved acquisition handler');
const deck=release.starters[0].deck;
function fresh(){const s=g.createSoulBattle([deck,deck],undefined,{random:()=>.9});s.turn=3;s.phase='main';for(const p of s.players){p.field=[null,null,null];p.hand=[];p.life=200;p.grave=[];p.deck=['NS2_002','NS2_003','NS2_004'];}return s;}
function put(s,side,id,slot=0){const f={id,uid:++s.serial,summonTurn:s.turn,attacks:0,skillTurn:-1,effects:[],attackedTargets:[],lastTarget:null,extra:0,mobFusion:false,permanentAtk:0,permanentDef:0};s.players[side].field[slot]=f;return f;}
function resolve(s){for(let i=0;i<12&&s.pending;i++)g.passReaction(s,1-s.pending.side);assert.equal(s.pending,null);if(g.evolutionOptions(s).event)g.resolveEvolution(s,g.evolutionOptions(s).event.side,null);}
for(const side of[0,1]){
 let s=fresh();s.active=side;let f=put(s,side,'NS2_029');s.players[1-side].grave=['NS2_002','NS2_003'];g.useSkill(s,side,f.uid);resolve(s);assert.equal(s.players[side].field[0],null);assert.ok(s.players[side].grave.includes(f.id));
 s=fresh();s.active=side;f=put(s,side,'NS2_030');s.players[side].hand=['NS2_002'];let initial=g.stats(f).def;assert.throws(()=>g.useSkill(s,side,f.uid,{costHandIndex:55}));assert.equal(s.players[side].hand.length,1);g.useSkill(s,side,f.uid,{costHandIndex:0});resolve(s);assert.equal(g.stats(f).def,initial+50);assert.equal(s.players[side].hand.length,0);
 for(const id of['NS2_033','NS2_045','mq:figene/74']){s=fresh();s.active=side;f=put(s,side,id);const target=id==='mq:figene/74'?'mq:figene/73':'NS2_034',a=put(s,side,target,1),b=put(s,1-side,target),n=g.stats(a).atk;s.players[side].hand=['NS2_002','NS2_003'];g.useSkill(s,side,f.uid);resolve(s);assert.equal(g.stats(a).atk,n+(id==='mq:figene/74'?30:20));assert.equal(g.stats(b).atk,n+(id==='mq:figene/74'?30:20));if(id==='NS2_045')assert.equal(s.players[side].life,220);}
 s=fresh();s.active=side;f=put(s,side,'mq:figene/73');let enemy=put(s,1-side,'NS2_002');enemy.permanentDef=999;initial=g.stats(f).atk;g.beginBattle(s,side);g.attack(s,side,f.uid,enemy.uid);resolve(s);assert.equal(g.stats(f).atk,initial+20);
 for(const id of['NS2_001','NS2_005','NS2_032']){s=fresh();s.active=side;f=put(s,side,'NS2_031');enemy=put(s,1-side,id);f.permanentAtk=200;const other=s.players[1-side];other.deck=id==='NS2_005'?['NS2_006']:['NS2_002'];other.grave=['NS2_003','NS2_004'];g.beginBattle(s,side);g.attack(s,side,f.uid,enemy.uid);resolve(s);assert.equal(s.players[side].life,225);assert.equal(other.field.filter(Boolean).length,id==='NS2_032'?2:1);}
 for(const id of['NS2_034','NS2_035']){s=fresh();s.active=side;f=put(s,side,'NS2_002');enemy=put(s,1-side,id);s.players[1-side].hand=['NS2_003'];g.beginBattle(s,side);const atk=g.stats(f).atk;g.attack(s,side,f.uid,enemy.uid);g.useSkill(s,1-side,enemy.uid,id==='NS2_034'?{costHandIndex:0}:{});resolve(s);if(id==='NS2_035')assert.equal(g.stats(f).atk,Math.max(0,atk-20));else assert.equal(s.players[1-side].hand.length,0);}
 s=fresh();s.active=side;f=put(s,side,'NS2_037');s.players[side].grave=['NS2_036'];s.players[side].reserve=['NS2_040'];const refs=[f.uid,{graveIndex:0}],r=g.fusionOptions(s,side,refs).find(r=>r.target==='NS2_040');assert.ok(r);g.fuse(s,side,refs,r.id);assert.equal(s.players[side].field[0].id,'NS2_040');assert.equal(s.players[side].grave.filter(id=>id==='NS2_036').length,1);
 s=fresh();s.active=side;const a=put(s,side,'NS2_001'),b=put(s,side,'NS2_021',1);s.players[side].reserve=['NS2_050'];assert.ok(g.fusionOptions(s,side,[a.uid,b.uid]).every(r=>by.get(r.target).soulClass!=='mob'));
}
console.log('PASS both sides: immediate self-destruction, atomic discard, team tag buffs, heal, attack ramp, death summons/revive, counter debuff, grave fusion and no seed-to-MOB');
assert.equal(freeEnemies.length,10);assert.equal(new Set(freeEnemies.map(e=>JSON.stringify(e.deck))).size,10);for(const e of freeEnemies){assert.ok(g.validateSoulDeck(e.deck).valid);for(const id of e.aces)assert.ok(e.deck.includes(id));const s=g.createSoulBattle([deck,e.deck],undefined,{random:()=>.41});s.cpuStrategy=e.strategy;s.cpuThemeTags=e.themeTagIds;for(let step=0;step<800&&s.winner===null;step++){resolve(s);if(s.winner!==null)break;if(s.active===1){if(s.phase==='main'){g.cpuMain(s);resolve(s);if(s.winner!==null)break;g.beginBattle(s,1);}else g.cpuAttack(s);}else{if(s.phase==='main'){const p=s.players[0];while(p.field.includes(null)&&p.hand.some((_,i)=>g.canSummonHand(s,0,i)))g.summon(s,0,p.hand.findIndex((_,i)=>g.canSummonHand(s,0,i)),p.field.indexOf(null));g.beginBattle(s,0);}else{let pair;for(const a of s.players[0].field.filter(Boolean))for(const d of s.players[1].field.filter(Boolean))if(!pair&&g.canAttack(s,0,a,d))pair=[a,d];if(pair)g.attack(s,0,pair[0].uid,pair[1].uid);else g.endTurn(s,0);}}}assert.notEqual(s.winner,null,e.id+' stalled');}
console.log('PASS ten distinct legal theme decks, CPU strategy execution and completed battles');
