import {towerStarters} from '../src/data/tower.js';
import {matchesMaterial} from '../src/game/fusion-rules.js';
import {oct06RetiredIds} from '../src/data/oct06-spec.js';
import expansion from '../docs/oct05-gacha-manifest.json' with {type:'json'};
import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {release,initializeInitialRelease} from '../src/game/initial-release.js';import {banners,poolFor,ratesFor,drawRarityRate,drawFigureRate,RATES,TEN_LAST_RATES,SPECIAL_RATES} from '../src/data/gacha.js';import {soulById as by,recipes,validateSoulDeck} from '../src/game/soul-battle.js';import {acquisitionText} from '../src/game/acquisition.js';import manifest from '../docs/pools75-manifest.json' with {type:'json'};
assert.deepEqual(RATES,{R:50,SR:30,SSR:15,UR:4.5,MOB:.5});assert.deepEqual(TEN_LAST_RATES,{SR:67,SSR:25,UR:7,MOB:1});assert.deepEqual(SPECIAL_RATES,{pickup:.02,allSSR:.001});assert.equal(release.version,1);assert.equal(banners.length,5);
const matches=matchesMaterial;
const result=[];
for(const b of banners){const pool=poolFor(b),record={added:b.extraIds||b.figureIds};assert.equal(pool.length,b.figureIds.length);assert.equal(new Set(b.figureIds).size,pool.length);assert.equal(record.added.length,b.requiresClear?30:b.figureIds.length);if(b.requiresClear)for(let i=1;i<=31;i++)assert.ok(b.figureIds.includes(String(i).padStart(2,'0')));for(const f of pool){assert.ok(by.has(f.sourceId));assert.ok(fs.existsSync(f.image));assert.ok(!/pixel|ドット|reference/.test(f.image));assert.ok(by.get(f.sourceId).soulSkill.program!==null);assert.ok(acquisitionText(f.sourceId).includes(b.name));}
 for(const count of [1,10])for(let index=0;index<count;index++){assert.ok(Math.abs(pool.reduce((sum,f)=>sum+drawFigureRate(b,f,count,index),0)-1)<1e-10);const base=ratesFor(b,count===10&&index===9),ssr=ratesFor(b,'SSR'),pickup=pool.find(f=>f.sourceId===b.pickupIds[0]);for(const rarity of Object.keys(RATES)){const expected=.979*(base[rarity]||0)+.02*(index===count-1?Number(pickup.rarity===rarity):(base[rarity]||0))+.001*(ssr[rarity]||0);assert.ok(Math.abs(drawRarityRate(b,rarity,count,index)-expected)<1e-10);}}
 const reached=new Set([...towerStarters.flatMap(s=>s.deck),...banners.filter(x=>b.requiresClear||!x.requiresClear).flatMap(x=>poolFor(x)).filter(f=>by.get(f.sourceId).soulClass==='seed').map(f=>f.sourceId)]);for(let i=0;i<5;i++)for(const r of recipes){if(!b.figureIds.includes(r.target))continue;const materials=[...reached].map(id=>by.get(id)).filter(f=>r.special||f.soulClass===r.fromClass);if(r.materials.every(m=>materials.some(f=>matches(f,m))))reached.add(r.target);}
 for(const id of record.added)assert.ok(reached.has(id),'New fusion inaccessible '+id);const unreachable=b.figureIds.filter(id=>!reached.has(id));result.push({id:b.id,reachable:reached.size,unreachable,normalRarityRates:ratesFor(b),singleActualRarityRates:Object.fromEntries(Object.keys(RATES).map(r=>[r,drawRarityRate(b,r)])),tenthActualRarityRates:Object.fromEntries(Object.keys(RATES).map(r=>[r,drawRarityRate(b,r,10,9)]))});
}
for(const [i,s]of release.starters.entries()){assert.ok(validateSoulDeck(s.deck).valid);assert.equal(s.deck.length,45);assert.ok(s.deck.some(id=>by.get(id).family));assert.ok(s.deck.every(id=>release.banners[i].figureIds.includes(id)));const old={initialChoice:{version:1,state:'claimed',starterId:s.id},soulDecks:[manifest.starters[i].oldDeck,[],[],[],[]],owned:{'01':12},diamonds:200,rubies:33,coins:999,elementCollectionVersion:1,familyCollectionVersion:1,lastDraw:{bannerId:banners[i].id,entries:[{id:'BFX001'}]},gachaStats:{draws:39,converted:2,rubiesFromConversion:4}},before=structuredClone(old);assert.equal(initializeInitialRelease(old),false);assert.deepEqual(old,before);}
fs.writeFileSync('docs/tower-pools-verification.json',JSON.stringify(result,null,2));console.log('PASS Three limited starter boosters and two later tower pools: unchanged rarity/special/guarantee rules, 100% sums, fusion closure using granted starters, archived starters and claimed saves preserved');console.log(JSON.stringify(result.map(({id,reachable,unreachable})=>({id,reachable,unreachable}))));
