const output=process.env.MPB_TEST_OUTPUT||'artifacts/tower';fs.mkdirSync(output,{recursive:true});
const base=process.env.MPB_TEST_URL||'http://127.0.0.1:5173';
import fs from 'node:fs';
import {createRequire} from 'node:module';import path from 'node:path';import assert from 'node:assert/strict';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
try{const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>document.documentElement.dataset.mpbReady==='1');
await p.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{towerStarters,towerEnemy}=await import('/src/data/tower.js'),{soulFigures}=await import('/src/game/soul-battle.js');const deck=[...towerStarters[0].deck];for(const id of ['ECL_S02','ECL_S01']){deck.splice(deck.indexOf(id),1);deck.unshift(id);}const profile={owned:Object.fromEntries(soulFigures.map(f=>[f.id,25])),soulDecks:[deck,[],[],[],[]],soulDeckSlot:0,centerId:'ECL_S01',reducedMotion:true};const old=Math.random;Math.random=()=>.999999;try{window.strengthDone=launchBattle({profile,request:{enemy:towerEnemy(1)},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=old;}});
const idle=async()=>{for(let i=0;i<180;i++){await p.locator('[data-fx-skip]').evaluateAll(bs=>bs.forEach(b=>b.click()));await p.waitForTimeout(40);if(await p.locator('.duel-dialog').count()&&!await p.locator('.duel-dialog.fx-running').count())return;}throw Error('animation timeout');};
await p.locator('.duel-screen').waitFor();await idle();await p.locator('[data-hand="0"]').click();await p.locator('[data-summon]').click();await idle();
const field=p.locator('.side-0 [data-piece]');assert.equal(await field.count(),1);assert.ok(await p.locator('[data-hand].fusion-ready').count());await field.first().click();assert.equal(await p.locator('[data-recipe]').count(),0);await p.locator('[data-inspect]').click();await p.locator('.duel-detail-figure').waitFor();assert.equal(await p.locator('[data-recipe]').count(),0);await p.locator('.duel-sheet [data-sheet-close]').first().click();assert.equal(await p.locator('[data-recipe]').count(),0);
const handBefore=await p.locator('[data-hand]').count(),statsBefore=await field.first().getAttribute('aria-label');await p.locator('[data-tap-move]').click();await p.locator('[data-hand="0"]').click();await p.locator('[data-recipe]').first().waitFor();assert.ok(await p.locator('[data-recipe="SET2_FUS_ECL_M02"]').count());assert.equal(await p.locator('[data-recipe^="resonance:"]').count(),2);await p.screenshot({path:path.join(output,'strengthen-choice-390.png')});await p.locator('.duel-sheet [data-sheet-close]').first().click();assert.equal(await p.locator('[data-hand]').count(),handBefore);assert.equal(await field.first().getAttribute('aria-label'),statsBefore);
await p.locator('[data-tap-move]').click();await p.locator('[data-hand="0"]').click();await p.locator('[data-recipe^="resonance:1:"]').click();await p.locator('[data-fuse]').dblclick({delay:10});await idle();assert.equal(await field.count(),1);assert.equal(await p.locator('[data-hand]').count(),handBefore-1);assert.match(await field.first().getAttribute('aria-label'),/モブミカゲ ATK 75 DEF 95/);await p.screenshot({path:path.join(output,'strengthen-survivor-390.png')});
await p.evaluate(()=>{location.hash='home';});await p.waitForFunction(()=>!document.querySelector('.duel-dialog'));assert.deepEqual(errors,[]);console.log('PASS browser: inspect does not choose materials; dedicated and two strengthening choices coexist; cancellation unchanged; chosen hand survivor +15; double confirm consumes once; navigation cleanup');
}finally{await browser.close();}
