import assert from 'node:assert/strict';import * as g from '../src/game/soul-battle.js';import {towerStarters,towerEnemy} from '../src/data/tower.js';
const fresh=()=>{const s=g.createSoulBattle([towerStarters[0].deck,towerStarters[1].deck]);s.turn=5;s.active=0;s.phase='main';s.players[0].field=[null,null,null];s.players[0].hand=[];s.players[0].reserve=[];return s;};
const put=(s,id,slot=0)=>s.players[0].field[slot]={id,uid:++s.serial,summonTurn:1,attacks:0,skillTurn:-1,skillUsesUsed:0,effects:[],attackedTargets:[],lastTarget:null,extra:0,mobFusion:false,permanentAtk:0,permanentDef:0};
const match=(a,b)=>({attr:a.attribute.split('/').some(x=>b.attribute.split('/').includes(x)),tag:a.tags.some(t=>b.tags.includes(t))});
const pool=g.soulFigures.filter(f=>!f.passive&&f.soulClass==='seed');let cases=[];for(const flags of [[true,false],[false,true],[true,true],[false,false]]){let pair;for(const a of pool){const b=pool.find(b=>b.id!==a.id&&match(a,b).attr===flags[0]&&match(a,b).tag===flags[1]);if(b){pair=[a,b];break;}}assert.ok(pair);cases.push({pair,bonus:flags.every(Boolean)?30:flags.some(Boolean)?15:0});}
for(const {pair,bonus}of cases)for(const hand of [false,true])for(const index of [0,1]){const s=fresh(),p=s.players[0],a=put(s,pair[0].id),b=hand?(p.hand=[pair[1].id],{handIndex:0}):put(s,pair[1].id,1).uid;const refs=[a.uid,b],before=JSON.stringify(s),opts=g.fusionOptions(s,0,refs);assert.equal(JSON.stringify(s),before);const r=opts.find(r=>r.resonance&&r.baseIndex===index);if(!bonus){assert.ok(!r);continue;}assert.equal(r.bonusATK,bonus);assert.equal(r.bonusDEF,bonus);const original=index===0?a:hand?null:p.field[1];if(original){original.skillUsesUsed=1;original.skillTurn=4;original.permanentAtk=7;original.permanentDef=-5;original.effects=[{key:'atk',value:-10,until:6},{key:'fusionLock',value:false,until:6}];original.attacks=1;}
 else p.handBonuses=[{id:pair[1].id,index:0,skillUsesUsed:1,skillTurn:4}];
 const reserves=[...p.reserve];g.fuse(s,0,refs,r.id);const survivor=p.field.find(f=>f?.id===pair[index].id);assert.ok(survivor);assert.equal(survivor.skillUsesUsed,1);assert.equal(g.soulById.get(survivor.id).soulClass,'seed');assert.equal(survivor.permanentAtk,(original?7:0)+bonus);assert.equal(survivor.permanentDef,(original?-5:0)+bonus);if(original){assert.deepEqual(survivor.effects,original.effects);assert.equal(survivor.attacks,1);}assert.equal(p.grave.length,1);assert.equal(p.field.filter(Boolean).length,1);assert.deepEqual(p.reserve,reserves);assert.throws(()=>g.fuse(s,0,refs,r.id));}
// Same-ID resets only skill budget, adds +30 once despite all shared tags/attributes.
{const s=fresh(),a=put(s,'01');a.skillUsesUsed=1;a.skillTurn=4;a.permanentAtk=12;a.effects=[{key:'def',value:-10,until:6}];s.players[0].hand=['01'];const refs=[a.uid,{handIndex:0}],r=g.fusionOptions(s,0,refs).find(r=>r.baseIndex===0);assert.equal(r.bonusATK,30);g.fuse(s,0,refs,r.id);const f=s.players[0].field[0];assert.equal(f.skillUsesUsed,0);assert.equal(f.skillTurn,-1);assert.equal(f.permanentAtk,42);assert.deepEqual(f.effects,a.effects);}
// Dedicated evolution remains selectable and resets budget as before.
{const s=fresh(),a=put(s,'ECL_S01'),b=put(s,'ECL_S02',1);a.skillUsesUsed=1;a.skillTurn=4;s.players[0].reserve=['ECL_M02'];const refs=[a.uid,b.uid],opts=g.fusionOptions(s,0,refs);assert.ok(opts.some(r=>r.resonance));const explicit=opts.find(r=>!r.resonance&&r.target==='ECL_M02');assert.ok(explicit);g.fuse(s,0,refs,explicit.id);assert.equal(s.players[0].field[0].id,'ECL_M02');assert.equal(s.players[0].field[0].skillUsesUsed,0);assert.equal(s.players[0].grave.length,2);}
// Mixed stages preserve whichever ID was selected, including its skill limit.
for(const index of [0,1]){const s=fresh(),a=put(s,'ECL_S01'),b=put(s,'ECL_M02',1);b.skillUsesUsed=1;b.skillTurn=4;const refs=[a.uid,b.uid],r=g.fusionOptions(s,0,refs).find(r=>r.baseIndex===index);assert.ok(r);g.fuse(s,0,refs,r.id);const f=s.players[0].field.find(Boolean);assert.equal(f.id,index?'ECL_M02':'ECL_S01');assert.equal(g.skillBudget(s,0,f.uid).limit,index?2:1);assert.equal(f.skillUsesUsed,index?1:0);}
{const s=fresh(),a=put(s,'01');s.players[0].hand=['02'];a.skillTurn=s.turn;assert.equal(g.fusionOptions(s,0,[a.uid,{handIndex:0}]).length,0);a.skillTurn=-1;a.effects=[{key:'fusionLock',value:true,until:s.turn}];assert.equal(g.fusionOptions(s,0,[a.uid,{handIndex:0}]).length,0);assert.equal(g.fusionOptions(s,0,[{handIndex:0},{handIndex:1}]).length,0);}
// Highlight candidates now include legal tag-based and mixed-stage hand pairs.
{const s=fresh(),a=put(s,'ECL_S01');s.players[0].hand=['ECL_S02','ECL_M02'];assert.deepEqual([...g.fusionReadyMaterials(s,0).hand],[0,1]);assert.ok(g.fusionReadyMaterials(s,0).field.has(a.uid));}
console.log('PASS strengthening: +15/+30, both survivors, field/hand, mixed stages, budget/state carry, explicit choice, cancellation/no mutation, single consumption, duplicate rejection and highlighting');
