import assert from 'node:assert/strict';import {createRequire} from 'node:module';import path from 'node:path';
const require=createRequire(path.resolve(path.dirname(process.execPath),'../node_modules/package.json')),{chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),base=process.env.MPB_TEST_URL||'http://127.0.0.1:5187';
try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/#home');
 while(await page.locator('[data-comp="dismiss-notice"]').count())await page.locator('[data-comp="dismiss-notice"]').click();
 const loaded=await page.evaluate(async()=>{const {soulFigures}=await import('/src/game/soul-battle.js');const fs=soulFigures.filter(f=>f.id.startsWith('BFX'));return await Promise.all(fs.map(f=>new Promise(resolve=>{const i=new Image;i.onload=()=>resolve({id:f.id,w:i.naturalWidth});i.onerror=()=>resolve({id:f.id,w:0});i.src=f.image;})));});assert.equal(loaded.length,24);assert.ok(loaded.every(x=>x.w>0));
 await page.evaluate(async()=>{const {launchBattle}=await import('/src/screens/soulDuelRuntime.js'),{pieceStarterDeck}=await import('/src/game/piece-starters.js'),{soulFigures}=await import('/src/game/soul-battle.js');const deck=pieceStarterDeck('materials-balloon');deck[0]='BFX001';deck[1]='BFX011';const p={owned:Object.fromEntries(soulFigures.map(f=>[f.id,25])),soulDecks:[deck,[],[],[],[]],soulDeckSlot:0,reducedMotion:true};window.tacticalProfile=p;const random=Math.random;Math.random=()=>.999999;try{window.tacticalBattle=launchBattle({profile:p,request:{difficulty:'easy'},onResolved:()=>({}),saveProfile:()=>{}});}finally{Math.random=random;}});
 const ready=()=>page.locator('.duel-dialog:not(.fx-running) [data-step="end"]:enabled').waitFor({timeout:60000});await ready();
 const count=await page.locator('[data-hand]').count();await page.locator('[data-hand="0"]').click();await page.locator('[data-hand-skill]').click();assert.match(await page.locator('.duel-sheet').textContent(),/墓地/);await page.locator('.duel-sheet [data-sheet-close]').click();assert.equal(await page.locator('[data-hand]').count(),count);
 await page.locator('[data-hand-skill]').click();await page.locator('[data-skill-confirm]').click();await ready();assert.equal(await page.locator('[data-hand]').count(),count);await page.locator('[data-zone="grave"]').click();assert.match(await page.locator('.duel-sheet').textContent(),/モブカセットクレープ/);await page.locator('.duel-sheet [data-sheet-close]').click();
 await page.locator('[data-hand="0"]').click();await page.locator('[data-summon]').click();await ready();await page.locator('.duel-field.side-0 [data-piece]').click();assert.match(await page.locator('.duel-sheet').textContent(),/ATK.*DEF/s);await page.screenshot({path:'docs/tactical-hand-and-detail-mobile.png'});await page.locator('.duel-sheet [data-sheet-close]').click();
 await page.locator('[data-step="end"]').click();
 for(let i=0;i<40;i++){await page.waitForTimeout(300);if(await page.locator('.duel-dialog:not(.fx-running) [data-pass]').count()){await page.locator('[data-pass]').click();continue;}if(await page.locator('.duel-dialog:not(.fx-running) [data-step="battle"]:enabled').count())break;}
 await page.locator('.duel-dialog:not(.fx-running) [data-step="battle"]:enabled').waitFor();assert.ok(await page.locator('.duel-field.side-1 [data-piece]').count());await page.locator('.duel-field.side-1 [data-piece]').first().click();assert.match(await page.locator('.duel-sheet').textContent(),/ATK.*DEF/s);await page.locator('.duel-sheet [data-sheet-close]').click();
 await page.locator('[data-log]').click();assert.match(await page.locator('.duel-sheet').textContent(),/シードデッキから2体ドロー/);await page.locator('.duel-sheet [data-sheet-close]').click();
 await page.locator('[data-quit]').click();await page.locator('[data-forfeit]').click();await page.locator('[data-close-result]').click();
 // Actual director shows the full enemy effect, including hand origin, and preserves it in the visible interval.
 const effect='自分ライフを30消費し、相手のソウルスキルを無効にする。その後1体ドローする。';
 await page.evaluate(async effect=>{const {createBattleDirector}=await import('/src/components/battle-director.js');const r=document.createElement('div');r.id='tactical-director';r.innerHTML='<div class="duel-fx"></div>';document.body.append(r);window.testDirector=createBattleDirector(r,{profile:{},style:{fast:false,cube:{id:'hero'}}});window.testRun=window.testDirector.run([{type:'skill',seq:999,side:1,id:'BFX023',name:'サイレント・カット',effect,fromHand:true}]);},effect);
 await page.locator('.fx-skill-effect').waitFor();assert.equal(await page.locator('.fx-skill-effect').textContent(),effect);await page.waitForTimeout(300);await page.screenshot({path:'docs/tactical-enemy-skill-mobile.png'});await page.evaluate(async()=>{await window.testRun;window.testDirector.destroy();document.querySelector('#tactical-director').remove();});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS Edge mobile: all 24 images; hand skill cancel/consume/cost/grave; ally and enemy tap detail; full effect log and enemy overlay; no page errors');
}finally{await browser.close();}
